set loc en

# Window Titles
::msgcat::mcset $loc "Tool"
::msgcat::mcset $loc "Message"
::msgcat::mcset $loc "Misc"
::msgcat::mcset $loc "Micro Map"
::msgcat::mcset $loc "Progress"

# Titles
::msgcat::mcset $loc STR
::msgcat::mcset $loc INT
::msgcat::mcset $loc WIS
::msgcat::mcset $loc DEX
::msgcat::mcset $loc CON
::msgcat::mcset $loc CHR
::msgcat::mcset $loc LEVEL
::msgcat::mcset $loc EXP
::msgcat::mcset $loc ADV
::msgcat::mcset $loc AU
::msgcat::mcset $loc AC

::msgcat::mcset $loc HP
::msgcat::mcset $loc SP
::msgcat::mcset $loc FD
::msgcat::mcset $loc WT

::msgcat::mcset $loc strength
::msgcat::mcset $loc intelligence
::msgcat::mcset $loc wisdom
::msgcat::mcset $loc dexterity
::msgcat::mcset $loc constitution
::msgcat::mcset $loc charisma

::msgcat::mcset $loc class
::msgcat::mcset $loc name
::msgcat::mcset $loc race
::msgcat::mcset $loc title

# Action Description
::msgcat::mcset $loc "Activate an equipment item"
::msgcat::mcset $loc "Eat an inventory item"
::msgcat::mcset $loc "Drink a potion in inventory"
::msgcat::mcset $loc "Read a scroll in inventory"
::msgcat::mcset $loc "Zap a rod in inventory"
::msgcat::mcset $loc "Aim a wand in inventory"
::msgcat::mcset $loc "Use a staff in inventory"
::msgcat::mcset $loc "Go up a dungeon level"
::msgcat::mcset $loc "Go down a dungeon level"

# Hack - autobar
::msgcat::mcset $loc "Use Mindcraft"
::msgcat::mcset $loc "Use racial/mutation power"

# Statusbar
::msgcat::mcset $loc status-message "Click for last message. Double-click for message history. Right-Click for options."

# Autobar
::msgcat::mcset $loc "Recite or study a prayer"
::msgcat::mcset $loc "Cast or study a spell"

# Help text
::msgcat::mcset $loc "Your character's %s"
::msgcat::mcset $loc "Click for a menu of actions."
::msgcat::mcset $loc "Click to display the Character Window."
::msgcat::mcset $loc "Your character's armor class "
::msgcat::mcset $loc "(total)"
::msgcat::mcset $loc "(base,bonus)"
::msgcat::mcset $loc ". Click to activate."
::msgcat::mcset $loc ". Click to change."
::msgcat::mcset $loc ". Click to toggle."
::msgcat::mcset $loc "Your character's gold"
::msgcat::mcset $loc "Current experience points"
::msgcat::mcset $loc "Experience points for next level"
::msgcat::mcset $loc " (min %d)"
::msgcat::mcset $loc "Your character's experience level"
::msgcat::mcset $loc "food level"
::msgcat::mcset $loc "hit points"
::msgcat::mcset $loc "spell points"
::msgcat::mcset $loc weight "weight being carried"
::msgcat::mcset $loc " (max %s)"
::msgcat::mcset $loc ". Right-Click for options."

# Context Menu
::msgcat::mcset $loc "Attach To Main"
::msgcat::mcset $loc "Attach To Misc"
::msgcat::mcset $loc "Float"
::msgcat::mcset $loc "Tall Layout"
::msgcat::mcset $loc "Wide Layout"
::msgcat::mcset $loc "Picture Labels"
::msgcat::mcset $loc "Text Labels"
::msgcat::mcset $loc "Show Bars"
::msgcat::mcset $loc "Hide Bars"
::msgcat::mcset $loc "Show Numbers"
::msgcat::mcset $loc "Hide Numbers"
::msgcat::mcset $loc "Show Max"
::msgcat::mcset $loc "Hide Max"
::msgcat::mcset $loc "Show"
::msgcat::mcset $loc showHP "Hit points"
::msgcat::mcset $loc showSP "Spell points"
::msgcat::mcset $loc showFD "Food level"
::msgcat::mcset $loc showWT "Weight being carried"

