set loc ja

# Window Titles
::msgcat::mcset $loc "Tool" ツール
::msgcat::mcset $loc "Message" メッセージ
::msgcat::mcset $loc "Misc" ステータス
::msgcat::mcset $loc "Micro Map" レーダー
::msgcat::mcset $loc "Progress" メーター

# Stat Titles
::msgcat::mcset $loc STR 腕力
::msgcat::mcset $loc INT 知力
::msgcat::mcset $loc WIS 賢さ
::msgcat::mcset $loc DEX 器用
::msgcat::mcset $loc CON 耐久
::msgcat::mcset $loc CHR 魅力
::msgcat::mcset $loc LEVEL レベル
::msgcat::mcset $loc EXP 経験
::msgcat::mcset $loc ADV 次レベル
::msgcat::mcset $loc AU 所持金
::msgcat::mcset $loc AC ＡＣ

::msgcat::mcset $loc HP
::msgcat::mcset $loc SP
::msgcat::mcset $loc FD
::msgcat::mcset $loc WT

::msgcat::mcset $loc strength 腕力
::msgcat::mcset $loc intelligence 知力
::msgcat::mcset $loc wisdom 賢さ
::msgcat::mcset $loc dexterity 器用さ
::msgcat::mcset $loc constitution 耐久力
::msgcat::mcset $loc charisma 魅力

::msgcat::mcset $loc class 職業
::msgcat::mcset $loc name 名前
::msgcat::mcset $loc race 種族
::msgcat::mcset $loc title 称号

# Action Description
::msgcat::mcset $loc "Activate an equipment item" アイテムを発動
::msgcat::mcset $loc "Eat an inventory item" 食料を食べる
::msgcat::mcset $loc "Drink a potion in inventory" 薬を飲む
::msgcat::mcset $loc "Read a scroll in inventory" 巻物を読む
::msgcat::mcset $loc "Zap a rod in inventory" ロッドを使う
::msgcat::mcset $loc "Aim a wand in inventory" 魔法棒を使う
::msgcat::mcset $loc "Use a staff in inventory" 杖を使う
::msgcat::mcset $loc "Go up a dungeon level" 階段を上る
::msgcat::mcset $loc "Go down a dungeon level" 階段を下る

::msgcat::mcset $loc status-message \
クリックで前のメッセージ。ダブルクリックでメッセージ履歴

# Autobar
::msgcat::mcset $loc "Recite or study a prayer" 祈祷を詠唱／学習する
::msgcat::mcset $loc "Cast or study a spell" 呪文を唱える／学習する

# Help text
::msgcat::mcset $loc "Your character's %s" "あなたの%s"
::msgcat::mcset $loc "Click for a menu of actions." クリックでメニュー表示
::msgcat::mcset $loc "Click to display the Character Window." クリックでキャラクタウィンドウ
::msgcat::mcset $loc "Your character's armor class " あなたのアーマークラス
::msgcat::mcset $loc "(total)" (合計)
::msgcat::mcset $loc "(base,bonus)" (基本、修正)
::msgcat::mcset $loc ". Click to activate."
::msgcat::mcset $loc ". Click to change."
::msgcat::mcset $loc ". Click to toggle." クリックで変更
::msgcat::mcset $loc "Your character's gold" あなたの所持金
::msgcat::mcset $loc "Current experience points" 現在の経験値
::msgcat::mcset $loc "Experience points for next level" 次のレベルまでの経験値
::msgcat::mcset $loc " (min %d)" (最小%d)
::msgcat::mcset $loc "Your character's experience level" あなたのレベル
::msgcat::mcset $loc "food level" 満腹度
::msgcat::mcset $loc "hit points" ヒットポイント
::msgcat::mcset $loc "spell points" マジックポイント
::msgcat::mcset $loc weight "weight being carried"
::msgcat::mcset $loc " (max %s)" (最大%s)
::msgcat::mcset $loc ". Right-Click for options." --右クリックでオプション

# Context Menu
::msgcat::mcset $loc "Attach To Main"
::msgcat::mcset $loc "Attach To Misc"
::msgcat::mcset $loc "Float"
::msgcat::mcset $loc "Tall Layout"
::msgcat::mcset $loc "Wide Layout"
::msgcat::mcset $loc "Picture Labels"
::msgcat::mcset $loc "Text Labels"
::msgcat::mcset $loc "Show Bars"
::msgcat::mcset $loc "Hide Bars"
::msgcat::mcset $loc "Show Numbers"
::msgcat::mcset $loc "Hide Numbers"
::msgcat::mcset $loc "Show Max"
::msgcat::mcset $loc "Hide Max"
::msgcat::mcset $loc "Show"
::msgcat::mcset $loc showHP "Hit points"
::msgcat::mcset $loc showSP "Spell points"
::msgcat::mcset $loc showFD "Food level"
::msgcat::mcset $loc showWT "Weight being carried"

