/*
 * File: list-effects.h
 * Purpose: List of effect types
 */

/*
 * "rating" is the power rating for an item activation, as a damage-per-blow
 * equivalent (x2). These ratings are used in the calculation of the power (and
 * therefore cost) of an item which has the effect as an activation, but NOT
 * for other items (e.g. potions, scrolls). Hence the use of INHIBIT_POWER.
 */

/* name aim rating description */
EFFECT(XXX, FALSE, 0, NULL)
EFFECT(ACID_BALL120, TRUE, 11, "shoots a radius-2 acid ball that inflicts {120} points of damage")
EFFECT(ACID_BOLT, TRUE, 6, "shoots an acid bolt that inflicts {10d8} points of damage")
EFFECT(ACID_BOLT2, TRUE, 7, "shoots an acid bolt that inflicts {12d8} points of damage")
EFFECT(ACQUIRE, FALSE, INHIBIT_POWER, "creates one good object on the floor near you")
EFFECT(ACQUIRE2, FALSE, INHIBIT_POWER, "creates {1+1d2} good objects on the ground near you")
EFFECT(ANNOY_MON, FALSE, 0, "awakens all sleeping monsters within {40} squares of you and hastes all monsters within line of sight")
EFFECT(ARROW, TRUE, 11, "fires a magical arrow that inflicts {150} points of damage")
EFFECT(BANISHMENT, FALSE, 20, "removes all non-unique monsters represented by a chosen symbol from the level, inflicting {1d4} points of damage for every monster removed")
EFFECT(BERSERKER, FALSE, 10, "cures {30} points of damage, removes fear and grants berserk strength for {50+1d50} turns")
EFFECT(BIZARRE, TRUE, 20, "does bizarre things")
EFFECT(BLESSING, FALSE, 6, "blesses you (a bonus of {+5} to armor class and {+10} to-hit) for {6+1d12} turns")
EFFECT(BLESSING2, FALSE, 7, "blesses you (a bonus of {+5} to armor class and {+10} to-hit) for {12+1d24} turns")
EFFECT(BLESSING3, FALSE, 8, "blesses you (a bonus of {+5} to armor class and {+10} to-hit) for {24+1d48} turns")
EFFECT(BLIND, FALSE, 0, "causes blindness that lasts for {75+4d25} turns")
EFFECT(BRAWN, FALSE, 30, "raises your strength at the expense of a random attribute")
EFFECT(INTELLECT, FALSE, 25, "raises your intelligence at the expense of a random attribute")
EFFECT(CONTEMPLATION, FALSE, 25, "raises your wisdom at the expense of a random attribute")
EFFECT(NIMBLENESS, FALSE, 25, "raises your dexterity at the expense of a random attribute")
EFFECT(TOUGHNESS, FALSE, 30, "raises your constitution at the expense of a random attribute")
EFFECT(CLAIRVOYANCE, FALSE, 23, "completely lights up and magically maps the current level, and detects all doors, stairs and traps in the immediate area")
EFFECT(COLD_BALL48, TRUE, 8, "shoots a radius-2 frost ball that inflicts {48} points of damage")
EFFECT(COLD_BALL96, TRUE, 10, "shoots a radius-2 frost ball that inflicts {96} points of damage")
EFFECT(COLD_BALL160, TRUE, 12, "shoots a radius-3 frost ball that inflicts {160} points of damage")
EFFECT(COLD_BALL200, TRUE, 13, "shoots a radius-3 frost ball that inflicts {200} points of damage")
EFFECT(COLD_BOLT, TRUE, 4, "shoots a frost bolt that inflicts {6d8} points of damage")
EFFECT(COLD_BOLT2, TRUE, 7, "shoots a frost bolt that inflicts {10d8} points of damage")
EFFECT(CONFUSE, FALSE, 0, "induces confusion that lasts for {10+4d5} turns")
EFFECT(CONFUSING, FALSE, 8, "enchants you with an aura of confusion that causes your next attack to confuse the target")
EFFECT(CREATE_HOUSE, FALSE, 0, "allows you to create a house from House Foundation Stones")
EFFECT(CREATE_TRAP, FALSE, 0, "creates traps on all empty squares around you")
EFFECT(CURE_BODY, FALSE, 7,  "cures all stunning, heals all cut damage, neutralizes poison and cures blindness")
EFFECT(CURE_MIND, FALSE, 8, "cures confusion and hallucination, removes fear and grants temporary resistance to confusion for {4d10} turns")
EFFECT(CURE_PARANOIA, FALSE, 2, "removes fear")
EFFECT(CURE_POISON, FALSE, 1, "neutralizes poison")
EFFECT(CURE_LIGHT, FALSE, 3, "cures {20} points of damage, heals {20} points worth of cuts and {5} points worth of confusion, and cures blindness")
EFFECT(CURE_SERIOUS, FALSE, 6, "cures {40} points of damage, heals all cut damage, and cures blindness and confusion")
EFFECT(CURE_CRITICAL, FALSE, 9, "cures {60} points of damage, cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURE_FULL300, FALSE, 12, "cures at least {300} points of damage (up to {35%%} of max HP), cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURE_FULL500, FALSE, 14, "cures {500} points of damage, cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURE_FULL1000, FALSE, 16, "cures {1000} points of damage, cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURE_FULL1200, FALSE, 18, "cures {1200} points of damage, cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURE_NONORLYBIG, FALSE, 21, "restores experience and all stats to maximum, heals {5000} hit points, and removes stunning, cuts, poison, hallucinations, blindness, confusion and amnesia")
EFFECT(CURE_TEMP, FALSE, 9, "cures all stunning, heals all cut damage, neutralizes poison, and cures blindness, confusion and amnesia")
EFFECT(CURSE_ARMOR, FALSE, 0, "curses the currently equipped body armor")
EFFECT(CURSE_WEAPON, FALSE, 0, "curses the currently wielded melee weapon")
EFFECT(DARKNESS, FALSE, 0, "darkens a radius-3 area (plus the entire room if you are currently in one) and blinds you for {3+1d5} turns")
EFFECT(DEEP_DESCENT, FALSE, 19, "transports you two levels down")
EFFECT(DESTROY_TDOORS, FALSE, 6, "destroys all traps and doors around you")
EFFECT(DESTRUCTION2, FALSE, 12, "destroys a radius-15 circular area centered at you and causes blindness lasting for {10+1d10} turns")
EFFECT(DETECT_ALL, FALSE, 10, "detects all treasure, objects, secret doors, stairs, traps and monsters in the immediate area")
EFFECT(DETECT_DOORSTAIR, FALSE, 6, "detects all doors and stairs in the immediate area")
EFFECT(DETECT_EVIL, FALSE, 6, "detects all evil monsters in the immediate area")
EFFECT(DETECT_INVIS, FALSE, 6, "detects all invisible monsters in the immediate area")
EFFECT(DETECT_TRAP, FALSE, 6, "detects all traps in the immediate area")
EFFECT(DETECT_TREASURE, FALSE, 6, "detects all treasure and objects in the immediate area")
EFFECT(DISARMING, TRUE, 7, "produces a beam that disarms all traps, unlocks all locked doors and reveals all secret doors")
EFFECT(DISPEL_ALL, FALSE, 11, "inflicts {120} points of damage on all monsters within line of sight")
EFFECT(DISPEL_EVIL, FALSE, 12, "inflicts {5*clvl} points of damage on all evil monsters within line of sight")
EFFECT(DISPEL_EVIL60, FALSE, 9, "inflicts {60} points of damage on all evil monsters within line of sight")
EFFECT(DISPEL_UNDEAD, FALSE, 9, "inflicts {60} points of damage on all undead creatures within line of sight")
EFFECT(DRAGON_BLACK, TRUE, 19, "allows you to breathe acid for {130} points of damage")
EFFECT(DRAGON_BLUE, TRUE, 18, "allows you to breathe lightning for {100} points of damage")
EFFECT(DRAGON_WHITE, TRUE, 18, "allows you to breathe frost for {110} points of damage")
EFFECT(DRAGON_RED, TRUE, 20, "allows you to breathe fire for {200} points of damage")
EFFECT(DRAGON_GREEN, TRUE, 19, "allows you to breathe gas for {150} points of damage")
EFFECT(DRAGON_MULTIHUED, TRUE, 20, "allows you to randomly breathe acid/lightning/fire/frost/gas for {250} points of damage")
EFFECT(DRAGON_SHADOW, TRUE, 21, "allows you to randomly breathe light/darkness for {200} points of damage")
EFFECT(DRAGON_LAW, TRUE, 23, "allows you to randomly breathe sound/shards for {230} points of damage")
EFFECT(DRAGON_GOLD, TRUE, 19, "allows you to breathe sound for {130} points of damage")
EFFECT(DRAGON_CHAOS, TRUE, 23, "allows you to randomly breathe chaos/disenchantment for {220} points of damage")
EFFECT(DRAGON_BALANCE, TRUE, 24, "allows you to randomly breathe sound/chaos/disenchantment/shards for {250} points of damage")
EFFECT(DRAGON_POWER, TRUE, 25, "allows you to randomly breathe the elements for {300} points of damage")
EFFECT(DRAGON_CRYSTAL, TRUE, 19, "allows you to breathe shards for {130} points of damage")
EFFECT(DRAGON_SILVER, TRUE, 19, "allows you to randomly breathe frost/inertia for {150} points of damage")
EFFECT(DRAGON_ETHEREAL, TRUE, 21, "allows you to breathe nether for {200} points of damage")
EFFECT(DRAGON_DLISK, TRUE, 21, "allows you to randomly breathe fire/nexus for {200} points of damage")
EFFECT(DRAGON_WATER, TRUE, 21, "allows you to breathe water for {200} points of damage")
EFFECT(DRAIN_LIFE, TRUE, 9, "inflicts {90} points of damage on a single creature that is not undead, a demon, a golem, an elemental or a vortex")
EFFECT(DRAIN_LIFE2, TRUE, 10, "inflicts {120} points of damage on a single creature that is not undead, a demon, a golem, an elemental or a vortex")
EFFECT(DRAIN_LIFE3, TRUE, 11, "inflicts {150} points of damage on a single creature that is not undead, a demon, a golem, an elemental or a vortex")
EFFECT(DRAIN_LIFE4, TRUE, 12, "inflicts {250} points of damage on a single creature that is not undead, a demon, a golem, an elemental or a vortex")
EFFECT(DRINK_BREATH, TRUE, 8, "causes you to breathe either frost or fire for {80} points of damage")
EFFECT(DRINK_GOOD, FALSE, 0, NULL)
EFFECT(DRINK_SALT, FALSE, 0, "induces vomiting, which will result in severe hunger but will also clear away all poison and cause {4} turns of paralysis")
EFFECT(EARTHQUAKES, FALSE, 5, "causes a radius-10 earthquake centered on you")
EFFECT(ELEC_BALL64, TRUE, 9, "shoots a radius-2 lightning ball that inflicts {64} points of damage")
EFFECT(ELEC_BALL250, TRUE, 14, "shoots a radius-3 lightning ball that inflicts {250} points of damage")
EFFECT(ELEC_BOLT, TRUE, 5, "shoots a lightning beam that inflicts {6d6} points of damage")
EFFECT(ENCHANT_ARMOR, FALSE, 12, "attempts to enchant a piece of armor once and also gives a chance to break a curse")
EFFECT(ENCHANT_ARMOR2, FALSE, 15, "attempts to enchant a piece of armor {2+1d3} times and also gives a chance to break a curse")
EFFECT(ENCHANT_TODAM, FALSE, 20, "attempts to magically enhance a weapon's to-dam bonus once and also gives a chance to break a curse")
EFFECT(ENCHANT_TOHIT, FALSE, 15, "attempts to magically enhance a weapon's to-hit bonus once and also gives a chance to break a curse")
EFFECT(ENCHANT_WEAPON, FALSE, 22, "attempts to magically enhance a weapon's to-dam and to-hit bonuses {1d3} times each and also gives a chance to break a curse")
EFFECT(ENLIGHTENMENT, FALSE, 22, "completely lights up and magically maps the current level")
EFFECT(ENLIGHTENMENT2, FALSE, INHIBIT_POWER, "restores and increases intelligence and wisdom, lights up and maps the current level, detects everything in the immediate area, and identifies all items you currently possess")
EFFECT(FIRE_BALL72, TRUE, 9, "shoots a radius-2 fire ball that inflicts {72} points of damage")
EFFECT(FIRE_BALL120, TRUE, 11, "shoots a radius-3 fire ball that inflicts {120} points of damage")
EFFECT(FIRE_BALL144, TRUE, 11, "shoots a radius-2 fire ball that inflicts {144} points of damage")
EFFECT(FIRE_BALL200, TRUE, 13, "shoots a radius-3 fire ball that inflicts {200} points of damage")
EFFECT(FIRE_BOLT, TRUE, 7, "shoots a fire bolt that inflicts {12d8} points of damage")
EFFECT(FOOD_BAD, FALSE, 0, NULL)
EFFECT(FOOD_GOOD, FALSE, 0, NULL)
EFFECT(FOOD_WAYBREAD, FALSE, 4, "cures {4d8} points of damage and neutralizes poison")
EFFECT(GAIN_ALL, FALSE, INHIBIT_POWER, "restores all stats to maximum, then permanently increases all stats")
EFFECT(GAIN_STR, FALSE, INHIBIT_POWER, "restores strength to maximum, then permanently increases strength")
EFFECT(GAIN_INT, FALSE, INHIBIT_POWER, "restores intelligence to maximum, then permanently increases intelligence")
EFFECT(GAIN_WIS, FALSE, INHIBIT_POWER, "restores wisdom to maximum, then permanently increases wisdom")
EFFECT(GAIN_DEX, FALSE, INHIBIT_POWER, "restores dexterity to maximum, then permanently increases dexterity")
EFFECT(GAIN_CON, FALSE, INHIBIT_POWER, "restores constitution to maximum, then permanently increases constitution")
EFFECT(GAIN_CHR, FALSE, INHIBIT_POWER, "restores charisma to maximum, then permanently increases charisma")
EFFECT(GAIN_EXP, FALSE, 0, "restores experience to maximum and grants up to {100000} experience points")
EFFECT(GAIN_EXP_LTD, FALSE, INHIBIT_POWER, "restores experience to maximum and grants either {100000} experience points or half the current experience point total plus {10}, whichever is less")
EFFECT(HASTE, FALSE, 10, "hastes you ({+10} to speed) for {20+1d20} turns")
EFFECT(HASTE2, FALSE, 13, "hastes you ({+10} to speed) for {75+1d75} turns")
EFFECT(HERO, FALSE, 7, "cures {10} points of damage, removes fear and grants heroism (resistance to fear, and a bonus of {+12} to-hit) for {25+1d25} turns")
EFFECT(IDENTIFY, FALSE, 9, "reveals all normal and hidden powers of one object")
EFFECT(IDENTIFY2, FALSE, 0, "reveals all normal and hidden powers of all carried objects")
EFFECT(ILLUMINATION, FALSE, 4, "lights up a radius-3 area, or the entire room if you are in one, inflicting {2d15} points of damage on any light-sensitive creatures within the radius")
EFFECT(LIGHT, FALSE, 4, "lights up a radius-2 area, or the entire room if you are in one, inflicting {2d8} points of damage on any light-sensitive creatures within the radius")
EFFECT(LIGHT_LINE, TRUE, 6, "lights up a line of squares, inflicting {6d8} points of damage on light-sensitive creatures on the line")
EFFECT(LOSCONF, FALSE, 10, "attempts to confuse all non-unique monsters within line of sight")
EFFECT(LOSE_EXP, FALSE, 0, "drains {25%%} of your experience total")
EFFECT(LOSHASTE, FALSE, 0, "hastes all monsters within line of sight")
EFFECT(LOSKILL, FALSE, 25, "removes all non-unique monsters within {20} squares of you, inflicting {1d3} points of damage for every monster removed")
EFFECT(LOSSLEEP, FALSE, 8, "attempts to put all non-unique monsters within line of sight to sleep")
EFFECT(LOSSLOW, FALSE, 7, "attempts to slow down all non-unique monsters within line of sight")
EFFECT(MANA_BOLT, TRUE, 7, "shoots a mana bolt that inflicts {12d8} points of damage")
EFFECT(MAPPING, FALSE, 10, "maps out a portion of the level centered on you")
EFFECT(MISSILE, TRUE, 3, "fires a magic missile that inflicts {3d4} points of damage")
EFFECT(MON_CLONE, TRUE, 0, "hastes and fully heals a single monster, and spawns a new monster of the same type if not unique")
EFFECT(MON_CONFUSE, TRUE, 3, "attempts to confuse a single non-unique monster")
EFFECT(MON_HASTE, TRUE, 0, "hastes a single monster")
EFFECT(MON_HEAL, TRUE, 0, "cures a single monster for {4d6} points of damage")
EFFECT(MON_SCARE, TRUE, 3, "attempts to scare a single non-unique monster")
EFFECT(MON_SLEEP, TRUE, 3, "attempts to put a single non-unique monster to sleep")
EFFECT(MON_SLOW, TRUE, 3, "attempts to slow down a single non-unique monster")
EFFECT(PARALYZE, FALSE, 0, "induces paralysis that lasts for {5+1d5} turns")
EFFECT(POISON, FALSE, 0, "poisons you (adding {10+2d7} points to the poison counter)")
EFFECT(POLYMORPH, TRUE, 7, "attempts to polymorph a single non-unique monster")
EFFECT(POLY_RACE, FALSE, 0, "attempts to polymorph you into the corresponding monster")
EFFECT(PROBING, FALSE, 8, "probes all monsters within line of sight")
EFFECT(PROTEVIL, FALSE, 6, "grants the enchantment of protection from evil for a duration equal to {1d25} plus three times your character level")
EFFECT(RAGE_BLESS_RESIST, FALSE, 21, "cures {30} points of damage, removes fear, and grants berserk strength, blessing and temporary resistance for {50+1d50} turns")
EFFECT(RECALL, FALSE, 15, "takes you (after a short while) from the dungeon to the town or from the town to the deepest level you have visited in the dungeon")
EFFECT(RECHARGE, FALSE, 11, "tries to recharge a wand or staff, destroying the wand or staff on failure")
/*EFFECT(REMOVE_CURSE, FALSE, 8, "removes all ordinary curses from one carried item")
EFFECT(REMOVE_CURSE2, FALSE, 20, "removes all ordinary and heavy curses from all carried items")*/
EFFECT(REM_FEAR_POIS, FALSE, 3, "removes fear and neutralizes poison")
EFFECT(RESIST_ALL, FALSE, 10, "grants temporary resistance to acid, lightning, fire, cold and poison for {20+1d20} turns")
EFFECT(RESIST_ALL_LORDLY, FALSE, 10, "grants temporary resistance to acid, lightning, fire, cold and poison for {40+1d40} turns")
EFFECT(RESIST_ACID, FALSE, 4, "grants temporary resistance to acid for {10+1d10} turns")
EFFECT(RESIST_COLD, FALSE, 4, "grants temporary resistance to cold for {10+1d10} turns")
EFFECT(RESIST_ELEC, FALSE, 4, "grants temporary resistance to lightning for {10+1d10} turns")
EFFECT(RESIST_FIRE, FALSE, 4, "grants temporary resistance to fire for {10+1d10} turns")
EFFECT(RESIST_POIS, FALSE, 4, "grants temporary resistance to poison for {10+1d10} turns")
EFFECT(RESTORE_ALL, FALSE, 15, "restores all stats to maximum")
EFFECT(RESTORE_LIFE, FALSE, 8, "restores experience to maximum")
EFFECT(RESTORE_MANA, FALSE, 10, "restores 500 mana points")
EFFECT(RESTORE_MANA2, FALSE, 20, "restores mana points to maximum")
EFFECT(RESTORE_ST_LEV, FALSE, 17, "restores experience points and all stats to maximum")
EFFECT(RESURRECT, FALSE, 0, "brings back to life a nearby ghost character")
EFFECT(RING_ACID, TRUE, 11, "shoots a radius-2 acid ball that inflicts {70} points of damage and grants temporary resistance to acid for {20+1d20} turns")
EFFECT(RING_FLAMES, TRUE, 11, "shoots a radius-2 fire ball that inflicts {80} points of damage and grants temporary resistance to fire for {20+1d20} turns")
EFFECT(RING_ICE, TRUE, 11, "shoots a radius-2 frost ball that inflicts {75} points of damage and grants temporary resistance to cold for {20+1d20} turns")
EFFECT(RING_LIGHTNING, TRUE, 11, "shoots a radius-2 lightning ball that inflicts {85} points of damage and grants temporary resistance to lightning for {20+1d20} turns")
EFFECT(RUNE, FALSE, 20, "inscribes a glyph of warding beneath you, blocking monsters from moving into that space")
EFFECT(SATISFY, FALSE, 7, "magically renders you well-fed (but not satiated)")
EFFECT(SHERO, FALSE, 9, "cures {30} points of damage, removes fear and grants berserk strength (resistance to fear, a bonus of {+12} to-hit, and a penalty of {-10} to AC) for {25+1d25} turns")
EFFECT(SHROOM_DEBILITY, FALSE, 5, "restores mana points to maximum but also reduces either strength or constitution")
EFFECT(SHROOM_EMERGENCY, FALSE, 7, "grants temporary resistance to fire and cold for {20+1d20} turns, cures {200} points of damage, but also causes you to hallucinate for {200+1d100} turns")
EFFECT(SHROOM_PURGING, FALSE, 5, "makes you very hungry but neutralizes poison and restores strength and constitution")
EFFECT(SHROOM_SPRINTING, FALSE, 5, "speeds you up ({+10} to speed) for {100} turns and then slows you down ({-10} to speed) for {100} extra turns")
EFFECT(SHROOM_STONE, FALSE, 5, "turns your skin to stone (a bonus of {+40} to AC, and a penalty of {-5} to speed) for {60+1d40} turns")
EFFECT(SHROOM_TERROR, FALSE, 5, "speeds you up ({+5} to speed) but also makes you mortally afraid for {80+1d40} turns")
EFFECT(SLEEPII, FALSE, 8, "attempts to put all non-unique monsters around you to sleep")
EFFECT(SLOW, FALSE, 0, "slows you down ({-10} to speed) for {20+1d20} turns")
EFFECT(STAFF_HOLY, FALSE, 12, "inflicts {120} points of damage on all evil monsters in sight, heals {50} hit points, cures all temporary negative effects, and grants protection from evil for {1d25+3*clvl} turns")
EFFECT(STAFF_MAGI, FALSE, 20, "restores both intelligence and mana points to maximum")
EFFECT(STAR_BALL, FALSE, 18, "shoots a radius-3 lightning ball that inflicts {150} points of damage in all eight cardinal directions")
EFFECT(STARLIGHT, FALSE, 5, "fires a line of light in all eight cardinal directions, inflicting {6d8} points of damage on light-sensitive creatures caught in one of the lines")
EFFECT(STARLIGHT2, FALSE, 7, "fires a line of light in all eight cardinal directions, inflicting {10d8} points of damage on light-sensitive creatures caught in one of the lines")
EFFECT(STINKING_CLOUD, TRUE, 3, "shoots a radius-2 poison cloud that inflicts {12} points of damage")
EFFECT(STONE_TO_MUD, TRUE, 6, "turns stone into mud and inflicts {20+1d30} points of damage to monsters susceptible to rock remover")
EFFECT(SUMMON_MON, FALSE, 0, "summons {1d3} monsters generated at the current dungeon level")
EFFECT(SUMMON_UNDEAD, FALSE, 0, "summons {1d3} non-unique undead monsters that are generated at the current dungeon level")
EFFECT(TDOOR_DEST, TRUE, 5, "destroys all doors and disarms all traps in a line")
EFFECT(TELE_LEVEL, FALSE, 15, "teleports you one level up or down (chosen at random)")
EFFECT(TELE_LEVEL2, FALSE, 0, "allows you to cross floors and ceilings for {20+1d20} turns")
EFFECT(TELE_LONG, FALSE, 6, "teleports you randomly up to {100} squares away")
EFFECT(TELE_OTHER, TRUE, 11, "produces a beam that teleports all monsters caught in it up to {100} squares away")
EFFECT(TELE_PHASE, FALSE, 5, "teleports you randomly up to {10} squares away")
EFFECT(TMD_ESP, FALSE, 10, "cures blindness and grants the power of telepathy for {12+6d6} turns")
EFFECT(TMD_INFRA, FALSE, 5, "extends your infravision by {50} feet for {100+4d25} turns")
EFFECT(TMD_SINVIS, FALSE, 7, "enables you to see invisible creatures for {12+2d6} turns")
EFFECT(TRAP_DOOR, FALSE, 0, "a trap door drops you down a level")
EFFECT(TRAP_PIT, FALSE, 0, "a pit trap - the fall might hurt")
EFFECT(TRAP_PIT_SPIKES, FALSE, 0, "a pit trap, with nasty spikes")
EFFECT(TRAP_PIT_POISON, FALSE, 0, "a pit trap, with poisoned spikes")
EFFECT(TRAP_RUNE_SUMMON, FALSE, 0, "a rune which summons monsters")
EFFECT(TRAP_RUNE_TELEPORT, FALSE, 0, "a rune which teleports")
EFFECT(TRAP_SPOT_FIRE, FALSE, 0, "a magical fire trap")
EFFECT(TRAP_SPOT_ACID, FALSE, 0, "a magical acid trap")
EFFECT(TRAP_DART_SLOW, FALSE, 0, "a dart which slows movements")
EFFECT(TRAP_DART_LOSE_STR, FALSE, 0, "a dart which drains strength")
EFFECT(TRAP_DART_LOSE_DEX, FALSE, 0, "a dart which drains dexterity")
EFFECT(TRAP_DART_LOSE_CON, FALSE, 0, "a dart which drains constitution")
EFFECT(TRAP_GAS_BLIND, FALSE, 0, "blinding gas")
EFFECT(TRAP_GAS_CONFUSE, FALSE, 0, "confusing gas")
EFFECT(TRAP_GAS_POISON, FALSE, 0, "poison gas")
EFFECT(TRAP_GAS_SLEEP, FALSE, 0, "soporific gas")
EFFECT(WAND_BREATH, TRUE, 12, "randomly shoots a radius-3 fire/frost/acid/lightning/poison ball that inflicts {200/160/200/160/120} points of damage")
EFFECT(WONDER, TRUE, 9, "has a random effect chosen from the various wand effects")
