/*********************************************************
* All sources in Hellbound are Copyright (c) 2008 Konijn *
* I Konijn, release all code and data under the terms of *
* of the GNU General Public License (version 2), as well *
* as under the traditional Angband license. Distribution *
* is allowed both under the terms of the GPL (version 2) *
* or under the terms of the traditional Angband license. *
*********************************************************/

//Global Objects

var vocations;

//Private Objects

//var _yyy;          //xxx

//Initialization

function initVocations(){
  vocations = new Object();
  vocations.all = "Warrior,Mage,Priest,Rogue,Hunter,Paladin,Spellblade,Hell Knight,Mystic,Orphic,High Mage,Druid,Warlock".split(",");

  vocations["Warrior"] = { 
    "strength" : 5,
    "intelligence" : -2,
    "wisdom" : -2,
    "dexterity" : 2,
    "constitution" : 2,
    "charisma" : -1,
    "disarming" : 25,
    "wizardry" : 18,
    "occlusion" : 18,
    "alchemy" : 18,
    "appraising" : 14,
    "stealth" : 1,
    "searching" : 14,
    "perception" : 2,
    "combat" : 70,
    "missiles" : 55,
    "wizardry_slice" : 10,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 45,
    "missiles_slice" : 45,
    "hitdice" : 9,
    "experience_rate" : 0,
    "stat_1" : "strength",
    "stat_2" : "constitution",
    "stat_3" : "dexterity",
    "spell_book" : TV_NO_BOOK,
    "spell_stat" : "strength",
    "spell_type" : MENTAL,
    "first_spell" : 99,
    "mana_encumbrance" : 99,
    "Miracles" : NO,
    "Sorcery" : NO,
    "Nature" : NO,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : NO,
    "Demonic" : NO,
    "gear" : [ '[ Chain Mail' , '| & Broad Sword~' , '= Fear Resistance' ],
    "resist_fear" : 30
  };

  vocations["Mage"] = { 
    "strength" : -5,
    "intelligence" : 3,
    "wisdom" : 0,
    "dexterity" : 1,
    "constitution" : -2,
    "charisma" : 1,
    "disarming" : 30,
    "wizardry" : 33,
    "occlusion" : 33,
    "alchemy" : 33,
    "appraising" : 16,
    "stealth" : 2,
    "searching" : 16,
    "perception" : 20,
    "combat" : 34,
    "missiles" : 20,
    "wizardry_slice" : 10,
    "occlusion_slice" : 9,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 15,
    "missiles_slice" : 15,
    "hitdice" : 0,
    "experience_rate" : 30,
    "stat_1" : "intelligence",
    "stat_2" : "constitution",
    "stat_3" : "strength",
    "spell_book" : TV_SORCERY_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 1,
    "mana_encumbrance" : 300,
    "Miracles" : SAME,
    "Sorcery" : SAME,
    "Nature" : SAME,
    "Chaos" : SAME,
    "Death" : SAME,
    "Tarot" : SAME,
    "Charms" : SAME,
    "Somatic" : SAME,
    "Demonic" : SAME,
    "gear" : [ '| & Dagger~' , '( & Robe~' ]
  };

  vocations["Priest"] = { 
    "strength" : -1,
    "intelligence" : -3,
    "wisdom" : 3,
    "dexterity" : -1,
    "constitution" : 0,
    "charisma" : 2,
    "disarming" : 25,
    "wizardry" : 31,
    "occlusion" : 31,
    "alchemy" : 31,
    "appraising" : 16,
    "stealth" : 2,
    "searching" : 16,
    "perception" : 8,
    "combat" : 48,
    "missiles" : 35,
    "wizardry_slice" : 9,
    "occlusion_slice" : 12,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 20,
    "missiles_slice" : 20,
    "hitdice" : 2,
    "experience_rate" : 20,
    "stat_1" : "wisdom",
    "stat_2" : "constitution",
    "stat_3" : "strength",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "wisdom",
    "spell_type" : DIVINE,
    "first_spell" : 1,
    "mana_encumbrance" : 350,
    "Miracles" : SUPER,
    "Sorcery" : WORSE,
    "Nature" : SAME,
    "Chaos" : WORSE,
    "Death" : SUPER,
    "Tarot" : WORSE,
    "Charms" : WORSE,
    "Somatic" : WORSE,
    "Demonic" : POOR,
    "gear" : [ '\\ & Mace~' , '( & Robe~' ]
  };

  vocations["Rogue"] = { 
    "strength" : 2,
    "intelligence" : 1,
    "wisdom" : -2,
    "dexterity" : 3,
    "constitution" : 1,
    "charisma" : -1,
    "disarming" : 45,
    "wizardry" : 30,
    "occlusion" : 30,
    "alchemy" : 30,
    "appraising" : 32,
    "stealth" : 5,
    "searching" : 32,
    "perception" : 24,
    "combat" : 60,
    "missiles" : 66,
    "wizardry_slice" : 13,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 40,
    "missiles_slice" : 30,
    "hitdice" : 6,
    "experience_rate" : 25,
    "stat_1" : "dexterity",
    "stat_2" : "intelligence",
    "stat_3" : "constitution",
    "spell_book" : TV_SORCERY_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 5,
    "mana_encumbrance" : 350,
    "Miracles" : POOR,
    "Sorcery" : SAME,
    "Nature" : POOR,
    "Chaos" : SAME,
    "Death" : BETTER,
    "Tarot" : BETTER,
    "Charms" : BETTER,
    "Somatic" : WORSE,
    "Demonic" : WORSE,
    "gear" : [ '| & Dagger~' , '( Soft Leather Armour' ]
  };

  vocations["Hunter"] = { 
    "strength" : 2,
    "intelligence" : 2,
    "wisdom" : 0,
    "dexterity" : 1,
    "constitution" : 1,
    "charisma" : 1,
    "disarming" : 30,
    "wizardry" : 30,
    "occlusion" : 30,
    "alchemy" : 30,
    "appraising" : 24,
    "stealth" : 3,
    "searching" : 24,
    "perception" : 16,
    "combat" : 56,
    "missiles" : 72,
    "wizardry_slice" : 9,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 30,
    "missiles_slice" : 45,
    "hitdice" : 4,
    "experience_rate" : 30,
    "stat_1" : "constitution",
    "stat_2" : "dexterity",
    "stat_3" : "intelligence",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 3,
    "mana_encumbrance" : 400,
    "Miracles" : NO,
    "Sorcery" : WORSE,
    "Nature" : BETTER,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : WORSE,
    "Charms" : WORSE,
    "Somatic" : WORSE,
    "Demonic" : NO,
    "gear" : [ '| & Broad Sword~' , '( Soft Leather Armour' ]
  };

  vocations["Paladin"] = { 
    "strength" : 3,
    "intelligence" : -3,
    "wisdom" : 1,
    "dexterity" : 0,
    "constitution" : 2,
    "charisma" : 2,
    "disarming" : 20,
    "wizardry" : 25,
    "occlusion" : 25,
    "alchemy" : 25,
    "appraising" : 12,
    "stealth" : 1,
    "searching" : 12,
    "perception" : 2,
    "combat" : 68,
    "missiles" : 40,
    "wizardry_slice" : 9,
    "occlusion_slice" : 11,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 35,
    "missiles_slice" : 30,
    "hitdice" : 6,
    "experience_rate" : 35,
    "stat_1" : "strength",
    "stat_2" : "wisdom",
    "stat_3" : "constitution",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "wisdom",
    "spell_type" : DIVINE,
    "first_spell" : 1,
    "mana_encumbrance" : 400,
    "Miracles" : BETTER,
    "Sorcery" : NO,
    "Nature" : NO,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : NO,
    "Demonic" : NO,
    "gear" : [ '| & Long Sword~' , '[ Metal Scale Mail' , '? Protection from Evil' ],
    "resist_fear" : 30
  };

  vocations["Spellblade"] = { 
    "strength" : 2,
    "intelligence" : 2,
    "wisdom" : 0,
    "dexterity" : 1,
    "constitution" : 0,
    "charisma" : 1,
    "disarming" : 30,
    "wizardry" : 29,
    "occlusion" : 29,
    "alchemy" : 29,
    "appraising" : 18,
    "stealth" : 2,
    "searching" : 18,
    "perception" : 16,
    "combat" : 50,
    "missiles" : 25,
    "wizardry_slice" : 9,
    "occlusion_slice" : 9,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 20,
    "missiles_slice" : 20,
    "hitdice" : 4,
    "experience_rate" : 50,
    "stat_1" : "strength",
    "stat_2" : "intelligence",
    "stat_3" : "constitution",
    "spell_book" : TV_SORCERY_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 1,
    "mana_encumbrance" : 350,
    "Miracles" : WORSE,
    "Sorcery" : WORSE,
    "Nature" : WORSE,
    "Chaos" : WORSE,
    "Death" : WORSE,
    "Tarot" : WORSE,
    "Charms" : SUPER,
    "Somatic" : WORSE,
    "Demonic" : WORSE,
    "gear" : [ '| & Long Sword~' , '( & Robe~' ]
  };

  vocations["Hell Knight"] = { 
    "strength" : 2,
    "intelligence" : 1,
    "wisdom" : 0,
    "dexterity" : 1,
    "constitution" : 2,
    "charisma" : -2,
    "disarming" : 20,
    "wizardry" : 25,
    "occlusion" : 25,
    "alchemy" : 25,
    "appraising" : 14,
    "stealth" : 1,
    "searching" : 14,
    "perception" : 12,
    "combat" : 65,
    "missiles" : 40,
    "wizardry_slice" : 9,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 34,
    "missiles_slice" : 29,
    "hitdice" : 6,
    "experience_rate" : 35,
    "stat_1" : "strength",
    "stat_2" : "intelligence",
    "stat_3" : "constitution",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : DIVINE,
    "first_spell" : 2,
    "mana_encumbrance" : 400,
    "Miracles" : NO,
    "Sorcery" : NO,
    "Nature" : NO,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : NO,
    "Demonic" : BETTER,
    "gear" : [ '| & Long Sword~' , '[ Metal Scale Mail' ],
    "resist_fear" : 20,
    "resist_nether" : 30
  };

  vocations["Mystic"] = { 
    "strength" : 2,
    "intelligence" : -1,
    "wisdom" : 1,
    "dexterity" : 3,
    "constitution" : 2,
    "charisma" : 1,
    "disarming" : 45,
    "wizardry" : 20,
    "occlusion" : 20,
    "alchemy" : 20,
    "appraising" : 32,
    "stealth" : 5,
    "searching" : 32,
    "perception" : 24,
    "combat" : 64,
    "missiles" : 60,
    "wizardry_slice" : 13,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 40,
    "missiles_slice" : 30,
    "hitdice" : 6,
    "experience_rate" : 40,
    "stat_1" : "dexterity",
    "stat_2" : "wisdom",
    "stat_3" : "constitution",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "wisdom",
    "spell_type" : MENTAL,
    "first_spell" : 1,
    "mana_encumbrance" : 300,
    "Miracles" : NO,
    "Sorcery" : NO,
    "Nature" : NO,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : SUPER,
    "Demonic" : NO,
    "gear" : [ '( & Robe~' , '! Healing'],
    "free_action" : function(level){ return level>24 && player.calc.lightArmor }
  };

  vocations["Orphic"] = { 
    "strength" : -1,
    "intelligence" : 0,
    "wisdom" : 3,
    "dexterity" : -1,
    "constitution" : -1,
    "charisma" : 2,
    "disarming" : 30,
    "wizardry" : 30,
    "occlusion" : 30,
    "alchemy" : 30,
    "appraising" : 22,
    "stealth" : 3,
    "searching" : 22,
    "perception" : 16,
    "combat" : 50,
    "missiles" : 40,
    "wizardry_slice" : 10,
    "occlusion_slice" : 10,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 20,
    "missiles_slice" : 30,
    "hitdice" : 2,
    "experience_rate" : 25,
    "stat_1" : "wisdom",
    "stat_2" : "constitution",
    "stat_3" : "dexterity",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "wisdom",
    "spell_type" : MENTAL,
    "first_spell" : 99,
    "mana_encumbrance" : 300,
    "Miracles" : NO,
    "Sorcery" : NO,
    "Nature" : NO,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : NO,
    "Demonic" : NO,
    "gear" : [ '| & Short Sword~' , '( & Robe~' , '! Restore Mana' ],
    "resist_fear" : 10,
    "sustain_wisdom" : 20,
    "resist_confusion" : 30,
    "telepathy" : 40
  };

  vocations["High Mage"] = { 
    "strength" : -5,
    "intelligence" : 4,
    "wisdom" : 0,
    "dexterity" : 0,
    "constitution" : -2,
    "charisma" : 1,
    "disarming" : 30,
    "wizardry" : 33,
    "occlusion" : 33,
    "alchemy" : 33,
    "appraising" : 16,
    "stealth" : 2,
    "searching" : 16,
    "perception" : 20,
    "combat" : 34,
    "missiles" : 20,
    "wizardry_slice" : 10,
    "occlusion_slice" : 9,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 15,
    "missiles_slice" : 15,
    "hitdice" : 0,
    "experience_rate" : 30,
    "stat_1" : "intelligence",
    "stat_2" : "constitution",
    "stat_3" : "strength",
    "spell_book" : TV_SORCERY_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 1,
    "mana_encumbrance" : 300,
    "Miracles" : BETTER,
    "Sorcery" : BETTER,
    "Nature" : BETTER,
    "Chaos" : BETTER,
    "Death" : BETTER,
    "Tarot" : BETTER,
    "Charms" : BETTER,
    "Somatic" : BETTER,
    "Demonic" : BETTER,
    "gear" : [ '| & Dagger~' , '( & Robe~' ]
  };

  vocations["Druid"] = { 
    "strength" : -1,
    "intelligence" : -3,
    "wisdom" : 4,
    "dexterity" : -2,
    "constitution" : 0,
    "charisma" : 3,
    "disarming" : 25,
    "wizardry" : 31,
    "occlusion" : 31,
    "alchemy" : 31,
    "appraising" : 16,
    "stealth" : 2,
    "searching" : 16,
    "perception" : 8,
    "combat" : 48,
    "missiles" : 35,
    "wizardry_slice" : 9,
    "occlusion_slice" : 12,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 20,
    "missiles_slice" : 20,
    "hitdice" : 2,
    "experience_rate" : 20,
    "stat_1" : "wisdom",
    "stat_2" : "charisma",
    "stat_3" : "constitution",
    "spell_book" : TV_MIRACLES_BOOK,
    "spell_stat" : "wisdom",
    "spell_type" : DIVINE,
    "first_spell" : 1,
    "mana_encumbrance" : 350,
    "Miracles" : NO,
    "Sorcery" : NO,
    "Nature" : SUPER,
    "Chaos" : NO,
    "Death" : NO,
    "Tarot" : NO,
    "Charms" : NO,
    "Somatic" : NO,
    "Demonic" : NO,
    "gear" : [ '\\ & Quarterstaff~' , '= Sustain Mind' , '( & Robe~' ]
  };

  vocations["Warlock"] = { 
    "strength" : -5,
    "intelligence" : 4,
    "wisdom" : 0,
    "dexterity" : 0,
    "constitution" : -2,
    "charisma" : 1,
    "disarming" : 30,
    "wizardry" : 33,
    "occlusion" : 33,
    "alchemy" : 33,
    "appraising" : 16,
    "stealth" : 2,
    "searching" : 16,
    "perception" : 20,
    "combat" : 34,
    "missiles" : 20,
    "wizardry_slice" : 10,
    "occlusion_slice" : 9,
    "stealth_slice" : 0,
    "searching_slice" : 0,
    "perception_slice" : 0,
    "combat_slice" : 15,
    "missiles_slice" : 15,
    "hitdice" : 0,
    "experience_rate" : 30,
    "stat_1" : "intelligence",
    "stat_2" : "constitution",
    "stat_3" : "dexterity",
    "spell_book" : TV_SORCERY_BOOK,
    "spell_stat" : "intelligence",
    "spell_type" : MAGIC,
    "first_spell" : 1,
    "mana_encumbrance" : 300,
    "Miracles" : WORSE,
    "Sorcery" : WORSE,
    "Nature" : WORSE,
    "Chaos" : BETTER,
    "Death" : WORSE,
    "Tarot" : WORSE,
    "Charms" : WORSE,
    "Somatic" : WORSE,
    "Demonic" : BETTER,
    "gear" : [ '| & Long Sword~' , '( & Robe~' ],
    "resist_nether" : 20
  };



}
//Public Functions

//function doXXX(){}

//Private Functions

//function doYYY(){}
