set loc en

# Window title
::msgcat::mcset $loc Squelch

# Squelch menu
::msgcat::mcset $loc Squelch
::msgcat::mcset $loc "Save As Default"
::msgcat::mcset $loc "Load Default"

# Mode menu
::msgcat::mcset $loc Mode
::msgcat::mcset $loc None
::msgcat::mcset $loc Cursed
::msgcat::mcset $loc Average
::msgcat::mcset $loc Good
::msgcat::mcset $loc Excellent
::msgcat::mcset $loc All
::msgcat::mcset $loc "Select All"

# Pages
::msgcat::mcset $loc Armor
::msgcat::mcset $loc Weapons
::msgcat::mcset $loc Other

# Search dialog
::msgcat::mcset $loc find-prompt Name

