set loc en

# Window title
# ex "Table of Contents - AngbandTk Help"
::msgcat::mcset $loc wm-title "%s - %s Help"

# Menu
::msgcat::mcset $loc Help
::msgcat::mcset $loc "Hide Contents"
::msgcat::mcset $loc "Show Contents"

# Toolbar
::msgcat::mcset $loc Hide
::msgcat::mcset $loc Back
::msgcat::mcset $loc Next
::msgcat::mcset $loc Refresh

# Contents
::msgcat::mcset $loc Contents

# Font
::msgcat::mcset $loc font,size {8 10 12 14 16 18 24}
::msgcat::mcset $loc font,fixed Courier
::msgcat::mcset $loc font,varwid Helvetica

# Find
::msgcat::mcset $loc find-prompt String
