MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = activation.txt artifact.txt blow_effects.txt blow_methods.txt \
 body.txt brand.txt chest_trap.txt class.txt constants.txt curse.txt \
 dragon_breed.txt dungeon.txt dungeon_profile.txt ego_item.txt flavor.txt \
 hints.txt history.txt monster.txt monster_base.txt monster_spell.txt names.txt \
 object.txt object_base.txt object_power.txt object_property.txt p_race.txt \
 pain.txt pit.txt player_property.txt player_timed.txt projection.txt \
 quest.txt realm.txt room_template.txt slay.txt socials.txt store.txt \
 summon.txt terrain.txt town.txt town_brandywine.txt town_bree.txt \
 town_feat.txt town_gondolin.txt town_lothlorien.txt town_minas_anor.txt \
 town_umbar.txt trap.txt vault.txt visuals.txt wild_feat.txt wild_info.txt \
 admin_stuff.txt level_golds.txt
PACKAGE = gamedata
