
(define-feature-type 0 "<darkness>" 1 #\Space :mimic nil)
(define-feature-type 1 "open floor" 1 #\. :mimic nil)
(define-feature-type 2 "invisible trap" 1 #\. :mimic 1)
(define-feature-type 3 "glyph of warding" 11 #\; :mimic nil)
(define-feature-type 4 "open door" 15 #\' :mimic nil)
(define-feature-type 5 "broken door" 15 #\' :mimic nil)
(define-feature-type 6 "up staircase" 1 #\< :mimic nil)
(define-feature-type 7 "down staircase" 1 #\> :mimic nil)
(define-feature-type 8 "General Store" 15 #\1 :mimic nil)
(define-feature-type 9 "Armoury" 2 #\2 :mimic nil)
(define-feature-type 10 "Weapon Smiths" 1 #\3 :mimic nil)
(define-feature-type 11 "Temple" 5 #\4 :mimic nil)
(define-feature-type 12 "Alchemy Shop" 6 #\5 :mimic nil)
(define-feature-type 13 "Magic Shop" 4 #\6 :mimic nil)
(define-feature-type 14 "Black Market" 8 #\7 :mimic nil)
(define-feature-type 15 "Home" 11 #\8 :mimic nil)
(define-feature-type 16 "trap door" 1 #\^ :mimic nil)
(define-feature-type 17 "pit" 2 #\^ :mimic nil)
(define-feature-type 18 "pit" 2 #\^ :mimic nil)
(define-feature-type 19 "pit" 2 #\^ :mimic nil)
(define-feature-type 20 "strange rune" 3 #\^ :mimic nil)
(define-feature-type 21 "strange rune" 3 #\^ :mimic nil)
(define-feature-type 22 "discolored spot" 7 #\^ :mimic nil)
(define-feature-type 23 "discolored spot" 7 #\^ :mimic nil)
(define-feature-type 24 "dart trap" 4 #\^ :mimic nil)
(define-feature-type 25 "dart trap" 4 #\^ :mimic nil)
(define-feature-type 26 "dart trap" 4 #\^ :mimic nil)
(define-feature-type 27 "dart trap" 4 #\^ :mimic nil)
(define-feature-type 28 "gas trap" 5 #\^ :mimic nil)
(define-feature-type 29 "gas trap" 5 #\^ :mimic nil)
(define-feature-type 30 "gas trap" 5 #\^ :mimic nil)
(define-feature-type 31 "gas trap" 5 #\^ :mimic nil)
(define-feature-type 32 "door" 15 #\+ :mimic 32)
(define-feature-type 33 "locked door" 15 #\+ :mimic 32)
(define-feature-type 34 "locked door" 15 #\+ :mimic 32)
(define-feature-type 35 "locked door" 15 #\+ :mimic 32)
(define-feature-type 36 "locked door" 15 #\+ :mimic 32)
(define-feature-type 37 "locked door" 15 #\+ :mimic 32)
(define-feature-type 38 "locked door" 15 #\+ :mimic 32)
(define-feature-type 39 "locked door" 15 #\+ :mimic 32)
(define-feature-type 40 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 41 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 42 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 43 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 44 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 45 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 46 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 47 "jammed door" 15 #\+ :mimic 32)
(define-feature-type 48 "secret door" 1 #\# :mimic 56)
(define-feature-type 49 "pile of rubble" 1 #\: :mimic nil)
(define-feature-type 50 "magma vein" 2 #\% :mimic nil)
(define-feature-type 51 "quartz vein" 1 #\% :mimic nil)
(define-feature-type 52 "magma vein" 2 #\% :mimic 50)
(define-feature-type 53 "quartz vein" 1 #\% :mimic 51)
(define-feature-type 54 "magma vein with treasure" 3 #\* :mimic nil)
(define-feature-type 55 "quartz vein with treasure" 3 #\* :mimic nil)
(define-feature-type 56 "granite wall" 1 #\# :mimic nil)
(define-feature-type 57 "granite wall" 1 #\# :mimic 56)
(define-feature-type 58 "granite wall" 1 #\# :mimic 56)
(define-feature-type 59 "granite wall" 1 #\# :mimic 56)
(define-feature-type 60 "permanent wall" 1 #\# :mimic nil)
(define-feature-type 61 "permanent wall" 1 #\# :mimic 60)
(define-feature-type 62 "permanent wall" 1 #\# :mimic 60)
(define-feature-type 63 "permanent wall" 1 #\# :mimic 60)