.\" posband.6
.\" PosBand 0.9.x man page for *nix systems
.\" Written by Alexander Ulyanov <posband@earthsea.org>
.TH PosBand 6 "6 Jan 2005" "" ""
.SH NAME
.BR PosBand
\- A variant of the popular Angband roguelike game
.SH SYNOPSIS
.BI "posband"
[options] [\-\- suboptions]
.SH DESCRIPTION
.BR PosBand
is a variant of Angband.
Angband is a roguelike game, similar to
Rogue, Moria or NetHack,
based (loosely) on J. R. R. Tolkien writings.
It is a pseudo\-graphical dungeon adventure game
using textual characters to represent
the walls and floors of a dungeon and the inhabitants therein.
The dungeon consists of 100 levels.
You start on the level 0 \- the town.
You can buy food and various equipment there.
As you descend into the dungeon,
the monsters become more and more powerful
(and the treasures increase too!)
To win the game, you must kill Morgoth,
the Lord of Darkness himself,
who lurks on the level 100 (5000 feet below the surface).
You'll need lots of luck and patience for this, though.
.PP
.BR PosBand
adds monster races to Angband.
You can play as a dragon, a demon, an elemental, a Balrog...
There are 52 new races in PosBand.
There is also a special race, Soul, which can possess
the corpse of any killed monster.
.PP
.BR PosBand
also includes some other enhancements, including themed levels,
infinite random artifacts, artifact reforging and
pets.
.PP
.BR PosBand
is available for Windows, Mac OS X and Unix.
There are binary packages for Red Hat and Slackware
Linux available too.
.PP
.BR PosBand
has a built-in help system. Just press '?' to invoke it.
If you haven't played *bands before,
you definitely should read it.
.SH AUTHOR
.BR PosBand
is written by Alexander Ulyanov (posband@earthsea.org). PosBand web
page is http://posband.earthsea.org/.
.PP
.BR PosBand
is itself based on
.BR "NPPAngband",
a very popular variant of Angband.
See http://home.comcast.net/~nppangband/ for more information
on
.BR "NPPAngband".
.PP
There is a newsgroup for discussing Angband
and its variants,
.BR "rec.games.roguelike.angband".
