subdir = ./lib/save/

## makefile.zb

srcfiles += lib/save/makefile.zb

INSTALL += \
		if [ -n "$(GAMEGROUP)" ]; then \
			chown -R root:$(GAMEGROUP) "$(DESTDIR)/lib/save";\
			chmod -R 070 "$(DESTDIR)/lib/save";\
		fi;
