set loc en

# Window title
::msgcat::mcset $loc Pets

# Menu
::msgcat::mcset $loc Command
::msgcat::mcset $loc "Dismiss Selected"
::msgcat::mcset $loc "Dismiss All"
::msgcat::mcset $loc "Stay Close"
::msgcat::mcset $loc "Follow Me"
::msgcat::mcset $loc "Seek And Destroy"
::msgcat::mcset $loc "Give Me Space"
::msgcat::mcset $loc "Stay Away"
::msgcat::mcset $loc "Open Doors"
::msgcat::mcset $loc "Pick Up Items"

# Column titles
::msgcat::mcset $loc Name
::msgcat::mcset $loc Items
::msgcat::mcset $loc Upkeep
::msgcat::mcset $loc Status

# Popup
::msgcat::mcset $loc "Dismiss This Pet"
::msgcat::mcset $loc "Dismiss This Type"

