set loc ja

# Window title
::msgcat::mcset $loc Pets ペット

# Menu
::msgcat::mcset $loc Command 命令
::msgcat::mcset $loc "Dismiss Selected" 選択したペットを放す
::msgcat::mcset $loc "Dismiss All" 全て放す
::msgcat::mcset $loc "Stay Close" 近くにいろ
::msgcat::mcset $loc "Follow Me" ついて来い
::msgcat::mcset $loc "Seek And Destroy" 敵を探して倒せ
::msgcat::mcset $loc "Give Me Space" すこし離れていろ
::msgcat::mcset $loc "Stay Away" 離れろ
::msgcat::mcset $loc "Open Doors" ドアを開けろ
::msgcat::mcset $loc "Pick Up Items" アイテムを拾え

# Column titles
::msgcat::mcset $loc Name 名前
::msgcat::mcset $loc Items アイテム
::msgcat::mcset $loc Upkeep 維持ＭＰ
::msgcat::mcset $loc Status 状態

# Popup
::msgcat::mcset $loc "Dismiss This Pet" これを放す
::msgcat::mcset $loc "Dismiss This Type" この種類を放す

