CLEANFILES=*.o *.so *.fasl *.x86f *.err *.fas *.ufsl *.lib *.sparcf *~

all: 


lisp-clean:
	cd vanilla && $(RM) $(CLEANFILES)
	cd vanilla/config && $(RM) $(CLEANFILES)

clean: lisp-clean
	$(RM) $(CLEANFILES)
