# Mage Sorcery/Trump
#
# TAB - Teleport Away       F1 - Mind Blast          SF1 - Trump Animal
#   [ - Magic Mapping       F2 - Confuse Monster     SF2 - Trump Monster
#   ] - Clairvoyance        F3 - Sleep Monster       SF3 - Trump Spiders
#   ' - Detct Doors/Traps   F4 - Nexus Bolt          SF4 - Trump Reptiles
#   " - Detect Obj./Treas.  F5 - Slow Monster        SF5 - Trump Hounds
#   ; - Detect Monsters     F6 - Mass Sleep          SF6 - Trump Cyberdemon
#   : - Detection           F7 - Banish              SF7 - Trump Undead
#   h - Identify            F8 - Death Dealing       SF8 - Trump Dragon
#   H - Insight             F9 - Stasis              SF9 - Mass Trump
#   J - Dimension Door     F10 - Slow Monsters      SF10 - Trump Demon
#   n - Teleport Level     F11 - Haste Self         SF11 - Trump Anc. Dragon
#   N - Word of Recall     F12 - Globe of Resilien. SF12 - Trump Gr. Undead
#   O - Charm Monster
#   P - Recharging
#   y - Phase Door
#   Y - Teleport Self
#   Z - Light Area

# TAB - Teleport Away
A:m5h
P:\t

# [ - Magic Mapping
A:m2b
C:0:[

# ] - Clairvoyance
A:m4d
C:0:]

# ' - Detect Doors/Traps
A:m1d
C:0:'

# " - Detect Objects/Treasure
A:m1c
C:0:"

# ; - Detect Monsters
A:m1a
C:0:;

# : - Detection
A:m3g
C:0::

# h - Identify
A:m2c
C:0:h

# H - Insight
A:m3h
C:0:H

# J - Dimension Door
A:m5f
C:0:J

# n - Teleport Level
A:m6b
C:0:n

# N - Word of Recall
A:m6e
C:0:N

# O - Charm Monster
A:m3a
C:0:O

# P - Recharging
A:m2a
C:0:P

# y - Phase Door
A:m5a
C:0:y

# Y - Teleport
A:m5e
C:0:Y

# Z - Light Area
A:m1e
C:0:Z

# Combat

# F1 - Mind Blast
A:\e\e\e*tm5b
P:^_x3B\r

# F2 - Confuse Monster
A:m1f
P:^_x3C\r

# F3 - Sleep Monster
A:m1h
P:^_x3D\r

# F4 - Nexus Bolt
A:\e\e\e*tm6b
P:^_x3E\r

# F5 - Slow Monster
A:m2e
P:^_x3F\r

# F6 - Mass Sleep
A:m2f
P:^_x40\r

# F7 - Banish
A:m7e
P:^_x41\r

# F8 - Death Dealing
A:m7g
P:^_x42\r

# F9 - Stasis
A:m4a
P:^_x43\r

# F10 - Slow Monsters
A:m4b
P:^_x44\r

# F11 - Haste Self
A:m2h
P:^_x85\r

# F12 - Globe of Resilience
A:m4h
P:^_x86\r

# Trump Summoning

# SHIFT-F1 - Trump Animal
A:m6f
P:^_Sx54\r

# SHIFT-F2 - Trump Monster
A:m6g
P:^_Sx55\r

# SHIFT-F3 - Trump Spiders
A:m7b
P:^_Sx56\r

# SHIFT-F4 - Trump Reptiles
A:m7c
P:^_Sx57\r

# SHIFT-F5 - Trump Hounds
A:m7d
P:^_Sx58\r

# SHIFT-F6 - Trump Cyberdemon
A:m7h
P:^_Sx59\r

# SHIFT-F7 - Trump Undead
A:m8c
P:^_Sx5A\r

# SHIFT-F8 - Trump Dragon
A:m8d
P:^_Sx5B\r

# SHIFT-F9 - Mass Trump
A:m8e
P:^_Sx5C\r

# SHIFT-F10 - Trump Demon
A:m8f
P:^_Sx5D\r

# SHIFT-F11 - Trump Ancient Dragon
A:m8g
P:^_Sx87\r

# SHIFT-F12 - Trump Greater Undead
A:m8h
P:^_Sx88\r
