# Rogue Trump Spells
#
# TAB - Teleport Away       F1 - Trump Animals
#   [ - Mind Blast          F2 - Phantasmal Servant
#   ] - Death Dealing       F3 - Trump Monster
#   ' - Trump Branding      F4 - Conjure Elemental
#   " - Living Trump        F5 - Joker Card
#   ; - Shuffle             F6 - Trump Spiders
#   : - Banish              F7 - Trump Reptiles
#   h - Teleport Level      F8 - Trump Hounds
#   H - Word of Recall      F9 - Trump Undead
#   J - Trump Lore         F10 - Trump Dragon
#   n - Minor Divination   F11 - Trump Demon
#   N - Trump Divination
#   O - Trump Spying
#   P - Trump Reach
#   y - Phase Door
#   Y - Teleport
#   Z - Dimension Door

# TAB - Teleport Away
A:m1h
P:\t

# [ - Mind Blast
A:\e\e\e*tm1b
C:0:[

# ] - Death Dealing
A:m3g
C:0:]

# ' - Trump Branding
A:m2f
C:0:'

# " - Living Trump
A:m3f
C:0:"

# ; - Shuffle
A:m1c
C:0:;

# : - Banish
A:m3e
C:0::

# h - Teleport Level
A:m2f
C:0:h

# H - Word of Recall
A:m2g
C:0:H

# J - Trump Lore
A:m4b
C:0:J

# n - Minor Divination
A:m1d
C:0:n

# N - Trump Divination
A:m4b
C:0:N

# O - Trump Spying
A:m1g
C:0:O

# P - Trump Reach
A:m2a
C:0:P

# y - Phase Door
A:m1a
C:0:y

# Y - Teleport
A:m1e
C:0:Y

# Z - Dimension Door
A:m1f
C:0:Z

# Trumps

# F1 - Trump Animals
A:m2b
P:^_x3B\r

# F2 - Phantasmal Servant
A:m2c
P:^_x3C\r

# F3 - Trump Monster
A:m2d
P:^_x3D\r

# F4 - Conjure Elemental
A:m2e
P:^_x3E\r

# F5 - Joker Card
A:m3a
P:^_x3F\r

# F6 - Trump Spiders
A:m3b
P:^_x40\r

# F7 - Trump Reptiles
A:m3c
P:^_x41\r

# F8 - Trump Hounds
A:m3d
P:^_x42\r

# F9 - Trump undead
A:m4c
P:^_x43\r

# F10 - Trump Dragon
A:m4d
P:^_x44\r

# F11 - Trump Demon
A:m4f
P:^_x85\r

# F12 - 
A:
P:^_x86\r

# SHIFT-F1 - 
A:
P:^_Sx54\r

# SHIFT-F2 - 
A:
P:^_Sx55\r

# SHIFT-F3 - 
A:
P:^_Sx56\r
