set loc ja

# Window title
::msgcat::mcset $loc Macros マクロ

# Window
::msgcat::mcset $loc Trigger: トリガー:
::msgcat::mcset $loc Action: 動作:

# Macro menu
::msgcat::mcset $loc Macro マクロ
::msgcat::mcset $loc "New Empty Macro" 新規マクロ
::msgcat::mcset $loc "Dump Macros" 設定を保存
::msgcat::mcset $loc "Load Pref File" 設定をロード

# Toolbar
::msgcat::mcset $loc Open 開く
::msgcat::mcset $loc Save 保存

# Statusbar
::msgcat::mcset $loc "%d macros" "%d 個のマクロ"

