/*
 * File: list-blow-effects.h
 * Purpose: Monster race blow effects
 */

/*  symbol     descr */
RBE(NONE,      "")
RBE(HURT,      "attack")
RBE(POISON,    "poison")
RBE(UN_BONUS,  "disenchant")
RBE(UN_POWER,  "drain charges")
RBE(EAT_GOLD,  "steal gold")
RBE(EAT_ITEM,  "steal items")
RBE(EAT_FOOD,  "eat your food")
RBE(EAT_LIGHT, "absorb light")
RBE(ACID,      "shoot acid")
RBE(ELEC,      "electrify")
RBE(FIRE,      "burn")
RBE(COLD,      "freeze")
RBE(BLIND,     "blind")
RBE(CONFUSE,   "confuse")
RBE(TERRIFY,   "terrify")
RBE(PARALYZE,  "paralyze")
RBE(LOSE_STR,  "reduce strength")
RBE(LOSE_INT,  "reduce intelligence")
RBE(LOSE_WIS,  "reduce wisdom")
RBE(LOSE_DEX,  "reduce dexterity")
RBE(LOSE_CON,  "reduce constitution")
RBE(LOSE_CHR,  "reduce charisma")
RBE(LOSE_ALL,  "reduce all stats")
RBE(SHATTER,   "shatter")
RBE(EXP_10,    "lower experience")
RBE(EXP_20,    "lower experience")
RBE(EXP_40,    "lower experience")
RBE(EXP_80,    "lower experience")
RBE(HALLU,     "cause hallucinations")
RBE(FORGET,    "cause amnesia")
RBE(DISEASE,   "cause disease")
RBE(TIME,      "produce time effects")
RBE(DISARM,    "disarm")
RBE(FAMINE,    "cause hunger")
