set loc en

# Window title
::msgcat::mcset $loc Font

# Font menu
::msgcat::mcset $loc Font

# Window
::msgcat::mcset $loc Font:
::msgcat::mcset $loc Size:
::msgcat::mcset $loc Style:
::msgcat::mcset $loc Bold
::msgcat::mcset $loc Italic
::msgcat::mcset $loc *sample \
	"The quick brown fox jumped over the lazy dog."

::msgcat::mcset $loc Item
::msgcat::mcset $loc Font
::msgcat::mcset $loc Size
::msgcat::mcset $loc Style

# Window (list)
::msgcat::mcset $loc ascii "Ascii Icons"
::msgcat::mcset $loc autobar "Autobar Menu"
::msgcat::mcset $loc choice "Choice Window"
::msgcat::mcset $loc equippy "Equippy Chars"
::msgcat::mcset $loc fixed Fixed
::msgcat::mcset $loc inventory "Equipment & Inventory"
::msgcat::mcset $loc knowledge "Knowledge & Other"
::msgcat::mcset $loc macros Macros
::msgcat::mcset $loc magic "Mindcraft, Spells & Powers"
::msgcat::mcset $loc message Message
::msgcat::mcset $loc messages "Message History"
::msgcat::mcset $loc misc "Misc & Progress"
::msgcat::mcset $loc miscPopup "Misc Window Menu"
::msgcat::mcset $loc monster "Monster Health Bar"
::msgcat::mcset $loc options Options
::msgcat::mcset $loc recall Recall
::msgcat::mcset $loc status Status
::msgcat::mcset $loc statusBar Statusbar
::msgcat::mcset $loc store Store
::msgcat::mcset $loc system System

# Statusbar
::msgcat::mcset $loc "1 item selected"
::msgcat::mcset $loc "%d items selected"

