set loc ja

# Window title
::msgcat::mcset $loc Font フォント

# Font menu
::msgcat::mcset $loc Font フォント

# Window
::msgcat::mcset $loc Font: フォント:
::msgcat::mcset $loc Size: サイズ:
::msgcat::mcset $loc Style: 字体:
::msgcat::mcset $loc Bold 太字:
::msgcat::mcset $loc Italic 斜体:
::msgcat::mcset $loc *sample \
	"This is a pen. 俺は荒井注だ！クビチョンパ"

::msgcat::mcset $loc Item
::msgcat::mcset $loc Font
::msgcat::mcset $loc Size
::msgcat::mcset $loc Style

# Window (list)
::msgcat::mcset $loc ascii "Ascii Icons"
::msgcat::mcset $loc autobar "Autobar Menu"
::msgcat::mcset $loc choice "選択ウィンドウ"
::msgcat::mcset $loc equippy "Equippy Chars"
::msgcat::mcset $loc fixed Fixed
::msgcat::mcset $loc inventory "装備と持ち物"
::msgcat::mcset $loc knowledge "知識、その他"
::msgcat::mcset $loc macros マクロ
::msgcat::mcset $loc magic "超能力、呪文、特殊能力"
::msgcat::mcset $loc message メッセージ
::msgcat::mcset $loc messages "メッセージ履歴"
::msgcat::mcset $loc misc "ステータスとＨＰ，ＭＰ"
::msgcat::mcset $loc miscPopup "アイテムポップアップ"
::msgcat::mcset $loc monster "モンスターＨＰ"
::msgcat::mcset $loc options オプション
::msgcat::mcset $loc recall 情報
::msgcat::mcset $loc status 特殊状態表示
::msgcat::mcset $loc statusBar ステータスバー
::msgcat::mcset $loc store 店
::msgcat::mcset $loc system System

# Statusbar
::msgcat::mcset $loc "1 item selected" 1個選択
::msgcat::mcset $loc "%d items selected" "%d個選択"

