subdir = ./lib/script/tk/

## makefile.zb

srcfiles += lib/script/tk/makefile.zb
files += lib/script/tk/*.tcl lib/script/tk/tips.txt

dirs := config image library

dirlist := $(dirlist) $(addprefix $(subdir),$(dirs))
include $(scandir)
