set loc en

# Window title
::msgcat::mcset $loc title "Choice - %s"
::msgcat::mcset $loc title-equipment Equipment
::msgcat::mcset $loc title-inventory Inventory
::msgcat::mcset $loc title-floor Floor
::msgcat::mcset $loc title-spell Spell
::msgcat::mcset $loc title-prayer Prayer
::msgcat::mcset $loc title-ele_attack "Elemental Brand"
::msgcat::mcset $loc title-pet "Pet Command"
::msgcat::mcset $loc title-mindcraft Mindcraft
::msgcat::mcset $loc title-power Power

# Popup
::msgcat::mcset $loc "Show Equipment"
::msgcat::mcset $loc "Show Inventory"
::msgcat::mcset $loc "Auto Expand"
::msgcat::mcset $loc "Show Icon"

