subdir = ./lib/script/

## makefile.zb

srcfiles += lib/script/makefile.zb
files += lib/script/init.lua lib/script/object.lua lib/script/spell.lua \
		 lib/script/test.lua lib/script/field.lua

dirs := tk

dirlist := $(dirlist) $(addprefix $(subdir),$(dirs))
include $(scandir)
