set loc en

# Window title
::msgcat::mcset $loc Keymap

# Keymap menu
::msgcat::mcset $loc Keymap
::msgcat::mcset $loc "Rogue-like Keyset"
::msgcat::mcset $loc "Dump Keymaps"
::msgcat::mcset $loc "Load Pref File"

# Toolbar
::msgcat::mcset $loc Open
::msgcat::mcset $loc Save

# Window
::msgcat::mcset $loc Action:
::msgcat::mcset $loc Normal
::msgcat::mcset $loc Shift
::msgcat::mcset $loc Control

