set loc ja

# Window title
::msgcat::mcset $loc Keymap キーマップ

# Keymap menu
::msgcat::mcset $loc Keymap キーマップ
::msgcat::mcset $loc "Rogue-like Keyset" ローグ風キー配置
::msgcat::mcset $loc "Dump Keymaps" キーマップを保存
::msgcat::mcset $loc "Load Pref File" キーマップをロード

# Toolbar
::msgcat::mcset $loc Open 開く
::msgcat::mcset $loc Save 保存

# Window
::msgcat::mcset $loc Action: 動作:
::msgcat::mcset $loc Normal 通常
::msgcat::mcset $loc Shift シフト
::msgcat::mcset $loc Control コントロール

