set loc en

# Window title
::msgcat::mcset $loc Color

# Color menu
::msgcat::mcset $loc Color

# Window
::msgcat::mcset $loc Opacity

# Window (List)
::msgcat::mcset $loc "List Background"
::msgcat::mcset $loc "List Highlight (Active)"
::msgcat::mcset $loc "List Highlight (Inactive)"
::msgcat::mcset $loc "Inventory Colors"

# Window (Monster Bar)
::msgcat::mcset $loc "Monster Name"

# Window (Status)
::msgcat::mcset $loc Good
::msgcat::mcset $loc Info
::msgcat::mcset $loc Bad

# Page titles
::msgcat::mcset $loc List
::msgcat::mcset $loc "Micro Map"
::msgcat::mcset $loc "Monster Bar"
::msgcat::mcset $loc Status
::msgcat::mcset $loc Target
::msgcat::mcset $loc Icons

