set loc ja

# Window title
::msgcat::mcset $loc Color カラー

# Color menu
::msgcat::mcset $loc Color カラー

# Window
::msgcat::mcset $loc Opacity 不透明度

# Window (List)
::msgcat::mcset $loc "List Background" リスト背景
::msgcat::mcset $loc "List Highlight (Active)" リスト強調(選択可)
::msgcat::mcset $loc "List Highlight (Inactive)" リスト強調(選択不可)
::msgcat::mcset $loc "Inventory Colors" 持ち物の文字色

# Window (Monster Bar)
::msgcat::mcset $loc "Monster Name" モンスター名

# Window (Status)
::msgcat::mcset $loc Good 良い状態
::msgcat::mcset $loc Info その他の状態
::msgcat::mcset $loc Bad 悪い状態

# Page titles
::msgcat::mcset $loc List リスト
::msgcat::mcset $loc "Micro Map" レーダー
::msgcat::mcset $loc "Monster Bar" モンスターＨＰ
::msgcat::mcset $loc Status 特殊状態
::msgcat::mcset $loc Target ターゲット
::msgcat::mcset $loc Icons

