set loc en

# Window title
::msgcat::mcset $loc "%s Hall of Fame"

# Score menu
::msgcat::mcset $loc Score
::msgcat::mcset $loc "Dump Scores"
::msgcat::mcset $loc "Show Record"

# View menu
::msgcat::mcset $loc View
::msgcat::mcset $loc Columns
::msgcat::mcset $loc Sort

# Column titles & menu labels
::msgcat::mcset $loc name Name
::msgcat::mcset $loc race Race
::msgcat::mcset $loc class Class
::msgcat::mcset $loc clevel Level
::msgcat::mcset $loc killedby "Killed By"
::msgcat::mcset $loc dlevel Depth
::msgcat::mcset $loc score Score
::msgcat::mcset $loc turns Turns
::msgcat::mcset $loc gold Gold
::msgcat::mcset $loc winner Winner
::msgcat::mcset $loc record Record
::msgcat::mcset $loc day Date

::msgcat::mcset $loc Town
::msgcat::mcset $loc Arena

# Statusbar
::msgcat::mcset $loc "Record %s."
::msgcat::mcset $loc "No record available."

# Search dialog
::msgcat::mcset $loc find-prompt Text

