set loc ja

# Window title
::msgcat::mcset $loc "%s Hall of Fame" "%s 勇者の殿堂"

# Score menu
::msgcat::mcset $loc Score スコア
::msgcat::mcset $loc "Dump Scores" スコアを保存
::msgcat::mcset $loc "Show Record" 記録を見る

# View menu
::msgcat::mcset $loc View
::msgcat::mcset $loc Columns
::msgcat::mcset $loc Sort ソート

# Column titles & menu labels
::msgcat::mcset $loc name 名前
::msgcat::mcset $loc race 種族
::msgcat::mcset $loc class クラス
::msgcat::mcset $loc clevel Level
::msgcat::mcset $loc killedby "Killed By"
::msgcat::mcset $loc dlevel Depth
::msgcat::mcset $loc score スコア
::msgcat::mcset $loc turns Turns
::msgcat::mcset $loc gold Gold
::msgcat::mcset $loc winner 勝利者
::msgcat::mcset $loc record Record
::msgcat::mcset $loc day Date

::msgcat::mcset $loc Town
::msgcat::mcset $loc Arena

# Statusbar
::msgcat::mcset $loc "Record %s." "%s を記録"
::msgcat::mcset $loc "No record available." 記録無し

# Search dialog
::msgcat::mcset $loc find-prompt Text

