MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = \
	a_info.txt \
	b_info.txt \
	e_info.txt \
	f_info.txt \
	k_info.txt \
	m_info.txt \
	misc.txt \
	monk_attack.txt \
	q_barrow_downs.txt \
	q_chaos.txt \
	q_cloning_pits.txt \
	q_crypt.txt \
	q_dark_elves.txt \
	q_doom1.txt \
	q_doom2.txt \
	q_eric.txt \
	q_haunted_house.txt \
	q_info.txt \
	q_killing_fields.txt \
	q_logrus_master.txt \
	q_mimics_treasure.txt \
	q_montsalvat.txt \
	q_nature.txt \
	q_old_castle.txt \
	q_old_man_willow.txt \
	q_orcs.txt \
	q_removed.txt \
	q_sewer.txt \
	q_sorcerer.txt \
	q_sorcery.txt \
	q_spawning_pits.txt \
	q_tengu_death_swords.txt \
	q_thieves.txt \
	q_vapor2.txt \
	q_vapor.txt \
	q_vault.txt \
	q_wargs.txt \
	r_info.txt \
	rooms.txt \
	s_info.txt \
	t_angwil.txt \
	t_basic.txt \
	t_beorn.txt \
	t_edoras.txt \
	t_laketown.txt \
	t_minas_tirith.txt \
	t_morannon.txt \
	t_osgiliath.txt \
	t_pref.txt \
	t_rivendell.txt \
	t_telmora.txt \
	t_zul.txt \
	vaults.txt \
	v_info.txt \
	w_angband.txt \
	world.txt \
	w_saruman.txt \
	w_sauron.txt \
	w_smaug.txt

PACKAGE = edit
