MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = artifact.txt ego_item.txt flavor.txt limits.txt monster.txt \
 names.txt object.txt p_class.txt p_hist.txt player_ghost.txt \
 m_limits.txt m_object.txt m_artifact.txt m_ego_item.txt m_monster.txt\
 m_p_race.txt m_p_class.txt m_p_hist.txt m_quest.txt\
 p_race.txt shop_own.txt quest.txt terrain.txt vault.txt 
PACKAGE = edit
