subdir = ./lib/edit/

## makefile.zb

srcfiles += lib/edit/makefile.zb

files += \
  lib/edit/a_info.txt lib/edit/e_info.txt lib/edit/f_info.txt\
  lib/edit/k_info.txt lib/edit/misc.txt lib/edit/r_info.txt\
  lib/edit/v_info.txt lib/edit/t_info.txt lib/edit/w_info.txt
