MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = a_info.txt    q0000003.txt  q00000ms.txt  qdarkelf.txt  t0000002.txt \
b_info.txt    q0000004.txt  q000chao.txt  qhaunted.txt  t0000003.txt \
d_info.txt    q0000005.txt  q000dekn.txt  q_info.txt    t0000004.txt \
e_info.txt    q0000006.txt  q000eric.txt  q_oberon.txt  t0000005.txt \
f_info.txt    q0000007.txt  q000lyeh.txt  q_pref.txt    t0000006.txt \
k_info.txt    q0000019.txt  q000natu.txt  q_random.txt  t_basic.txt \
q0000020.txt  q000sorc.txt  q_serpen.txt  t_info.txt \
q0000021.txt  q0clone0.txt  qsmaug.txt    t_lite.txt \
m_info.txt    q0000022.txt  q0fields.txt  q_warg.txt    t_pref.txt \
misc.txt      q0000023.txt  q0thief1.txt  r_info.txt    v_info.txt \
q0000001.txt  q0000027.txt  q0thief2.txt  s_info.txt    w_info.txt \
q0000002.txt  q0000028.txt  q0willow.txt  t0000001.txt

PACKAGE = edit
