set loc ja

# Window title
::msgcat::mcset $loc Assign アサイン

# Assign To menu
::msgcat::mcset $loc "Assign To" アサイン先

# Assign What menu
::msgcat::mcset $loc "Assign What" アサイン種類
::msgcat::mcset $loc Alternate 変える
::msgcat::mcset $loc Icon アイコン
::msgcat::mcset $loc Sound サウンド
::msgcat::mcset $loc Sprite アニメーション

# Sound menu
::msgcat::mcset $loc Sound サウンド
::msgcat::mcset $loc Configuration
::msgcat::mcset $loc Directory

# Sound lists
::msgcat::mcset $loc "Sound Files"
::msgcat::mcset $loc "Assigned Sounds"
::msgcat::mcset $loc sound-none None

# Character menu
::msgcat::mcset $loc "Auto Assign..." 自動アサイン

# Feature menu
::msgcat::mcset $loc Background... 背景
::msgcat::mcset $loc Memorize 記憶
::msgcat::mcset $loc "Town Light" 街の明かり

# Feature -> Lighting menu
::msgcat::mcset $loc Lighting 照明
::msgcat::mcset $loc Icon アイコン
::msgcat::mcset $loc None なし
::msgcat::mcset $loc Tint 色

# Page titles
::msgcat::mcset $loc character 自分
::msgcat::mcset $loc effect 効果
::msgcat::mcset $loc feature 地形
::msgcat::mcset $loc monster モンスター
::msgcat::mcset $loc object アイテム

# Effects
::msgcat::mcset $loc Ball
::msgcat::mcset $loc Bolt
::msgcat::mcset $loc Ammunition

# Statusbar
::msgcat::mcset $loc Feature 地形
::msgcat::mcset $loc Monster モンスター
::msgcat::mcset $loc Object アイテム
::msgcat::mcset $loc "Not assigned." なし
::msgcat::mcset $loc browser-group "Icon type \"%s\"."

# Search dialog
::msgcat::mcset $loc find-prompt 名前

