CLEANFILES=*.o *.so *.fasl *.x86f *.err *.fas *.ufsl *.lib 

all: 
#	cd zlib && ./configure
#	cd zlib && $(MAKE) all
#	-cd libpng && ln -s scripts/makefile.linux Makefile
#	cd libpng && $(MAKE) libpng.a


lisp-clean:
	cd compat && $(RM) $(CLEANFILES)
	$(RM) $(CLEANFILES)

clean: lisp-clean

