-- Autogenerated file, do NOT edit

-------------------- Obj gen ----------------------
__scribe_apply_magic = {}

function __scribe_add_apply_magic(tval, sval, fct)
        if not __scribe_apply_magic[tval] then __scribe_apply_magic[tval] = {} end
        __scribe_apply_magic[tval][sval] = fct
end

function __scribe_apply_magic_hook(obj, level, power)
        if __scribe_apply_magic[obj.tval] and __scribe_apply_magic[obj.tval][obj.sval] then
                __scribe_apply_magic[obj.tval][obj.sval](obj, level, power)
                return TRUE
        end
end

add_hook_script(HOOK_APPLY_MAGIC, "__scribe_apply_magic_hook", "__scribe_apply_magic_hook")


-------------------- Obj quaff ----------------------
__scribe_quaff = {}

function __scribe_add_quaff(tval, sval, fct)
        if not __scribe_quaff[tval] then __scribe_quaff[tval] = {} end
        __scribe_quaff[tval][sval] = fct
end

function __scribe_quaff_hook(obj)
        if __scribe_quaff[obj.tval] and __scribe_quaff[obj.tval][obj.sval] then
                return TRUE, __scribe_quaff[obj.tval][obj.sval](obj)
        end
end

add_hook_script(HOOK_QUAFF, "__scribe_quaff_hook", "__scribe_quaff_hook")

-------------------- Obj eat ----------------------
__scribe_eat = {}

function __scribe_add_eat(tval, sval, fct)
        if not __scribe_eat[tval] then __scribe_eat[tval] = {} end
        __scribe_eat[tval][sval] = fct
end

function __scribe_eat_hook(obj)
        if __scribe_eat[obj.tval] and __scribe_eat[obj.tval][obj.sval] then
                return TRUE, __scribe_eat[obj.tval][obj.sval](obj)
        end
end

add_hook_script(HOOK_EAT, "__scribe_eat_hook", "__scribe_eat_hook")

-------------------- Obj read ----------------------
__scribe_read = {}

function __scribe_add_read(tval, sval, fct)
        if not __scribe_read[tval] then __scribe_read[tval] = {} end
        __scribe_read[tval][sval] = fct
end

function __scribe_read_hook(obj)
        if __scribe_read[obj.tval] and __scribe_read[obj.tval][obj.sval] then
                return TRUE, __scribe_read[obj.tval][obj.sval](obj)
        end
end

add_hook_script(HOOK_READ, "__scribe_read_hook", "__scribe_read_hook")

-- here comes the various obj hooks
