set loc en

# Window title
::msgcat::mcset $loc home-title1 "Your Home"
::msgcat::mcset $loc home-title2 "Your Home"
::msgcat::mcset $loc store-title1 {The %1$s owned by %2$s}
::msgcat::mcset $loc store-title2 "The %s"

# Window
::msgcat::mcset $loc Quantity:
::msgcat::mcset $loc "Total Cost:"
::msgcat::mcset $loc "Gold Remaining:"
::msgcat::mcset $loc Purse:
::msgcat::mcset $loc Inventory

# Store menu
::msgcat::mcset $loc Home
::msgcat::mcset $loc Store
::msgcat::mcset $loc Take
::msgcat::mcset $loc Buy
::msgcat::mcset $loc Drop
::msgcat::mcset $loc Sell
::msgcat::mcset $loc Inspect
::msgcat::mcset $loc Auto-Haggle
::msgcat::mcset $loc Destroy
::msgcat::mcset $loc Leave

# Popup
::msgcat::mcset $loc "Buy An Item"
::msgcat::mcset $loc "Buy This Item"
::msgcat::mcset $loc "Buy One"
::msgcat::mcset $loc "Buy Five"
::msgcat::mcset $loc "Buy Some"
::msgcat::mcset $loc "Buy All"
::msgcat::mcset $loc "Drop An Item"
::msgcat::mcset $loc "Drop This Item"
::msgcat::mcset $loc "Drop One"
::msgcat::mcset $loc "Drop Five"
::msgcat::mcset $loc "Drop Some"
::msgcat::mcset $loc "Drop All"
::msgcat::mcset $loc "Sell An Item"
::msgcat::mcset $loc "Sell This Item"
::msgcat::mcset $loc "Sell One"
::msgcat::mcset $loc "Sell Five"
::msgcat::mcset $loc "Sell Some"
::msgcat::mcset $loc "Sell All"
::msgcat::mcset $loc "Take An Item"
::msgcat::mcset $loc "Take This Item"
::msgcat::mcset $loc "Take One"
::msgcat::mcset $loc "Take Five"
::msgcat::mcset $loc "Take Some"
::msgcat::mcset $loc "Take All"
::msgcat::mcset $loc "Select This Item"
::msgcat::mcset $loc Inspect
::msgcat::mcset $loc *Destroy*

# Statusbar
::msgcat::mcset $loc status-number-store "Number of store items"
::msgcat::mcset $loc status-number-inven "Number of inventory items"
::msgcat::mcset $loc status-weight-inven "Weight of inventory items"
::msgcat::mcset $loc "%d item"
::msgcat::mcset $loc "%d items"

# Options
::msgcat::mcset $loc "Show Flavors"
::msgcat::mcset $loc "Show Icons"
::msgcat::mcset $loc "Show Weights"
::msgcat::mcset $loc "Use Metric"
::msgcat::mcset $loc "Graphics Mode"
::msgcat::mcset $loc "List Mode"

