set loc ja

# Window title
::msgcat::mcset $loc home-title1 我が家
::msgcat::mcset $loc home-title2 我が家
::msgcat::mcset $loc store-title1 {%1$s 店主:%2$s}
::msgcat::mcset $loc store-title2 "%s"

# Window
::msgcat::mcset $loc Quantity: 個数:
::msgcat::mcset $loc "Total Cost:" 合計金額:
::msgcat::mcset $loc "Gold Remaining:" 所持金:
::msgcat::mcset $loc Purse: 買取最高額
::msgcat::mcset $loc Inventory 持ち物

# Store menu
::msgcat::mcset $loc Home 我が家
::msgcat::mcset $loc Store 店
::msgcat::mcset $loc Take 取る
::msgcat::mcset $loc Buy 買う
::msgcat::mcset $loc Drop 置く
::msgcat::mcset $loc Sell 売る
::msgcat::mcset $loc Inspect 調べる
::msgcat::mcset $loc Auto-Haggle 自動値切り
::msgcat::mcset $loc Destroy 壊す
::msgcat::mcset $loc Leave 立ち去る

# Popup
::msgcat::mcset $loc "Buy An Item" 一個買う
::msgcat::mcset $loc "Buy This Item" これを買う
::msgcat::mcset $loc "Buy One" 一個買う
::msgcat::mcset $loc "Buy Five" 五個買う
::msgcat::mcset $loc "Buy Some"
::msgcat::mcset $loc "Buy All" 全部買う
::msgcat::mcset $loc "Drop An Item" 一個捨てる
::msgcat::mcset $loc "Drop This Item"
::msgcat::mcset $loc "Drop One" 一個置く
::msgcat::mcset $loc "Drop Five" 五個置く
::msgcat::mcset $loc "Drop Some"
::msgcat::mcset $loc "Drop All" 全部置く
::msgcat::mcset $loc "Sell An Item" 一個売る
::msgcat::mcset $loc "Sell This Item" これを売る
::msgcat::mcset $loc "Sell One" 一個売る
::msgcat::mcset $loc "Sell Five" 五個売る
::msgcat::mcset $loc "Sell Some"
::msgcat::mcset $loc "Sell All" 全部売る
::msgcat::mcset $loc "Take An Item" 一個取る
::msgcat::mcset $loc "Take This Item" これを取る
::msgcat::mcset $loc "Take One" 一個取る
::msgcat::mcset $loc "Take Five" 五個取る
::msgcat::mcset $loc "Take Some"
::msgcat::mcset $loc "Take All" 全部取る
::msgcat::mcset $loc "Select This Item" これを選択
::msgcat::mcset $loc Inspect 調べる
::msgcat::mcset $loc *Destroy* *壊す*

# Statusbar
::msgcat::mcset $loc status-number-store "Number of store items"
::msgcat::mcset $loc status-number-inven "Number of inventory items"
::msgcat::mcset $loc status-weight-inven "Weight of inventory items"
::msgcat::mcset $loc "%d item" "%d 個のアイテム"
::msgcat::mcset $loc "%d items" "%d 個のアイテム"

# Options
::msgcat::mcset $loc "Show Flavors" 特徴も表示
::msgcat::mcset $loc "Show Icons" アイコンを表示
::msgcat::mcset $loc "Show Weights" 重量を表示
::msgcat::mcset $loc "Use Metric" メートル法で表示
::msgcat::mcset $loc "Graphics Mode" グラフィックで表示
::msgcat::mcset $loc "List Mode" リストで表示

