set loc ja

# Window title
::msgcat::mcset $loc "Message History" メッセージ履歴

# Menu
::msgcat::mcset $loc Message メッセージ
::msgcat::mcset $loc "Dump Messages" メッセージを保存
::msgcat::mcset $loc "Combine Messages" メッセージを結合
::msgcat::mcset $loc "Max Messages..." 最大メッセージ数

# Search dialog
::msgcat::mcset $loc find-prompt テキスト

# Dialog
::msgcat::mcset $loc max-title 表示メッセージ数
::msgcat::mcset $loc max-prompt  "最大 (1-2048)"

::msgcat::mcset $loc max-message \
"表示するメッセージの行数を入力してください。その行数だけ\
メッセージが保存されますが、行数が多いほど表示は遅くなります。"

# Messages Window: title
::msgcat::mcset $loc Messages メッセージ

