set loc en

# Window title
::msgcat::mcset $loc Options
::msgcat::mcset $loc "Options (%s)"

# Page titles
::msgcat::mcset $loc Cheating
::msgcat::mcset $loc Command
::msgcat::mcset $loc Disturbance
::msgcat::mcset $loc Dungeon
::msgcat::mcset $loc Efficiency
::msgcat::mcset $loc Interface
::msgcat::mcset $loc Misc
::msgcat::mcset $loc Monster
::msgcat::mcset $loc Object
::msgcat::mcset $loc Prompt
::msgcat::mcset $loc Other

# Options menu
::msgcat::mcset $loc Options
::msgcat::mcset $loc "Save As Default"
::msgcat::mcset $loc "Load Default Settings"
# ::msgcat::mcset $loc "Show Unused Options"

# Read/WriteSettings
::msgcat::mcset $loc title-write "Write Settings"
::msgcat::mcset $loc msg-write "Really make these the default settings?"
::msgcat::mcset $loc title-read "Read Settings"
::msgcat::mcset $loc msg-read "Really read the saved settings?"

# Search dialog
::msgcat::mcset $loc find-prompt Keyword

# Birth Options: Pages
::msgcat::mcset $loc Birth
::msgcat::mcset $loc Ironman
::msgcat::mcset $loc Quests
::msgcat::mcset $loc Wilderness

# Birth Options: Quests
::msgcat::mcset $loc quest-prompt \
	"Enter the number of random quests you\
	would like your character to complete in addition to the\
	two required quests (Oberon and the Serpent of Chaos). If\
	you do not want any additional quests, enter 0."
::msgcat::mcset $loc "(Max of %d)"

# Birth Options: Wilderness
::msgcat::mcset $loc wild-prompt \
	"Choose the complexity of the town level."

