set loc ja

# Window title
::msgcat::mcset $loc Options オプション
::msgcat::mcset $loc "Options (%s)" "オプション(%s)"

# Page titles
# Page titles
::msgcat::mcset $loc Cheating インチキ
::msgcat::mcset $loc Command コマンド
::msgcat::mcset $loc Disturbance 行動中止
::msgcat::mcset $loc Dungeon ダンジョン
::msgcat::mcset $loc Efficiency 効率化
::msgcat::mcset $loc Interface インターフェース
::msgcat::mcset $loc Misc 様々な設定
::msgcat::mcset $loc Monster モンスター
::msgcat::mcset $loc Object アイテム
::msgcat::mcset $loc Prompt プロンプト
::msgcat::mcset $loc Other その他
::msgcat::mcset $loc Japanese 日本語版特別
#::msgcat::mcset $loc OAngband OAngband
#::msgcat::mcset $loc ZAngband ZAngband

# Options menu
::msgcat::mcset $loc Options オプション
::msgcat::mcset $loc "Save As Default" デフォルトとして保存
::msgcat::mcset $loc "Load Default Settings" デフォルト設定
::msgcat::mcset $loc "Show Unused Options" 未使用オプション

# Read/WriteSettings
::msgcat::mcset $loc title-write "Write Settings"
::msgcat::mcset $loc msg-write "Really make these the default settings?"
::msgcat::mcset $loc title-read "Read Settings"
::msgcat::mcset $loc msg-read "Really read the saved settings?"

# Search dialog
::msgcat::mcset $loc find-prompt Keyword

# Birth Options: Pages
::msgcat::mcset $loc Birth 初期
::msgcat::mcset $loc Ironman 鉄人
::msgcat::mcset $loc Quests クエスト
::msgcat::mcset $loc Wilderness 荒野

# Birth Options: Quests
::msgcat::mcset $loc quest-prompt \
	"必須のクエスト(オベロン及び混沌のサーペント)に加えて、\
	追加のクエストの数を設定することが出来ます。\
	追加クエストを行ないたくない場合は '0'を入力して下さい。"

::msgcat::mcset $loc "(Max of %d)" "(最大 %d)"

# Birth Options: Wilderness
::msgcat::mcset $loc wild-prompt \
	"街の規模を選んでください。"

