set loc en

# Window title
::msgcat::mcset $loc Powers

# Table labels
::msgcat::mcset $loc Name
::msgcat::mcset $loc Level
::msgcat::mcset $loc Cost
::msgcat::mcset $loc Fail
::msgcat::mcset $loc Stat

# Stat names
::msgcat::mcset $loc Strength
::msgcat::mcset $loc Intelligence
::msgcat::mcset $loc Wisdom
::msgcat::mcset $loc Constitution
::msgcat::mcset $loc Dexterity
::msgcat::mcset $loc Charisma

# Popup
::msgcat::mcset $loc "Select This Power"

