set loc ja

# Window title
::msgcat::mcset $loc Powers 特殊能力

# Table labels
::msgcat::mcset $loc Name 名前
::msgcat::mcset $loc Level レベル
::msgcat::mcset $loc Cost ＭＰ
::msgcat::mcset $loc Fail 失敗率
::msgcat::mcset $loc Stat 必要特性

# Stat names
::msgcat::mcset $loc Strength 腕力
::msgcat::mcset $loc Intelligence 知力
::msgcat::mcset $loc Wisdom 賢さ
::msgcat::mcset $loc Constitution 耐久力
::msgcat::mcset $loc Dexterity 器用さ
::msgcat::mcset $loc Charisma 魅力

# Popup
::msgcat::mcset $loc "Select This Power"

