set loc ja

# Window title
::msgcat::mcset $loc Character

::msgcat::mcset $loc TestChar 漢

# Menu
::msgcat::mcset $loc "Change Icon" アイコン変更
::msgcat::mcset $loc "Change Name" 名前変更
::msgcat::mcset $loc "File Character" ファイルに書き出す

# Change name dialog
::msgcat::mcset $loc pyname-title "Character Name"
::msgcat::mcset $loc pyname-msg "Character names may be up to 15 chars long and may not contain control chars."
::msgcat::mcset $loc pyname-prompt "Name"
::msgcat::mcset $loc pyname-invalid-title "Invalid Name"
::msgcat::mcset $loc pyname-invalid-msg "Control chars aren't allowed in character names."

# Pages
::msgcat::mcset $loc info 情報
::msgcat::mcset $loc flag フラグ
::msgcat::mcset $loc mutation 突然変異
::msgcat::mcset $loc virtue 徳
::msgcat::mcset $loc note メモ

# Flags
::msgcat::mcset $loc "Name" 名前
::msgcat::mcset $loc "Sex" 性別
::msgcat::mcset $loc "Race" 種族
::msgcat::mcset $loc "Class" 職業
::msgcat::mcset $loc "Title" 称号
::msgcat::mcset $loc "HP" ＨＰ
::msgcat::mcset $loc "SP" ＭＰ
::msgcat::mcset $loc "Realm 1" 領域１ 
::msgcat::mcset $loc "Realm 2" 領域２
::msgcat::mcset $loc "Patron" 守護魔神
::msgcat::mcset $loc Age 年齢
::msgcat::mcset $loc Height 身長
::msgcat::mcset $loc Weight 体重
::msgcat::mcset $loc "Status" 社会的地位
::msgcat::mcset $loc "Maximize" 最大化
::msgcat::mcset $loc "Preserve" 保存
::msgcat::mcset $loc Self 内部
::msgcat::mcset $loc RB 種
::msgcat::mcset $loc CB 職
::msgcat::mcset $loc EB 装
::msgcat::mcset $loc Best 最高
::msgcat::mcset $loc STR: 腕力:
::msgcat::mcset $loc INT: 知力:
::msgcat::mcset $loc WIS: 賢さ:
::msgcat::mcset $loc DEX: 器用:
::msgcat::mcset $loc CON: 耐久:
::msgcat::mcset $loc CHR: 魅力:
::msgcat::mcset $loc Level レベル
::msgcat::mcset $loc "Cur Exp" 経験値
::msgcat::mcset $loc "Max Exp" 最大経験値
::msgcat::mcset $loc "Adv Exp" 次レベル
::msgcat::mcset $loc Gold 所持金
::msgcat::mcset $loc Burden 荷重
::msgcat::mcset $loc "Armor" ＡＣ
::msgcat::mcset $loc "Fight" 格闘
::msgcat::mcset $loc "Melee" 打撃
::msgcat::mcset $loc "Shoot" 射撃
::msgcat::mcset $loc "Blows" 打撃回数
::msgcat::mcset $loc "Shots" 射撃回数
::msgcat::mcset $loc "Infra" 赤外
::msgcat::mcset $loc "+ to Skill" スキル補正
::msgcat::mcset $loc "Deadliness" 殺傷力
::msgcat::mcset $loc "Blows/Round" 打撃回数
::msgcat::mcset $loc "Shots/Round" 射撃回数
::msgcat::mcset $loc "Saving Throw" 魔法防御
::msgcat::mcset $loc "Stealth" 隠密行動
::msgcat::mcset $loc "Fighting" 打撃
::msgcat::mcset $loc "Shooting" 射撃
::msgcat::mcset $loc "Disarming" 解除
::msgcat::mcset $loc "Magic Device" 魔法道具使用
::msgcat::mcset $loc "Perception" 知覚
::msgcat::mcset $loc "Searching" 探索
::msgcat::mcset $loc Infravision 赤外線視力
::msgcat::mcset $loc "Awful" 酷い
::msgcat::mcset $loc "Very Bad" 最低
::msgcat::mcset $loc "Bad" 悪い
::msgcat::mcset $loc "Poor" 劣る
::msgcat::mcset $loc "Mediocre" 並
::msgcat::mcset $loc "Fair" 普通
::msgcat::mcset $loc "Good" 良い
::msgcat::mcset $loc "Very Good" 大変良い
::msgcat::mcset $loc "Excellent" 卓越
::msgcat::mcset $loc "Superb" 超越
::msgcat::mcset $loc "Heroic" 英雄的
::msgcat::mcset $loc "Legendary" 伝説的
::msgcat::mcset $loc "Chaos Rank" カオスランク
::msgcat::mcset $loc "Amber \[%d\]" "アンバー \[%d\]"

# Infravision
# Note: infra-none can be same as infra-fmt if you want (it will say "0 feet")
::msgcat::mcset $loc infra-none None
::msgcat::mcset $loc infra-fmt "%d %s"
::msgcat::mcset $loc foot
::msgcat::mcset $loc metre
::msgcat::mcset $loc feet
::msgcat::mcset $loc metres
