set loc ja

# Window title
::msgcat::mcset $loc "%s Tips" "日本語版 %s 豆知識"

# Tips File
::msgcat::mcset $loc tips.txt tips_j.txt

# Text
::msgcat::mcset $loc "Welcome to %s" "日本語版 %s にようこそ"
::msgcat::mcset $loc "Times 18 bold" "ＭＳ 明朝 12 bold"
::msgcat::mcset $loc "Did you know...\n" "知ってましたか...\n"
::msgcat::mcset $loc "Show this window every time the game starts" "ゲームを起動するたびにこのウィンドウを表示する"
::msgcat::mcset $loc "< Back" "<前"
::msgcat::mcset $loc "Next >" "次>"

