set loc ja

::msgcat::mcset $loc Knowledge 情報
::msgcat::mcset $loc artifact アーティファクト
::msgcat::mcset $loc monster モンスター
::msgcat::mcset $loc object アイテム
::msgcat::mcset $loc pet ペット
::msgcat::mcset $loc quest クエスト
::msgcat::mcset $loc home 我が家
::msgcat::mcset $loc "%d in group, %d known" "合計 %d、%d が既知"
::msgcat::mcset $loc "%d in group" "合計 %d"
::msgcat::mcset $loc "%d items" "合計 %d"

# Search dialog
::msgcat::mcset $loc find-prompt 名前

if 0 {
# Artifact groups
::msgcat::mcset $loc "Light Sources" 光源
::msgcat::mcset $loc "Amulets" アミュレット
::msgcat::mcset $loc "Rings" 指輪
::msgcat::mcset $loc "Dragon Scale Mail" ドラゴン・スケイルメイル
::msgcat::mcset $loc "Hard Armour" 堅い鎧
::msgcat::mcset $loc "Soft Armour" 軟らかい鎧
::msgcat::mcset $loc "Shields" 盾
::msgcat::mcset $loc "Crown" 王冠
::msgcat::mcset $loc "Helms" ヘルメット
::msgcat::mcset $loc "Cloaks" クローク
::msgcat::mcset $loc "Gloves" 篭手
::msgcat::mcset $loc "Boots" 靴
::msgcat::mcset $loc "Swords" 刀剣
::msgcat::mcset $loc "Polearms" 長柄武器
::msgcat::mcset $loc "Hafted" 鈍器
::msgcat::mcset $loc "Bows" 弓

::msgcat::mcset $loc "Rods" ロッド
::msgcat::mcset $loc "Staffs" スタッフ
::msgcat::mcset $loc "Wands" ワンド
}

# Object groups
::msgcat::mcset $loc "Sword" 剣
::msgcat::mcset $loc "Polearm" 長柄武器
::msgcat::mcset $loc "Hafted" 鈍器
::msgcat::mcset $loc "Bow" 弓
::msgcat::mcset $loc "Ammunition" 矢／ボルト
::msgcat::mcset $loc "Shield" 盾
::msgcat::mcset $loc "Crown" 王冠
::msgcat::mcset $loc "Helm" ヘルメット
::msgcat::mcset $loc "Gloves" 篭手
::msgcat::mcset $loc "Boots" 靴
::msgcat::mcset $loc "Cloak" クローク
::msgcat::mcset $loc "Dragon Scale Mail" ドラゴン・スケイルメイル
::msgcat::mcset $loc "Hard Armor" 硬い防具
::msgcat::mcset $loc "Soft Armor" 軟らかい防具
::msgcat::mcset $loc "Ring" 指輪
::msgcat::mcset $loc "Amulet" アミュレット
::msgcat::mcset $loc "Light Source" 光源
::msgcat::mcset $loc "Potion" 薬
::msgcat::mcset $loc "Scroll" 巻物
::msgcat::mcset $loc "Wand" ワンド
::msgcat::mcset $loc "Staff" スタッフ
::msgcat::mcset $loc "Rod" ロッド

::msgcat::mcset $loc "Prayer Book" 祈祷書
::msgcat::mcset $loc "Magic Book" 呪文書

::msgcat::mcset $loc "Illusion Book" 幻術書
::msgcat::mcset $loc "Nature Book" 自然魔術書

::msgcat::mcset $loc "Druid Book" ドルイド魔法書
::msgcat::mcset $loc "Necro Book" 死霊術書

::msgcat::mcset $loc "Life Book" 生命の魔法書
::msgcat::mcset $loc "Sorcery Book" 仙術の魔法書
::msgcat::mcset $loc "Nature Book" 自然の魔法書
::msgcat::mcset $loc "Chaos Book" カオスの魔法書
::msgcat::mcset $loc "Death Book" 暗黒の魔法書
::msgcat::mcset $loc "Trump Book" トランプの魔法書
::msgcat::mcset $loc "Arcane Book" 秘術の魔法書

::msgcat::mcset $loc "Figurine" 人形
::msgcat::mcset $loc "Statue" 像
::msgcat::mcset $loc "Corpse" 死体

::msgcat::mcset $loc "Spikes" スパイク
::msgcat::mcset $loc "Digging Tool" 掘削道具
::msgcat::mcset $loc "Chest" 箱
::msgcat::mcset $loc "Food" 食糧
::msgcat::mcset $loc "Gold" 金
::msgcat::mcset $loc "Skeleton" 骨
::msgcat::mcset $loc "Junk" ガラクタ

::msgcat::mcset $loc "Mushroom" キノコ

# Monster groups
::msgcat::mcset $loc "Ancient Dragons" 古代ドラゴン
::msgcat::mcset $loc "Angelic Beings" 天使
::msgcat::mcset $loc "Birds" 鳥
::msgcat::mcset $loc "Canines" 犬類
::msgcat::mcset $loc "Creeping Coins" クリーピングコイン
::msgcat::mcset $loc "Demihumans" 半人
::msgcat::mcset $loc "Dragons" ドラゴン
::msgcat::mcset $loc "Elementals" エレメンタル
::msgcat::mcset $loc "Energy Ball" エネルギー球
::msgcat::mcset $loc "Eyes/Beholders" 眼/ビホルダー
::msgcat::mcset $loc "Felines" 猫類
::msgcat::mcset $loc "Ghosts" 幽霊
::msgcat::mcset $loc "Giant Ants" 巨大蟻
::msgcat::mcset $loc "Giant Bats" 巨大コウモリ
::msgcat::mcset $loc "Giant Centipedes" 巨大ムカデ
::msgcat::mcset $loc "Giant Dragon Flies" 巨大トンボ
::msgcat::mcset $loc "Giant Lice" 巨大シラミ
::msgcat::mcset $loc "Giants" ジャイアント
::msgcat::mcset $loc "Golems" ゴーレム
::msgcat::mcset $loc "Humans" 人間
::msgcat::mcset $loc "Hybrids" 合成獣
::msgcat::mcset $loc "Hydras" ヒドラ
::msgcat::mcset $loc "Mummies" ミイラ
::msgcat::mcset $loc "Icky Things" ベトベト
::msgcat::mcset $loc "Jellies" ジェリー
::msgcat::mcset $loc "Killer Beetles" キラービートル
::msgcat::mcset $loc "Kobolds" コボルド
::msgcat::mcset $loc "Lichs" リッチ
::msgcat::mcset $loc "Major Demons" 上位デーモン
::msgcat::mcset $loc "Minor Demons" 下位デーモン
::msgcat::mcset $loc "Molds" モールド
::msgcat::mcset $loc "Multiplying Insects" 昆虫
::msgcat::mcset $loc "Mushroom Patches" キノコ
::msgcat::mcset $loc "Nagas" ナーガ
::msgcat::mcset $loc "Ogres" オーガ
::msgcat::mcset $loc "Orcs" オーク
::msgcat::mcset $loc "Quadropeds" 四足獣
::msgcat::mcset $loc "Quylthulgs" クイルスルグ
::msgcat::mcset $loc "Reptiles/Amphibians" 爬虫類/両生類
::msgcat::mcset $loc "Rodents" ネズミ/ウサギ
::msgcat::mcset $loc "Scorpions/Spiders" 蠍/蜘蛛
::msgcat::mcset $loc "Skeletons" スケルトン
::msgcat::mcset $loc "Snakes" 蛇
::msgcat::mcset $loc "Townspeople" 街の住民
::msgcat::mcset $loc "Tricksters" ミミック類
::msgcat::mcset $loc "Trolls" トロル
::msgcat::mcset $loc "Vampires" 吸血鬼
::msgcat::mcset $loc "Vortices" ボーテックス
::msgcat::mcset $loc "Water Dwellers" 水棲生物
::msgcat::mcset $loc "Wights/Wraiths" ワイト/レイス
::msgcat::mcset $loc "Worms/Worm Masses" イモムシ
::msgcat::mcset $loc "Xorns/Xarens" ゾーン/ザレン
::msgcat::mcset $loc "Yeeks" イーク
::msgcat::mcset $loc "Yeti" イェティ
::msgcat::mcset $loc "Zephyr Hounds" ハウンド
::msgcat::mcset $loc "Zombies/Mummies" ゾンビ/ミイラ
::msgcat::mcset $loc "Uniques" ユニーク

