set loc en

# Window title
::msgcat::mcset $loc Recall

::msgcat::mcset $loc header-object %s:
::msgcat::mcset $loc header-pile "A pile of %d items:"
::msgcat::mcset $loc header-monster "The %s:"
::msgcat::mcset $loc header-unique %s:
::msgcat::mcset $loc header-magic %s:
::msgcat::mcset $loc header-quest "%s - Danger level %d:"

::msgcat::mcset $loc memory-spell "Level %d  Mana %d  Fail %d%%"
::msgcat::mcset $loc memory-power "Level %d  Cost %d  Fail %d%%  Stat %s"

# Context menu
::msgcat::mcset $loc History
::msgcat::mcset $loc "Show Icon"
::msgcat::mcset $loc "Auto Expand"
::msgcat::mcset $loc "Recall 2.0"

# Pet commands
::msgcat::mcset $loc "Dismiss pets"
::msgcat::mcset $loc "Stay close"
::msgcat::mcset $loc "Follow me"
::msgcat::mcset $loc "Seek and destroy"
::msgcat::mcset $loc "Give me space"
::msgcat::mcset $loc "Stay away"
::msgcat::mcset $loc "Allow open doors"
::msgcat::mcset $loc "Disallow open doors"
::msgcat::mcset $loc "Allow pickup items"
::msgcat::mcset $loc "Disallow pickup items"

