set loc ja

# Window title
::msgcat::mcset $loc Recall 情報

::msgcat::mcset $loc header-object %s:
::msgcat::mcset $loc header-pile "A pile of %d items:"
::msgcat::mcset $loc header-monster "The %s:"
::msgcat::mcset $loc header-unique %s:
::msgcat::mcset $loc header-magic %s:
::msgcat::mcset $loc header-quest "%s - Danger level %d:"

::msgcat::mcset $loc memory-spell "Level %d  Mana %d  Fail %d%%"
::msgcat::mcset $loc memory-power "Level %d  Cost %d  Fail %d%%  Stat %s"

# Context menu
::msgcat::mcset $loc History
::msgcat::mcset $loc "Show Icon"
::msgcat::mcset $loc "Auto Expand"
::msgcat::mcset $loc "Recall 2.0"

# Pet commands
::msgcat::mcset $loc "Dismiss pets" ペットを放す
::msgcat::mcset $loc "Stay close" 近くにいろ
::msgcat::mcset $loc "Follow me" ついて来い
::msgcat::mcset $loc "Seek and destroy" 敵を探して倒せ
::msgcat::mcset $loc "Give me space" 少し離れろ
::msgcat::mcset $loc "Stay away" 離れろ
::msgcat::mcset $loc "Allow open doors" ドアを開けさせる
::msgcat::mcset $loc "Disallow open doors" ドアを開けさせない
::msgcat::mcset $loc "Allow pickup items" アイテムを拾わせる
::msgcat::mcset $loc "Disallow pickup items" アイテムを拾わせない

