set loc ja

# Window title
::msgcat::mcset $loc "Character Record" キャラクター記録
::msgcat::mcset $loc "Character Record for %s" "%s のキャラクター記録"

# Record menu
::msgcat::mcset $loc Record 記録
::msgcat::mcset $loc "Save As..." 名前を付けて保存

# Page titles
::msgcat::mcset $loc Dump 保存
::msgcat::mcset $loc Messages メッセージ
::msgcat::mcset $loc Photo 記念写真

# Statusbar
::msgcat::mcset $loc "Reading image file..." 画像読み込み中...
::msgcat::mcset $loc "Done." 終了
