.\"                                      Hey, EMACS: -*- nroff -*-
.\" Template-author: Stig E Sandoe
.\" CCLAN-NOTE: If you customise this page, please change author at the bottom
.\" 
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH Apps 1 "Summer 2003" 
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.\" CCLAN-NOTE: set NAME to your package, and then \- short description
.SH NAME
lbsd \- Langband sound-daemon
.SH SYNOPSIS
.B lbsd

.SH DESCRIPTION
.\"Add longer description here, I have just pasted from control here
This daemon is useless for anyone but langband-engine and
langband-zterm.  

This man-page is very simplified.  Please check the
package-documentation in /usr/share/doc/langband-engine/

.SH SEE ALSO
.BR langband-engine (3l), langband-vanilla (3l)
.SH AUTHOR
This manual page was written by Stig E Sandoe <stig@langband.org>

