set loc en

# Window title
::msgcat::mcset $loc Main

# File menu
::msgcat::mcset $loc File
::msgcat::mcset $loc Save
::msgcat::mcset $loc "Quit With Save"
::msgcat::mcset $loc Quit

# Inven menu
::msgcat::mcset $loc Inven
::msgcat::mcset $loc Equipment
::msgcat::mcset $loc Inventory
::msgcat::mcset $loc Inspect
::msgcat::mcset $loc Inscribe
::msgcat::mcset $loc Uninscribe

# Inven -> Use menu
::msgcat::mcset $loc Use
::msgcat::mcset $loc Destroy
::msgcat::mcset $loc Drop
::msgcat::mcset $loc "Pick Up"
::msgcat::mcset $loc "Take Off"
::msgcat::mcset $loc Wear/Wield
::msgcat::mcset $loc "Eat Food"
::msgcat::mcset $loc "Fire Missile"
::msgcat::mcset $loc "Fuel Light"
::msgcat::mcset $loc "Jam Spike"
::msgcat::mcset $loc Throw

# Inven -> Magic menu
::msgcat::mcset $loc Magic
::msgcat::mcset $loc Activate
::msgcat::mcset $loc "Aim Wand"
::msgcat::mcset $loc "Drink Potion"
::msgcat::mcset $loc "Read Scroll"
::msgcat::mcset $loc "Use Staff"
::msgcat::mcset $loc "Zap Rod"
::msgcat::mcset $loc Browse
::msgcat::mcset $loc Study

# Action menu
::msgcat::mcset $loc Action
::msgcat::mcset $loc Note
::msgcat::mcset $loc Repeat
::msgcat::mcset $loc Target
::msgcat::mcset $loc "End Shapechange"
::msgcat::mcset $loc Pets
::msgcat::mcset $loc "Use Power"

# Action -> Alter menu
::msgcat::mcset $loc Alter
::msgcat::mcset $loc Alter
::msgcat::mcset $loc Bash
::msgcat::mcset $loc Close
::msgcat::mcset $loc Disarm
::msgcat::mcset $loc Open
::msgcat::mcset $loc Tunnel

# Action -> Looking menu
::msgcat::mcset $loc Looking
::msgcat::mcset $loc Locate
::msgcat::mcset $loc Look
::msgcat::mcset $loc Map

# Action -> Resting menu
::msgcat::mcset $loc Resting
::msgcat::mcset $loc Rest
::msgcat::mcset $loc "Stay"
::msgcat::mcset $loc "Stay (With Pickup)"

# Action -> Searching menu
::msgcat::mcset $loc Searching
::msgcat::mcset $loc Search
::msgcat::mcset $loc "Search Mode"

# Action -> Movement menu
::msgcat::mcset $loc Movement
::msgcat::mcset $loc "Go Down"
::msgcat::mcset $loc "Go Up"
::msgcat::mcset $loc Run
::msgcat::mcset $loc "Walk"
::msgcat::mcset $loc "Walk (With Pickup)"

# Other menu
::msgcat::mcset $loc Other
::msgcat::mcset $loc "Character Info"
::msgcat::mcset $loc Feeling
::msgcat::mcset $loc "File Character"
::msgcat::mcset $loc "High Scores"
::msgcat::mcset $loc Knowledge
::msgcat::mcset $loc "Message History"
::msgcat::mcset $loc Photo
::msgcat::mcset $loc "Quest Status"
::msgcat::mcset $loc "Quest Status"
::msgcat::mcset $loc "Time Of Day"

# Options menu
#::msgcat::mcset $loc Options
::msgcat::mcset $loc Alternate
::msgcat::mcset $loc Assign
::msgcat::mcset $loc Borg
::msgcat::mcset $loc Color
::msgcat::mcset $loc Controls
::msgcat::mcset $loc Font
::msgcat::mcset $loc Icons
::msgcat::mcset $loc Keymap
::msgcat::mcset $loc Macros
::msgcat::mcset $loc Music
::msgcat::mcset $loc Options
::msgcat::mcset $loc "Prf Files"
::msgcat::mcset $loc Sound
::msgcat::mcset $loc Sprite
::msgcat::mcset $loc Squelch
::msgcat::mcset $loc "Use Music"
::msgcat::mcset $loc "Use Sound"

# Other -> Photo menu
::msgcat::mcset $loc Photo
::msgcat::mcset $loc photo-new New
::msgcat::mcset $loc photo-open Open

# Tool menu
::msgcat::mcset $loc Tool
::msgcat::mcset $loc "Vault Editor"

# Window menu
::msgcat::mcset $loc Window
::msgcat::mcset $loc "Arrange Windows..."
::msgcat::mcset $loc "Maximize Windows..."
::msgcat::mcset $loc "Save Window Positions"
::msgcat::mcset $loc "Load Window Positions"
::msgcat::mcset $loc "AutoSave Positions"
::msgcat::mcset $loc "Choice Window"
::msgcat::mcset $loc "Message Window"
::msgcat::mcset $loc "Messages Window"
::msgcat::mcset $loc "Micro Map Window"
::msgcat::mcset $loc "Misc Window"
::msgcat::mcset $loc "Progress Window"
::msgcat::mcset $loc "Recall Window"

# Help menu
::msgcat::mcset $loc Help
::msgcat::mcset $loc Help
::msgcat::mcset $loc Tips
::msgcat::mcset $loc "About %s..."

# Status message
::msgcat::mcset $loc Danger!
::msgcat::mcset $loc "Level %d"

# Depth
::msgcat::mcset $loc Arena
::msgcat::mcset $loc Quest
::msgcat::mcset $loc Town
::msgcat::mcset $loc Town/Wild
::msgcat::mcset $loc "Level %d"
::msgcat::mcset $loc "%d feet"

# Depth (OAngband: metric)
::msgcat::mcset $loc "%d m"

# Dialogs
::msgcat::mcset $loc dialog-title-defpos "Arrange Windows"
::msgcat::mcset $loc dialog-msg-defpos \
	"This will set the size and position of every window\
	to the default.\nYou will lose your custom window\
	positions.\n\nReally arrange the windows?"

::msgcat::mcset $loc dialog-title-max "Maximize Windows"
::msgcat::mcset $loc dialog-msg-max \
	"This will increase the size of the Main Window so that\
	the game windows fill the screen. It will also arrange\
	all the windows. You will lose your custom window\
	positions.\n\nReally maximize the windows?"

::msgcat::mcset $loc dialog-title-loadpos "Load Window Positions"
::msgcat::mcset $loc dialog-msg-loadpos-fail \
	"There are no saved windows positions to restore"
::msgcat::mcset $loc dialog-msg-loadpos \
	"Really load the saved window positions?"

::msgcat::mcset $loc dialog-title-quit "Quit %s"
::msgcat::mcset $loc dialog-msg-quit \
	"Do you really want to save the game and quit?"
::msgcat::mcset $loc dialog-msg-abort \
	"Do you really want to quit without saving?"

# Statusbar
::msgcat::mcset $loc status-center "Click to recenter the display."
::msgcat::mcset $loc status-depth "Click to toggle depth_in_feet."

# Right-click menu
::msgcat::mcset $loc "Rest as needed"
::msgcat::mcset $loc "Rest for HP/SP"

