set loc ja

# Window title
::msgcat::mcset $loc Main メイン

# File menu
::msgcat::mcset $loc File ファイル
::msgcat::mcset $loc Save セーブ
::msgcat::mcset $loc "Quit With Save" セーブして終了
::msgcat::mcset $loc Quit 終了

# Inven menu
::msgcat::mcset $loc Inven アイテム
::msgcat::mcset $loc Equipment 装備
::msgcat::mcset $loc Inventory 持ち物
::msgcat::mcset $loc Inspect 調べる
::msgcat::mcset $loc Inscribe 銘を刻む
::msgcat::mcset $loc Uninscribe 銘を消す

# Inven -> Use menu
::msgcat::mcset $loc Use 使う
::msgcat::mcset $loc Destroy 壊す
::msgcat::mcset $loc Drop 落とす
::msgcat::mcset $loc "Pick Up" 拾う
::msgcat::mcset $loc "Take Off" 外す
::msgcat::mcset $loc Wear/Wield 装備する
::msgcat::mcset $loc "Eat Food" 食べる
::msgcat::mcset $loc "Fire Missile" 発射する
::msgcat::mcset $loc "Fuel Light" 光源補充
::msgcat::mcset $loc "Jam Spike" ドアにはさむ
::msgcat::mcset $loc Throw 投げる

# Inven -> Magic menu
::msgcat::mcset $loc Magic 魔法アイテム
::msgcat::mcset $loc Activate 発動する
::msgcat::mcset $loc "Aim Wand" 魔法棒を使う
::msgcat::mcset $loc "Drink Potion" 薬を飲む
::msgcat::mcset $loc "Read Scroll" 巻物を読む
::msgcat::mcset $loc "Use Staff" 杖を使う
::msgcat::mcset $loc "Zap Rod" ロッドを使う
::msgcat::mcset $loc Browse 本を開く
::msgcat::mcset $loc Study 学習する

# Action menu
::msgcat::mcset $loc Action 行動
::msgcat::mcset $loc Note メモ
::msgcat::mcset $loc Repeat 繰り返し
::msgcat::mcset $loc Target ターゲット
::msgcat::mcset $loc "End Shapechange"
::msgcat::mcset $loc Pets ペット
::msgcat::mcset $loc "Use Power" 特殊能力

# Action -> Alter menu
::msgcat::mcset $loc Alter 変える
::msgcat::mcset $loc Alter 変える
::msgcat::mcset $loc Bash 体当たり
::msgcat::mcset $loc Close 閉める
::msgcat::mcset $loc Disarm 解除する
::msgcat::mcset $loc Open 開く
::msgcat::mcset $loc Tunnel 穴を掘る

# Action -> Looking menu
::msgcat::mcset $loc Looking 見る
::msgcat::mcset $loc Locate
::msgcat::mcset $loc Look 見る
::msgcat::mcset $loc Map マップ

# Action -> Resting menu
::msgcat::mcset $loc Resting 休息
::msgcat::mcset $loc Rest 休息する
::msgcat::mcset $loc "Stay" "休憩"
::msgcat::mcset $loc "Stay (With Pickup)" "休憩(拾う)"

# Action -> Searching menu
::msgcat::mcset $loc Searching 探索
::msgcat::mcset $loc Search 探す
::msgcat::mcset $loc "Search Mode" 探索モード

# Action -> Movement menu
::msgcat::mcset $loc Movement 移動
::msgcat::mcset $loc "Go Down" 階段を下がる
::msgcat::mcset $loc "Go Up" 階段を上る
::msgcat::mcset $loc Run 走る
::msgcat::mcset $loc "Walk" "歩く"
::msgcat::mcset $loc "Walk (With Pickup)" "歩く(拾う)"

# Other menu
::msgcat::mcset $loc Other その他
::msgcat::mcset $loc "Character Info" キャラクター情報
::msgcat::mcset $loc Feeling 雰囲気
::msgcat::mcset $loc "File Character" キャラ情報セーブ
::msgcat::mcset $loc "High Scores" ハイスコア
::msgcat::mcset $loc Knowledge 知識
::msgcat::mcset $loc "Message History" メッセージ履歴
::msgcat::mcset $loc Photo 記念写真
::msgcat::mcset $loc "Quest Status" クエスト情報
::msgcat::mcset $loc "Quest Status" クエスト情報
::msgcat::mcset $loc "Time Of Day" ゲーム中時間

# Options menu
#::msgcat::mcset $loc Preferences 詳細設定
::msgcat::mcset $loc Alternate 変更
::msgcat::mcset $loc Assign アサイン
::msgcat::mcset $loc Borg ボーグ
::msgcat::mcset $loc Color 色
::msgcat::mcset $loc Controls
::msgcat::mcset $loc Font フォント
::msgcat::mcset $loc Icons
::msgcat::mcset $loc Keymap キーマップ
::msgcat::mcset $loc Macros マクロ
::msgcat::mcset $loc Music ＢＧＭ
::msgcat::mcset $loc Options オプション
::msgcat::mcset $loc "Prf Files"
::msgcat::mcset $loc Sound サウンド
::msgcat::mcset $loc Sprite アニメーション
::msgcat::mcset $loc Squelch 自動破壊
::msgcat::mcset $loc "Use Music" ＢＧＭ使用
::msgcat::mcset $loc "Use Sound" サウンド使用

# Other -> Photo menu
::msgcat::mcset $loc Photo 記念写真
::msgcat::mcset $loc photo-new 新規
::msgcat::mcset $loc photo-open 開く

# Tool menu
::msgcat::mcset $loc Tool ツール
::msgcat::mcset $loc "Vault Editor" 宝物庫エディタ

# Window menu
::msgcat::mcset $loc Window ウィンドウ
::msgcat::mcset $loc "Arrange Windows..." ウィンドウ整列
::msgcat::mcset $loc "Maximize Windows..." ウィンドウ最大化
::msgcat::mcset $loc "Save Window Positions" ウィンドウ位置保存
::msgcat::mcset $loc "Load Window Positions" ウィンドウ位置ロード
::msgcat::mcset $loc "AutoSave Positions" 位置を自動セーブ
::msgcat::mcset $loc "Choice Window" 選択ウィンドウ
::msgcat::mcset $loc "Message Window"
::msgcat::mcset $loc "Messages Window" メッセージウィンドウ
::msgcat::mcset $loc "Micro Map Window"
::msgcat::mcset $loc "Misc Window"
::msgcat::mcset $loc "Progress Window"
::msgcat::mcset $loc "Recall Window"

# Help menu
::msgcat::mcset $loc Help ヘルプ
::msgcat::mcset $loc Help ヘルプ
::msgcat::mcset $loc Tips 豆知識
::msgcat::mcset $loc "About %s..." "%s について"

# Status message
::msgcat::mcset $loc Danger! 危険！
::msgcat::mcset $loc "Level %d" "レベル %d"

# Depth
::msgcat::mcset $loc Arena アリーナ
::msgcat::mcset $loc Quest クエスト
::msgcat::mcset $loc Town 街
::msgcat::mcset $loc Town/Wild 街/荒野
::msgcat::mcset $loc "Level %d" "%d 階"
::msgcat::mcset $loc "%d feet"

# Depth (OAngband: metric)
::msgcat::mcset $loc "%d m"

# Dialogs
::msgcat::mcset $loc dialog-title-defpos "Arrange Windows"
::msgcat::mcset $loc dialog-msg-defpos \
	"This will set the size and position of every window\
	to the default.\nYou will lose your custom window\
	positions.\n\nReally arrange the windows?"

::msgcat::mcset $loc dialog-title-max "Maximize Windows"
::msgcat::mcset $loc dialog-msg-max \
	"This will increase the size of the Main Window so that\
	the game windows fill the screen. It will also arrange\
	all the windows. You will lose your custom window\
	positions.\n\nReally maximize the windows?"

::msgcat::mcset $loc dialog-title-loadpos "ウィンドウ位置をロード"
::msgcat::mcset $loc dialog-msg-loadpos-fail \
	"ウィンドウ位置のセーブデータがありません"
::msgcat::mcset $loc dialog-msg-loadpos \
	"本当にウィンドウ位置をロードしますか?"

::msgcat::mcset $loc dialog-title-quit "%sを終了"
::msgcat::mcset $loc dialog-msg-quit \
	"本当にセーブして終了しますか?"
::msgcat::mcset $loc dialog-msg-abort \
	"Do you really want to quit without saving?"

# Statusbar
::msgcat::mcset $loc status-center "Click to recenter the display."
::msgcat::mcset $loc status-depth "Click to toggle depth_in_feet."

# Right-click menu
::msgcat::mcset $loc "Rest as needed"
::msgcat::mcset $loc "Rest for HP/SP"

