set loc en

# Window title
::msgcat::mcset $loc Music

# Music menu
::msgcat::mcset $loc Music
::msgcat::mcset $loc "Use Music"

# Window
::msgcat::mcset $loc "Position %d/%d"
::msgcat::mcset $loc "(No current song)"

# Column titles
::msgcat::mcset $loc Playlist
::msgcat::mcset $loc Song

# Playlist menu
::msgcat::mcset $loc play-new "New Playlist..."
::msgcat::mcset $loc play-add "Add Playlists..."
::msgcat::mcset $loc play-edit "Edit Selected Playlist..."
::msgcat::mcset $loc play-remove "Remove Selected Playlists"

# Song menu
::msgcat::mcset $loc song-add-f "Add Files..."
::msgcat::mcset $loc song-add-d "Add Folder..."
::msgcat::mcset $loc song-remove-sel "Remove Selected Files"
::msgcat::mcset $loc song-remove-miss "Remove Missing Files"
::msgcat::mcset $loc song-remove-all "Remove All Files"

# Open file dialog
::msgcat::mcset $loc "Playlists"
::msgcat::mcset $loc "All supported types"
::msgcat::mcset $loc "All files"

# messageBox
::msgcat::mcset $loc title-song-remove-all "Remove All Songs"
::msgcat::mcset $loc msg-song-remove-all "Really remove all songs from the playlist \"%s\"?"

# Playlist editor
::msgcat::mcset $loc "Playlist Editor"
::msgcat::mcset $loc Title
::msgcat::mcset $loc Location
::msgcat::mcset $loc "Town (Day)"
::msgcat::mcset $loc "Town (Night)"
::msgcat::mcset $loc Dungeon
::msgcat::mcset $loc Quest
::msgcat::mcset $loc "Wild (Day)"
::msgcat::mcset $loc "Wild (Night)"
::msgcat::mcset $loc Arena
::msgcat::mcset $loc "Dungeon Level"
::msgcat::mcset $loc Min:
::msgcat::mcset $loc Max:
::msgcat::mcset $loc File
::msgcat::mcset $loc "Save As..."
::msgcat::mcset $loc Untitled
::msgcat::mcset $loc (unsaved)
::msgcat::mcset $loc untitled.mus

