# -*- Mode: Makefile -*-

CLEANFILES=*.o *.so *.fasl *.x86f *.err *.fas *.ufsl *.lib *.sparcf

# Top Level Makefile for xptest

clean:
	rm -f ${CLEANFILES}

distclean:	clean
	rm -f *~ *.bak .\#* \#*

