set loc en

#
# Book menu
#

# Menu title
::msgcat::mcset $loc Book
::msgcat::mcset $loc "%s Book - %s"

#
# Book window
#

# Column titles
::msgcat::mcset $loc Name
::msgcat::mcset $loc Level
::msgcat::mcset $loc Mana
::msgcat::mcset $loc Fail
::msgcat::mcset $loc Comment

# Window
::msgcat::mcset $loc prayer
::msgcat::mcset $loc spell

# Ex: "5 spells, 4 unknown"
::msgcat::mcset $loc "%d %s, %d unknown"

# Ex: "4 spells"
::msgcat::mcset $loc "%d %s"

# Popup
::msgcat::mcset $loc "Select This %s"
::msgcat::mcset $loc Cast
::msgcat::mcset $loc Recite
::msgcat::mcset $loc Study

