set loc ja

#
# Book menu
#

# Menu title
::msgcat::mcset $loc Book 魔法書
::msgcat::mcset $loc "%s Book - %s" "%sの魔法書 - %s"

#
# Book window
#

# Column titles
::msgcat::mcset $loc Name 名前
::msgcat::mcset $loc Level レベル
::msgcat::mcset $loc Mana ＭＰ
::msgcat::mcset $loc Fail 失率
::msgcat::mcset $loc Comment コメント

# Window
::msgcat::mcset $loc prayer 祈祷
::msgcat::mcset $loc spell 呪文

# Ex: "5 spells, 4 unknown"
::msgcat::mcset $loc "%d %s, %d unknown" "%d個の%s、%d個不明"

# Ex: "4 spells"
::msgcat::mcset $loc "%d %s" "%d個の%s"

# Popup
::msgcat::mcset $loc "Select This %s" "この%sを選択"
::msgcat::mcset $loc Cast 唱える
::msgcat::mcset $loc Recite 詠唱する
::msgcat::mcset $loc Study  学習

