@echo off
move angband.c angband.c
move angband.h angband.h
move angband.ico angband.ico
move angband.res angband.res
move archer.c archer.c
move archer.o archer.o
move artifact.c artifact.c
move artifact.o artifact.o
move autoconf.h autoconf.h
move autopick.c autopick.c
move autopick.o autopick.o
move bard.c bard.c
move bard.o bard.o
move bigsmov.bat bigsmov.bat
move bigsmov2.bat bigsmov2.bat
move birth.c birth.c
move birth.o birth.o
move bldg.c bldg.c
move bldg.o bldg.o
move c-string.c c-string.c
move c-string.h c-string.h
move c-string.o c-string.o
move c-vec.c c-vec.c
move c-vec.h c-vec.h
move c-vec.o c-vec.o
move cavalry.c cavalry.c
move cavalry.o cavalry.o
move cave.c cave.c
move cave.o cave.o
move classes.c classes.c
move classes.h classes.h
move classes.o classes.o
move cmd1.c cmd1.c
move cmd1.o cmd1.o
move cmd2.c cmd2.c
move cmd2.o cmd2.o
move cmd3.c cmd3.c
move cmd3.o cmd3.o
move cmd4.c cmd4.c
move cmd4.o cmd4.o
move cmd5.c cmd5.c
move cmd5.o cmd5.o
move cmd6.c cmd6.c
move cmd6.o cmd6.o
move combat.c combat.c
move combat.o combat.o
move defines.h defines.h
move demigod.c demigod.c
move demigod.o demigod.o
move devices.c devices.c
move devices.o devices.o
move do-spell.c do-spell.c
move do-spell.o do-spell.o
move duelist.c duelist.c
move duelist.o duelist.o
move dungeon.c dungeon.c
move dungeon.o dungeon.o
move effects.c effects.c
move effects.o effects.o
move ego.c ego.c
move equip.c equip.c
move equip.h equip.h
move equip.o equip.o
move externs.h externs.h
move fear.c fear.c
move fear.h fear.h
move fear.o fear.o
move files.c files.c
move files.o files.o
move flavor.c flavor.c
move flavor.o flavor.o
move floors.c floors.c
move floors.o floors.o
move generate.c generate.c
move generate.h generate.h
move generate.o generate.o
move gf.c gf.c
move grid.c grid.c
move grid.h grid.h
move grid.o grid.o
move h-basic.h h-basic.h
move h-config.h h-config.h
move h-define.h h-define.h
move h-system.h h-system.h
move h-type.h h-type.h
move hex.c hex.c
move hex_mage.c hex_mage.c
move hissatsu.c hissatsu.c
move hissatsu.o hissatsu.o
move home.c home.c
move home.h home.h
move home.o home.o
move init.h init.h
move init1.c init1.c
move init1.o init1.o
move init2.c init2.c
move init2.o init2.o
move int-map.c int-map.c
move int-map.h int-map.h
move int-map.o int-map.o
move inv.c inv.c
move lawyer.c lawyer.c
move lawyer.o lawyer.o
move load.c load.c
move load.o load.o
move mage.c mage.c
move mage.o mage.o
move maid-x11.c maid-x11.c
move main-cap.c main-cap.c
move main-dos.c main-dos.c
move main-gcu.c main-gcu.c
move main-ibm.c main-ibm.c
move main-mac.c main-mac.c
move main-sdl.c main-sdl.c
move main-win.c main-win.c
move main-win.o main-win.o
move main-x11.c main-x11.c
move main-xaw.c main-xaw.c
move main.c main.c
move makefile.inc Makefile.inc
move makefile.osx Makefile.osx
move makefile.src Makefile.src
move mauler.c mauler.c
move mauler.o mauler.o
move melee1.c melee1.c
move melee1.o melee1.o
move melee2.c melee2.c
move melee2.o melee2.o
move menu.c menu.c
move menu.h menu.h
move menu.o menu.o
move message.c message.c
move message.h message.h
move message.o message.o
move mon.c mon.c
move monk.c monk.c
move monk.o monk.o
move monster.c monster.c
move monster.o monster.o
move monster1.c monster1.c
move monster1.o monster1.o
move monster2.c monster2.c
move monster2.o monster2.o
move mspells1.c mspells1.c
move mspells1.o mspells1.o
move mspells2.c mspells2.c
move mspells2.o mspells2.o
move mut.c mut.c
move mut_a.c mut_a.c
move mut_a.o mut_a.o
move mystic.c mystic.c
move mystic.o mystic.o
move ninja.c ninja.c
move ninja.o ninja.o
move ninjalaw.c ninjalaw.c
move ninjalaw.o ninjalaw.o
move obj.c obj.c
move object1.c object1.c
move object1.o object1.o
move object2.c object2.c
move object2.o object2.o
move object3.c object3.c
move object3.o object3.o
move obj_kind.c obj_kind.c
move obj_kind.o obj_kind.o
move pack.c pack.c
move pack.h pack.h
move pack.o pack.o
move paladin.c paladin.c
move paladin.o paladin.o
move priest.c priest.c
move priest.o priest.o
move psion.c psion.c
move psion.o psion.o
move py_birth.c py_birth.c
move py_birth.o py_birth.o
move py_throw.c py_throw.c
move py_throw.h py_throw.h
move py_throw.o py_throw.o
move quest.c quest.c
move quest.h quest.h
move quest.o quest.o
move quiver.c quiver.c
move quiver.h quiver.h
move quiver.o quiver.o
move races.c races.c
move races.o races.o
move races_a.c races_a.c
move races_a.o races_a.o
move races_k.c races_k.c
move races_k.o races_k.o
move racial.c racial.c
move racial.o racial.o
move ranger.c ranger.c
move ranger.o ranger.o
move readdib.c readdib.c
move readdib.h readdib.h
move readdib.o readdib.o
move rect.c rect.c
move rect.h rect.h
move rect.o rect.o
move red_mage.c red_mage.c
move red_mage.o red_mage.o
move resist.c resist.c
move resist.h resist.h
move resist.o resist.o
move rogue.c rogue.c
move rogue.o rogue.o
move rooms.c rooms.c
move rooms.h rooms.h
move rooms.o rooms.o
move samurai.c samurai.c
move samurai.o samurai.o
move save.c save.c
move save.o save.o
move savefile.c savefile.c
move savefile.h savefile.h
move savefile.o savefile.o
move scores.c scores.c
move scores.h scores.h
move scores.o scores.o
move scout.c scout.c
move scout.o scout.o
move shop.c shop.c
move shop.h shop.h
move shop.o shop.o
move skills.c skills.c
move skills.o skills.o
move sniper.c sniper.c
move sniper.o sniper.o
move sorcerer.c sorcerer.c
move sorcerer.o sorcerer.o
move spells.c spells.c
move spells.h spells.h
move spells.o spells.o
move spells1.c spells1.c
move spells1.o spells1.o
move spells2.c spells2.c
move spells2.o spells2.o
move spells3.c spells3.c
move spells3.o spells3.o
move spells_a.c spells_a.c
move spells_a.o spells_a.o
move spells_c.c spells_c.c
move spells_c.o spells_c.o
move spells_h.c spells_h.c
move spells_h.o spells_h.o
move spells_m.c spells_m.c
move spells_m.o spells_m.o
move spells_s.c spells_s.c
move spells_s.o spells_s.o
move spoilers.c spoilers.c
move spoilers.o spoilers.o
move str-map.c str-map.c
move str-map.h str-map.h
move str-map.o str-map.o
move streams.c streams.c
move streams.h streams.h
move streams.o streams.o
move tables.c tables.c
move tables.o tables.o
move tourist.c tourist.c
move tourist.o tourist.o
move types.h types.h
move util.c util.c
move util.o util.o
move variable.c variable.c
move variable.o variable.o
move variant.c variant.c
move variant.h variant.h
move variant.o variant.o
move virtue.c virtue.c
move virtue.o virtue.o
move wall.bmp wall.bmp
move warlock.c warlock.c
move warlock.o warlock.o
move warrior.c warrior.c
move warrior.o warrior.o
move wild.c wild.c
move wild.o wild.o
move wizard1.c wizard1.c
move wizard1.o wizard1.o
move wizard2.c wizard2.c
move wizard2.o wizard2.o
move wiz_obj.c wiz_obj.c
move wiz_obj.o wiz_obj.o
move xtra1.c xtra1.c
move xtra1.o xtra1.o
move xtra2.c xtra2.c
move xtra2.o xtra2.o
move z-config.h z-config.h
move z-doc.c z-doc.c
move z-doc.h z-doc.h
move z-doc.o z-doc.o
move z-form.c z-form.c
move z-form.h z-form.h
move z-form.o z-form.o
move z-rand.c z-rand.c
move z-rand.h z-rand.h
move z-rand.o z-rand.o
move z-term.c z-term.c
move z-term.h z-term.h
move z-term.o z-term.o
move z-util.c z-util.c
move z-util.h z-util.h
move z-util.o z-util.o
move z-virt.c z-virt.c
move z-virt.h z-virt.h
move z-virt.o z-virt.o
move ..\aclocal.m4 ..\aclocal.m4
move ..\autogen.sh ..\autogen.sh
move ..\autopick.txt ..\autopick.txt
move ..\config.log ..\config.log
move ..\config.sub ..\config.sub
move ..\readme.txt ..\readme.txt
move ..\lib\help\attack.txt ..\lib\help\attack.txt
move ..\lib\help\birth.txt ..\lib\help\birth.txt
move ..\lib\help\bldg.txt ..\lib\help\bldg.txt
move ..\lib\help\classes.txt ..\lib\help\Classes.txt
move ..\lib\help\command.txt ..\lib\help\command.txt
move ..\lib\help\commdesc.txt ..\lib\help\commdesc.txt
move ..\lib\help\defend.txt ..\lib\help\defend.txt
move ..\lib\help\demigods.txt ..\lib\help\Demigods.txt
move ..\lib\help\demons.txt ..\lib\help\Demons.txt
move ..\lib\help\dragons.txt ..\lib\help\Dragons.txt
move ..\lib\help\dungeon.txt ..\lib\help\dungeon.txt
move ..\lib\help\editor.txt ..\lib\help\editor.txt
move ..\lib\help\faq.txt ..\lib\help\faq.txt
move ..\lib\help\gambling.txt ..\lib\help\gambling.txt
move ..\lib\help\general.txt ..\lib\help\general.txt
move ..\lib\help\helpinfo.txt ..\lib\help\helpinfo.txt
move ..\lib\help\magic.txt ..\lib\help\magic.txt
move ..\lib\help\monster.txt ..\lib\help\monster.txt
move ..\lib\help\objects.txt ..\lib\help\objects.txt
move ..\lib\help\option.txt ..\lib\help\option.txt
move ..\lib\help\pref.txt ..\lib\help\pref.txt
move ..\lib\help\races.txt ..\lib\help\Races.txt
move ..\lib\help\rings.txt ..\lib\help\rings.txt
move ..\lib\help\spells.csv ..\lib\help\spells.csv
move ..\lib\help\start.txt ..\lib\help\start.txt
move ..\lib\help\tang.txt ..\lib\help\tang.txt
move ..\lib\help\town.txt ..\lib\help\town.txt
move ..\lib\help\version.txt ..\lib\help\version.txt
move ..\lib\help\warlocks.txt ..\lib\help\Warlocks.txt
move ..\lib\file\a_cursed.txt ..\lib\file\a_cursed.txt
move ..\lib\file\a_high.txt ..\lib\file\a_high.txt
move ..\lib\file\a_low.txt ..\lib\file\a_low.txt
move ..\lib\file\a_med.txt ..\lib\file\a_med.txt
move ..\lib\file\chainswd.txt ..\lib\file\chainswd.txt
move ..\lib\file\credits.txt ..\lib\file\credits.txt
move ..\lib\file\dead.txt ..\lib\file\dead.txt
move ..\lib\file\death.txt ..\lib\file\death.txt
move ..\lib\file\elvish.txt ..\lib\file\elvish.txt
move ..\lib\file\error.txt ..\lib\file\error.txt
move ..\lib\file\lite_low.txt ..\lib\file\lite_low.txt
move ..\lib\file\lite_med.txt ..\lib\file\lite_med.txt
move ..\lib\file\mondeath.txt ..\lib\file\mondeath.txt
move ..\lib\file\monfear.txt ..\lib\file\monfear.txt
move ..\lib\file\monfrien.txt ..\lib\file\monfrien.txt
move ..\lib\file\monspeak.txt ..\lib\file\monspeak.txt
move ..\lib\file\news.txt ..\lib\file\news.txt
move ..\lib\file\news1.txt ..\lib\file\news1.txt
move ..\lib\file\news10.txt ..\lib\file\news10.txt
move ..\lib\file\news11.txt ..\lib\file\news11.txt
move ..\lib\file\news12.txt ..\lib\file\news12.txt
move ..\lib\file\news13.txt ..\lib\file\news13.txt
move ..\lib\file\news14.txt ..\lib\file\news14.txt
move ..\lib\file\news15.txt ..\lib\file\news15.txt
move ..\lib\file\news16.txt ..\lib\file\news16.txt
move ..\lib\file\news17.txt ..\lib\file\news17.txt
move ..\lib\file\news18.txt ..\lib\file\news18.txt
move ..\lib\file\news19.txt ..\lib\file\news19.txt
move ..\lib\file\news2.txt ..\lib\file\news2.txt
move ..\lib\file\news3.txt ..\lib\file\news3.txt
move ..\lib\file\news4.txt ..\lib\file\news4.txt
move ..\lib\file\news5.txt ..\lib\file\news5.txt
move ..\lib\file\news6.txt ..\lib\file\news6.txt
move ..\lib\file\news7.txt ..\lib\file\news7.txt
move ..\lib\file\news8.txt ..\lib\file\news8.txt
move ..\lib\file\news9.txt ..\lib\file\news9.txt
move ..\lib\file\ring_low.txt ..\lib\file\ring_low.txt
move ..\lib\file\ring_med.txt ..\lib\file\ring_med.txt
move ..\lib\file\rumors.txt ..\lib\file\rumors.txt
move ..\lib\file\seppuku.txt ..\lib\file\seppuku.txt
move ..\lib\file\silly.txt ..\lib\file\silly.txt
move ..\lib\file\sname.txt ..\lib\file\sname.txt
move ..\lib\file\timefun.txt ..\lib\file\timefun.txt
move ..\lib\file\timenorm.txt ..\lib\file\timenorm.txt
move ..\lib\file\w_cursed.txt ..\lib\file\w_cursed.txt
move ..\lib\file\w_high.txt ..\lib\file\w_high.txt
move ..\lib\file\w_low.txt ..\lib\file\w_low.txt
move ..\lib\file\w_med.txt ..\lib\file\w_med.txt
move ..\lib\edit\a_info.txt ..\lib\edit\a_info.txt
move ..\lib\edit\b_info.txt ..\lib\edit\b_info.txt
move ..\lib\edit\d_info.txt ..\lib\edit\d_info.txt
move ..\lib\edit\e_info.txt ..\lib\edit\e_info.txt
move ..\lib\edit\f_info.txt ..\lib\edit\f_info.txt
move ..\lib\edit\k_info.txt ..\lib\edit\k_info.txt
move ..\lib\edit\misc.txt ..\lib\edit\misc.txt
move ..\lib\edit\m_info.txt ..\lib\edit\m_info.txt
move ..\lib\edit\qi.vim ..\lib\edit\qi.vim
move ..\lib\edit\q_apina.txt ..\lib\edit\q_apina.txt
move ..\lib\edit\q_bears.alt ..\lib\edit\q_bears.alt
move ..\lib\edit\q_bears.txt ..\lib\edit\q_bears.txt
move ..\lib\edit\q_birds.txt ..\lib\edit\q_birds.txt
move ..\lib\edit\q_cellar.txt ..\lib\edit\q_cellar.txt
move ..\lib\edit\q_chaos.txt ..\lib\edit\q_chaos.txt
move ..\lib\edit\q_cq1.txt ..\lib\edit\q_cq1.txt
move ..\lib\edit\q_crypt.fix ..\lib\edit\q_crypt.fix
move ..\lib\edit\q_crypt.txt ..\lib\edit\q_crypt.txt
move ..\lib\edit\q_dino.txt ..\lib\edit\q_dino.txt
move ..\lib\edit\q_djinni.txt ..\lib\edit\q_djinni.txt
move ..\lib\edit\q_doom1.txt ..\lib\edit\q_doom1.txt
move ..\lib\edit\q_doom2.txt ..\lib\edit\q_doom2.txt
move ..\lib\edit\q_eric.txt ..\lib\edit\q_eric.txt
move ..\lib\edit\q_fairy.txt ..\lib\edit\q_fairy.txt
move ..\lib\edit\q_info.txt ..\lib\edit\q_info.txt
move ..\lib\edit\q_nature.txt ..\lib\edit\q_nature.txt
move ..\lib\edit\q_oberon.txt ..\lib\edit\q_oberon.txt
move ..\lib\edit\q_orcs.txt ..\lib\edit\q_orcs.txt
move ..\lib\edit\q_sewer.txt ..\lib\edit\q_sewer.txt
move ..\lib\edit\q_shrine.txt ..\lib\edit\q_shrine.txt
move ..\lib\edit\q_smug.txt ..\lib\edit\q_smug.txt
move ..\lib\edit\q_snakes.txt ..\lib\edit\q_snakes.txt
move ..\lib\edit\q_staff.txt ..\lib\edit\q_staff.txt
move ..\lib\edit\q_vapor.txt ..\lib\edit\q_vapor.txt
move ..\lib\edit\q_vapor2.txt ..\lib\edit\q_vapor2.txt
move ..\lib\edit\q_vault.txt ..\lib\edit\q_vault.txt
move ..\lib\edit\q_wargs.txt ..\lib\edit\q_wargs.txt
move ..\lib\edit\q_worms.txt ..\lib\edit\q_worms.txt
move ..\lib\edit\q_wtower.txt ..\lib\edit\q_wtower.txt
move ..\lib\edit\ri.vim ..\lib\edit\ri.vim
move ..\lib\edit\rooms.txt ..\lib\edit\rooms.txt
move ..\lib\edit\r_info.txt ..\lib\edit\r_info.txt
move ..\lib\edit\s_info.txt ..\lib\edit\s_info.txt
move ..\lib\edit\t_ana.txt ..\lib\edit\t_ana.txt
move ..\lib\edit\t_angwil.txt ..\lib\edit\t_angwil.txt
move ..\lib\edit\t_basic.txt ..\lib\edit\t_basic.txt
move ..\lib\edit\t_info.txt ..\lib\edit\t_info.txt
move ..\lib\edit\t_lite.txt ..\lib\edit\t_lite.txt
move ..\lib\edit\t_pref.txt ..\lib\edit\t_pref.txt
move ..\lib\edit\t_thalos.txt ..\lib\edit\t_thalos.txt
move ..\lib\edit\t_zul.txt ..\lib\edit\t_zul.txt
move ..\lib\edit\update.sh ..\lib\edit\update.sh
move ..\lib\edit\vaults.txt ..\lib\edit\vaults.txt
move ..\lib\edit\v_info.txt ..\lib\edit\v_info.txt
move ..\lib\edit\w_info.txt ..\lib\edit\w_info.txt
move ..\lib\pref\colors.prf ..\lib\pref\colors.prf
move ..\lib\pref\font-ami.prf ..\lib\pref\font-ami.prf
move ..\lib\pref\font-dos.prf ..\lib\pref\font-dos.prf
move ..\lib\pref\font-ibm.prf ..\lib\pref\font-ibm.prf
move ..\lib\pref\font-mac.prf ..\lib\pref\font-mac.prf
move ..\lib\pref\font-mon.prf ..\lib\pref\font-mon.prf
move ..\lib\pref\font-sdl.prf ..\lib\pref\font-sdl.prf
move ..\lib\pref\font-win.prf ..\lib\pref\font-win.prf
move ..\lib\pref\font-x11.prf ..\lib\pref\font-x11.prf
move ..\lib\pref\font-xxx.prf ..\lib\pref\font-xxx.prf
move ..\lib\pref\font.prf ..\lib\pref\font.prf
move ..\lib\pref\graf-ami.prf ..\lib\pref\graf-ami.prf
move ..\lib\pref\graf-dos.prf ..\lib\pref\graf-dos.prf
move ..\lib\pref\graf-gcu.prf ..\lib\pref\graf-gcu.prf
move ..\lib\pref\graf-ibm.prf ..\lib\pref\graf-ibm.prf
move ..\lib\pref\graf-mac.prf ..\lib\pref\graf-mac.prf
move ..\lib\pref\graf-new.prf ..\lib\pref\graf-new.prf
move ..\lib\pref\graf-sdl.prf ..\lib\pref\graf-sdl.prf
move ..\lib\pref\graf-win.prf ..\lib\pref\graf-win.prf
move ..\lib\pref\graf-x11.prf ..\lib\pref\graf-x11.prf
move ..\lib\pref\graf-xaw.prf ..\lib\pref\graf-xaw.prf
move ..\lib\pref\graf-xxx.prf ..\lib\pref\graf-xxx.prf
move ..\lib\pref\graf.prf ..\lib\pref\graf.prf
move ..\lib\pref\pickpref.prf ..\lib\pref\pickpref.prf
move ..\lib\pref\picktype.prf ..\lib\pref\picktype.prf
move ..\lib\pref\pref-acn.prf ..\lib\pref\pref-acn.prf
move ..\lib\pref\pref-ami.prf ..\lib\pref\pref-ami.prf
move ..\lib\pref\pref-emx.prf ..\lib\pref\pref-emx.prf
move ..\lib\pref\pref-gcu.prf ..\lib\pref\pref-gcu.prf
move ..\lib\pref\pref-key.prf ..\lib\pref\pref-key.prf
move ..\lib\pref\pref-mac.prf ..\lib\pref\pref-mac.prf
move ..\lib\pref\pref-opt.prf ..\lib\pref\pref-opt.prf
move ..\lib\pref\pref-sdl.prf ..\lib\pref\pref-sdl.prf
move ..\lib\pref\pref-win.prf ..\lib\pref\pref-win.prf
move ..\lib\pref\pref-x11.prf ..\lib\pref\pref-x11.prf
move ..\lib\pref\pref.prf ..\lib\pref\pref.prf
move ..\lib\pref\proxy.prf ..\lib\pref\proxy.prf
move ..\lib\pref\spell-xx.prf ..\lib\pref\spell-xx.prf
move ..\lib\pref\user-win.prf ..\lib\pref\user-win.prf
move ..\lib\pref\user.prf ..\lib\pref\user.prf
move ..\lib\pref\xtra-gcu.prf ..\lib\pref\xtra-gcu.prf
move ..\lib\pref\xtra-new.prf ..\lib\pref\xtra-new.prf
move ..\lib\pref\xtra-xxx.prf ..\lib\pref\xtra-xxx.prf
move changes changes
