call clean.bat
del /Q ..\setup\lib\readme.txt
del /Q ..\setup\lib\customize\*.*
del /Q ..\setup\lib\fonts\*.*
del /Q ..\setup\lib\gamedata\*.*
del /Q ..\setup\lib\help\*.*
del /Q ..\setup\lib\icons\*.*
del /Q ..\setup\lib\screens\*.*
del /Q ..\setup\lib\sounds\*.*
del /Q ..\setup\lib\tiles\*.*
del /Q ..\setup\lib\tiles\gervais\*.*
del /Q ..\setup\lib\tiles\pseudo\*.*
del /Q ..\setup\lib\tiles\shockbolt\*.*
del /Q ..\setup\lib\user\save\*.*
del /Q ..\setup\manual\*.*
del /Q ..\setup\noteye\*.*
del /Q ..\setup\src\*.*
del /Q ..\setup\src\client\*.*
del /Q ..\setup\src\common\*.*
del /Q ..\setup\src\curses\*.*
del /Q ..\setup\src\fix\*.*
del /Q ..\setup\src\SDL\*.*
del /Q ..\setup\src\server\*.*
del /Q ..\setup\src\win\*.*
del /Q ..\setup\*.txt
del /Q ..\setup\*.bat
del /Q ..\setup\*.dll
del /Q ..\setup\*.exe
del /Q ..\setup\Manual.*
pause