/*
** Lua binding: misc
** Generated automatically by tolua 4.0a - angband.
*/

#include "lua/tolua.h"

/* Exported function */
int  tolua_misc_open (lua_State* tolua_S);
void tolua_misc_close (lua_State* tolua_S);

#include "angband.h"

/* function to register type */
static void toluaI_reg_types (lua_State* tolua_S)
{
(void) tolua_S;	/* Hack - prevent compiler warnings */
}

/* function: cave_set_feat */
static int toluaI_misc_cave_set_feat00(lua_State* tolua_S)
{
 if (!tolua_istype(tolua_S,1,LUA_TNUMBER,0) ||
     !tolua_istype(tolua_S,2,LUA_TNUMBER,0) ||
     !tolua_istype(tolua_S,3,LUA_TNUMBER,0) ||
     !tolua_isnoobj(tolua_S,4))
 {
  TOLUA_ERR_FN(cave_set_feat);
 } else {
  int x = ((int)  tolua_getnumber(tolua_S,1,0));
  int y = ((int)  tolua_getnumber(tolua_S,2,0));
  int feat = ((int)  tolua_getnumber(tolua_S,3,0));
  cave_set_feat(x,y,feat);
 }
 return 0;
}

/* Open function */
int tolua_misc_open (lua_State* tolua_S)
{
 tolua_open(tolua_S);
 toluaI_reg_types(tolua_S);
 TOLUA_DEF(TRUE);
 TOLUA_DEF(FALSE);
 TOLUA_DEF(FEAT_NONE);
 TOLUA_DEF(FEAT_FLOOR);
 TOLUA_DEF(FEAT_OPEN);
 TOLUA_DEF(FEAT_BROKEN);
 TOLUA_DEF(FEAT_LESS);
 TOLUA_DEF(FEAT_MORE);
 TOLUA_DEF(FEAT_SAND);
 TOLUA_DEF(FEAT_SALT);
 TOLUA_DEF(FEAT_WET_MUD);
 TOLUA_DEF(FEAT_DRY_MUD);
 TOLUA_DEF(FEAT_FLOOR_TILE);
 TOLUA_DEF(FEAT_FLOOR_WOOD);
 TOLUA_DEF(FEAT_PEBBLES);
 TOLUA_DEF(FEAT_SOLID_LAVA);
 TOLUA_DEF(FEAT_CLOSED);
 TOLUA_DEF(FEAT_PILLAR);
 TOLUA_DEF(FEAT_SECRET);
 TOLUA_DEF(FEAT_RUBBLE);
 TOLUA_DEF(FEAT_MAGMA);
 TOLUA_DEF(FEAT_QUARTZ);
 TOLUA_DEF(FEAT_MAGMA_K);
 TOLUA_DEF(FEAT_QUARTZ_K);
 TOLUA_DEF(FEAT_WALL_EXTRA);
 TOLUA_DEF(FEAT_WALL_INNER);
 TOLUA_DEF(FEAT_WALL_OUTER);
 TOLUA_DEF(FEAT_WALL_SOLID);
 TOLUA_DEF(FEAT_PERM_EXTRA);
 TOLUA_DEF(FEAT_PERM_INNER);
 TOLUA_DEF(FEAT_PERM_OUTER);
 TOLUA_DEF(FEAT_PERM_SOLID);
 TOLUA_DEF(FEAT_PATTERN_START);
 TOLUA_DEF(FEAT_PATTERN_1);
 TOLUA_DEF(FEAT_PATTERN_2);
 TOLUA_DEF(FEAT_PATTERN_3);
 TOLUA_DEF(FEAT_PATTERN_4);
 TOLUA_DEF(FEAT_PATTERN_END);
 TOLUA_DEF(FEAT_PATTERN_OLD);
 TOLUA_DEF(FEAT_PATTERN_XTRA1);
 TOLUA_DEF(FEAT_PATTERN_XTRA2);
 TOLUA_DEF(FEAT_DEEP_WATER);
 TOLUA_DEF(FEAT_SHAL_WATER);
 TOLUA_DEF(FEAT_DEEP_LAVA);
 TOLUA_DEF(FEAT_SHAL_LAVA);
 TOLUA_DEF(FEAT_DIRT);
 TOLUA_DEF(FEAT_GRASS);
 TOLUA_DEF(FEAT_OCEAN_WATER);
 TOLUA_DEF(FEAT_DEEP_ACID);
 TOLUA_DEF(FEAT_SHAL_ACID);
 TOLUA_DEF(FEAT_TREE_WATER);
 TOLUA_DEF(FEAT_TREES);
 TOLUA_DEF(FEAT_MOUNTAIN);
 TOLUA_DEF(FEAT_SNOW_MOUNTAIN);
 TOLUA_DEF(FEAT_BOULDER);
 TOLUA_DEF(FEAT_PINE_TREE);
 TOLUA_DEF(FEAT_SNOW_TREE);
 TOLUA_DEF(FEAT_OBELISK);
 TOLUA_DEF(FEAT_FENCE);
 TOLUA_DEF(FEAT_WELL);
 TOLUA_DEF(FEAT_FOUNTAIN);
 TOLUA_DEF(FEAT_JUNGLE);
 TOLUA_DEF(FEAT_BUSH);
 TOLUA_DEF(FEAT_DEAD_BUSH);
 TOLUA_DEF(FEAT_GRASS_LONG);
 TOLUA_DEF(FEAT_ROCK_GEN);
 TOLUA_DEF(FEAT_ROCK_SNOW);
 TOLUA_DEF(FEAT_TREE_GEN);
 TOLUA_DEF(FEAT_TREE_SNOW);
 TOLUA_DEF(FEAT_SNOW);
 TOLUA_DEF(FEAT_DEEP_SWAMP);
 TOLUA_DEF(FEAT_SHAL_SWAMP);
 TOLUA_FUN(cave_set_feat,toluaI_misc_cave_set_feat00);
 return 1;
}
/* Close function */
void tolua_misc_close (lua_State* tolua_S)
{
 TOLUA_UNDEF(TRUE);
 TOLUA_UNDEF(FALSE);
 TOLUA_UNDEF(FEAT_NONE);
 TOLUA_UNDEF(FEAT_FLOOR);
 TOLUA_UNDEF(FEAT_OPEN);
 TOLUA_UNDEF(FEAT_BROKEN);
 TOLUA_UNDEF(FEAT_LESS);
 TOLUA_UNDEF(FEAT_MORE);
 TOLUA_UNDEF(FEAT_SAND);
 TOLUA_UNDEF(FEAT_SALT);
 TOLUA_UNDEF(FEAT_WET_MUD);
 TOLUA_UNDEF(FEAT_DRY_MUD);
 TOLUA_UNDEF(FEAT_FLOOR_TILE);
 TOLUA_UNDEF(FEAT_FLOOR_WOOD);
 TOLUA_UNDEF(FEAT_PEBBLES);
 TOLUA_UNDEF(FEAT_SOLID_LAVA);
 TOLUA_UNDEF(FEAT_CLOSED);
 TOLUA_UNDEF(FEAT_PILLAR);
 TOLUA_UNDEF(FEAT_SECRET);
 TOLUA_UNDEF(FEAT_RUBBLE);
 TOLUA_UNDEF(FEAT_MAGMA);
 TOLUA_UNDEF(FEAT_QUARTZ);
 TOLUA_UNDEF(FEAT_MAGMA_K);
 TOLUA_UNDEF(FEAT_QUARTZ_K);
 TOLUA_UNDEF(FEAT_WALL_EXTRA);
 TOLUA_UNDEF(FEAT_WALL_INNER);
 TOLUA_UNDEF(FEAT_WALL_OUTER);
 TOLUA_UNDEF(FEAT_WALL_SOLID);
 TOLUA_UNDEF(FEAT_PERM_EXTRA);
 TOLUA_UNDEF(FEAT_PERM_INNER);
 TOLUA_UNDEF(FEAT_PERM_OUTER);
 TOLUA_UNDEF(FEAT_PERM_SOLID);
 TOLUA_UNDEF(FEAT_PATTERN_START);
 TOLUA_UNDEF(FEAT_PATTERN_1);
 TOLUA_UNDEF(FEAT_PATTERN_2);
 TOLUA_UNDEF(FEAT_PATTERN_3);
 TOLUA_UNDEF(FEAT_PATTERN_4);
 TOLUA_UNDEF(FEAT_PATTERN_END);
 TOLUA_UNDEF(FEAT_PATTERN_OLD);
 TOLUA_UNDEF(FEAT_PATTERN_XTRA1);
 TOLUA_UNDEF(FEAT_PATTERN_XTRA2);
 TOLUA_UNDEF(FEAT_DEEP_WATER);
 TOLUA_UNDEF(FEAT_SHAL_WATER);
 TOLUA_UNDEF(FEAT_DEEP_LAVA);
 TOLUA_UNDEF(FEAT_SHAL_LAVA);
 TOLUA_UNDEF(FEAT_DIRT);
 TOLUA_UNDEF(FEAT_GRASS);
 TOLUA_UNDEF(FEAT_OCEAN_WATER);
 TOLUA_UNDEF(FEAT_DEEP_ACID);
 TOLUA_UNDEF(FEAT_SHAL_ACID);
 TOLUA_UNDEF(FEAT_TREE_WATER);
 TOLUA_UNDEF(FEAT_TREES);
 TOLUA_UNDEF(FEAT_MOUNTAIN);
 TOLUA_UNDEF(FEAT_SNOW_MOUNTAIN);
 TOLUA_UNDEF(FEAT_BOULDER);
 TOLUA_UNDEF(FEAT_PINE_TREE);
 TOLUA_UNDEF(FEAT_SNOW_TREE);
 TOLUA_UNDEF(FEAT_OBELISK);
 TOLUA_UNDEF(FEAT_FENCE);
 TOLUA_UNDEF(FEAT_WELL);
 TOLUA_UNDEF(FEAT_FOUNTAIN);
 TOLUA_UNDEF(FEAT_JUNGLE);
 TOLUA_UNDEF(FEAT_BUSH);
 TOLUA_UNDEF(FEAT_DEAD_BUSH);
 TOLUA_UNDEF(FEAT_GRASS_LONG);
 TOLUA_UNDEF(FEAT_ROCK_GEN);
 TOLUA_UNDEF(FEAT_ROCK_SNOW);
 TOLUA_UNDEF(FEAT_TREE_GEN);
 TOLUA_UNDEF(FEAT_TREE_SNOW);
 TOLUA_UNDEF(FEAT_SNOW);
 TOLUA_UNDEF(FEAT_DEEP_SWAMP);
 TOLUA_UNDEF(FEAT_SHAL_SWAMP);
 TOLUA_UNDEF(cave_set_feat);
}
