/*
** Lua binding: ui
** Generated automatically by tolua 4.0a - angband.
*/

#include "lua/tolua.h"

/* Exported function */
int  tolua_ui_open (lua_State* tolua_S);
void tolua_ui_close (lua_State* tolua_S);

#include "angband.h"

/* function to register type */
static void toluaI_reg_types (lua_State* tolua_S)
{
(void) tolua_S;	/* Hack - prevent compiler warnings */
}

/* function: update_stuff */
static int toluaI_ui_update_stuff00(lua_State* tolua_S)
{
 if (!tolua_isnoobj(tolua_S,1))
 {
  TOLUA_ERR_FN(update_stuff);
 } else {
  update_stuff();
 }
 return 0;
}

/* function: redraw_stuff */
static int toluaI_ui_redraw_stuff00(lua_State* tolua_S)
{
 if (!tolua_isnoobj(tolua_S,1))
 {
  TOLUA_ERR_FN(redraw_stuff);
 } else {
  redraw_stuff();
 }
 return 0;
}

/* function: window_stuff */
static int toluaI_ui_window_stuff00(lua_State* tolua_S)
{
 if (!tolua_isnoobj(tolua_S,1))
 {
  TOLUA_ERR_FN(window_stuff);
 } else {
  window_stuff();
 }
 return 0;
}

/* function: handle_stuff */
static int toluaI_ui_handle_stuff00(lua_State* tolua_S)
{
 if (!tolua_isnoobj(tolua_S,1))
 {
  TOLUA_ERR_FN(handle_stuff);
 } else {
  handle_stuff();
 }
 return 0;
}

/* function: message_flush */
static int toluaI_ui_message_flush00(lua_State* tolua_S)
{
 if (!tolua_isnoobj(tolua_S,1))
 {
  TOLUA_ERR_FN(message_flush);
 } else {
  message_flush();
 }
 return 0;
}

/* function: msgf */
static int toluaI_ui_msgf00(lua_State* tolua_S)
{
 if (!tolua_istype(tolua_S,1,LUA_TSTRING,0) ||
     !tolua_isnoobj(tolua_S,2))
 {
  TOLUA_ERR_FN(msgf);
 } else {
  cptr fmt = ((cptr)  tolua_getstring(tolua_S,1,0));
  msgf(fmt);
 }
 return 0;
}

/* function: get_check */
static int toluaI_ui_get_check00(lua_State* tolua_S)
{
 if (!tolua_istype(tolua_S,1,LUA_TSTRING,0) ||
     !tolua_isnoobj(tolua_S,2))
 {
  TOLUA_ERR_FN(get_check);
 } else {
  cptr prompt = ((cptr)  tolua_getstring(tolua_S,1,0));
  bool toluaI_ret = (bool)  get_check(prompt);
  tolua_pushbool(tolua_S,(int)toluaI_ret);
 }
 return 1;
}

/* function: sound */
static int toluaI_ui_sound00(lua_State* tolua_S)
{
 if (!tolua_istype(tolua_S,1,LUA_TNUMBER,0) ||
     !tolua_isnoobj(tolua_S,2))
 {
  TOLUA_ERR_FN(sound);
 } else {
  int num = ((int)  tolua_getnumber(tolua_S,1,0));
  sound(num);
 }
 return 0;
}

/* Open function */
int tolua_ui_open (lua_State* tolua_S)
{
 tolua_open(tolua_S);
 toluaI_reg_types(tolua_S);
 TOLUA_DEF(TERM_DARK);
 TOLUA_DEF(TERM_WHITE);
 TOLUA_DEF(TERM_SLATE);
 TOLUA_DEF(TERM_ORANGE);
 TOLUA_DEF(TERM_RED);
 TOLUA_DEF(TERM_GREEN);
 TOLUA_DEF(TERM_BLUE);
 TOLUA_DEF(TERM_UMBER);
 TOLUA_DEF(TERM_L_DARK);
 TOLUA_DEF(TERM_L_WHITE);
 TOLUA_DEF(TERM_VIOLET);
 TOLUA_DEF(TERM_YELLOW);
 TOLUA_DEF(TERM_L_RED);
 TOLUA_DEF(TERM_L_GREEN);
 TOLUA_DEF(TERM_L_BLUE);
 TOLUA_DEF(TERM_L_UMBER);
 TOLUA_DEF(SOUND_NONE);
 TOLUA_DEF(SOUND_HIT);
 TOLUA_DEF(SOUND_MISS);
 TOLUA_DEF(SOUND_FLEE);
 TOLUA_DEF(SOUND_DROP);
 TOLUA_DEF(SOUND_KILL);
 TOLUA_DEF(SOUND_LEVEL);
 TOLUA_DEF(SOUND_DEATH);
 TOLUA_DEF(SOUND_STUDY);
 TOLUA_DEF(SOUND_TELEPORT);
 TOLUA_DEF(SOUND_SHOOT);
 TOLUA_DEF(SOUND_QUAFF);
 TOLUA_DEF(SOUND_ZAP);
 TOLUA_DEF(SOUND_WALK);
 TOLUA_DEF(SOUND_TPOTHER);
 TOLUA_DEF(SOUND_HITWALL);
 TOLUA_DEF(SOUND_EAT);
 TOLUA_DEF(SOUND_STORE1);
 TOLUA_DEF(SOUND_STORE2);
 TOLUA_DEF(SOUND_STORE3);
 TOLUA_DEF(SOUND_STORE4);
 TOLUA_DEF(SOUND_DIG);
 TOLUA_DEF(SOUND_OPENDOOR);
 TOLUA_DEF(SOUND_SHUTDOOR);
 TOLUA_DEF(SOUND_TPLEVEL);
 TOLUA_DEF(SOUND_SCROLL);
 TOLUA_DEF(SOUND_BUY);
 TOLUA_DEF(SOUND_SELL);
 TOLUA_DEF(SOUND_WARN);
 TOLUA_DEF(SOUND_ROCKET);
 TOLUA_DEF(SOUND_N_KILL);
 TOLUA_DEF(SOUND_U_KILL);
 TOLUA_DEF(SOUND_QUEST);
 TOLUA_DEF(SOUND_HEAL);
 TOLUA_DEF(SOUND_X_HEAL);
 TOLUA_DEF(SOUND_BITE);
 TOLUA_DEF(SOUND_CLAW);
 TOLUA_DEF(SOUND_M_SPELL);
 TOLUA_DEF(SOUND_SUMMON);
 TOLUA_DEF(SOUND_BREATH);
 TOLUA_DEF(SOUND_BALL);
 TOLUA_DEF(SOUND_M_HEAL);
 TOLUA_DEF(SOUND_ATK_SPELL);
 TOLUA_DEF(SOUND_EVIL);
 TOLUA_DEF(SOUND_TOUCH);
 TOLUA_DEF(SOUND_STING);
 TOLUA_DEF(SOUND_CRUSH);
 TOLUA_DEF(SOUND_SLIME);
 TOLUA_DEF(SOUND_WAIL);
 TOLUA_DEF(SOUND_WINNER);
 TOLUA_DEF(SOUND_FIRE);
 TOLUA_DEF(SOUND_ACID);
 TOLUA_DEF(SOUND_ELEC);
 TOLUA_DEF(SOUND_COLD);
 TOLUA_DEF(SOUND_ILLEGAL);
 TOLUA_DEF(SOUND_FAIL);
 TOLUA_DEF(SOUND_WAKEUP);
 TOLUA_DEF(SOUND_INVULN);
 TOLUA_DEF(SOUND_FALL);
 TOLUA_DEF(SOUND_PAIN);
 TOLUA_DEF(SOUND_DESTITEM);
 TOLUA_DEF(SOUND_MOAN);
 TOLUA_DEF(SOUND_SHOW);
 TOLUA_DEF(SOUND_UNUSED);
 TOLUA_DEF(SOUND_EXPLODE);
 TOLUA_DEF(SOUND_MAX);
 TOLUA_DEF(PU_BONUS);
 TOLUA_DEF(PU_TORCH);
 TOLUA_DEF(PU_HP);
 TOLUA_DEF(PU_MANA);
 TOLUA_DEF(PU_SPELLS);
 TOLUA_DEF(PU_VIEW);
 TOLUA_DEF(PU_MON_LITE);
 TOLUA_DEF(PU_MONSTERS);
 TOLUA_DEF(PU_DISTANCE);
 TOLUA_DEF(PU_FLOW);
 TOLUA_DEF(PR_MISC);
 TOLUA_DEF(PR_TITLE);
 TOLUA_DEF(PR_LEV);
 TOLUA_DEF(PR_EXP);
 TOLUA_DEF(PR_STATS);
 TOLUA_DEF(PR_ARMOR);
 TOLUA_DEF(PR_HP);
 TOLUA_DEF(PR_MANA);
 TOLUA_DEF(PR_GOLD);
 TOLUA_DEF(PR_DEPTH);
 TOLUA_DEF(PR_EQUIPPY);
 TOLUA_DEF(PR_HEALTH);
 TOLUA_DEF(PR_CUT);
 TOLUA_DEF(PR_STUN);
 TOLUA_DEF(PR_HUNGER);
 TOLUA_DEF(PR_STATUS);
 TOLUA_DEF(PR_BLIND);
 TOLUA_DEF(PR_CONFUSED);
 TOLUA_DEF(PR_AFRAID);
 TOLUA_DEF(PR_POISONED);
 TOLUA_DEF(PR_STATE);
 TOLUA_DEF(PR_SPEED);
 TOLUA_DEF(PR_STUDY);
 TOLUA_DEF(PR_EXTRA);
 TOLUA_DEF(PR_BASIC);
 TOLUA_DEF(PR_MAP);
 TOLUA_DEF(PR_WIPE);
 TOLUA_DEF(PW_INVEN);
 TOLUA_DEF(PW_EQUIP);
 TOLUA_DEF(PW_SPELL);
 TOLUA_DEF(PW_PLAYER);
 TOLUA_DEF(PW_SCRIPT_VARS);
 TOLUA_DEF(PW_SCRIPT_SOURCE);
 TOLUA_DEF(PW_MESSAGE);
 TOLUA_DEF(PW_OVERHEAD);
 TOLUA_DEF(PW_MONSTER);
 TOLUA_DEF(PW_OBJECT);
 TOLUA_DEF(PW_DUNGEON);
 TOLUA_DEF(PW_SNAPSHOT);
 TOLUA_DEF(PW_VISIBLE);
 TOLUA_DEF(PW_BORG_1);
 TOLUA_DEF(PW_BORG_2);
 TOLUA_FUN(update_stuff,toluaI_ui_update_stuff00);
 TOLUA_FUN(redraw_stuff,toluaI_ui_redraw_stuff00);
 TOLUA_FUN(window_stuff,toluaI_ui_window_stuff00);
 TOLUA_FUN(handle_stuff,toluaI_ui_handle_stuff00);
 TOLUA_FUN(message_flush,toluaI_ui_message_flush00);
 TOLUA_FUN(msgf,toluaI_ui_msgf00);
 TOLUA_FUN(get_check,toluaI_ui_get_check00);
 TOLUA_FUN(sound,toluaI_ui_sound00);
 return 1;
}
/* Close function */
void tolua_ui_close (lua_State* tolua_S)
{
 TOLUA_UNDEF(TERM_DARK);
 TOLUA_UNDEF(TERM_WHITE);
 TOLUA_UNDEF(TERM_SLATE);
 TOLUA_UNDEF(TERM_ORANGE);
 TOLUA_UNDEF(TERM_RED);
 TOLUA_UNDEF(TERM_GREEN);
 TOLUA_UNDEF(TERM_BLUE);
 TOLUA_UNDEF(TERM_UMBER);
 TOLUA_UNDEF(TERM_L_DARK);
 TOLUA_UNDEF(TERM_L_WHITE);
 TOLUA_UNDEF(TERM_VIOLET);
 TOLUA_UNDEF(TERM_YELLOW);
 TOLUA_UNDEF(TERM_L_RED);
 TOLUA_UNDEF(TERM_L_GREEN);
 TOLUA_UNDEF(TERM_L_BLUE);
 TOLUA_UNDEF(TERM_L_UMBER);
 TOLUA_UNDEF(SOUND_NONE);
 TOLUA_UNDEF(SOUND_HIT);
 TOLUA_UNDEF(SOUND_MISS);
 TOLUA_UNDEF(SOUND_FLEE);
 TOLUA_UNDEF(SOUND_DROP);
 TOLUA_UNDEF(SOUND_KILL);
 TOLUA_UNDEF(SOUND_LEVEL);
 TOLUA_UNDEF(SOUND_DEATH);
 TOLUA_UNDEF(SOUND_STUDY);
 TOLUA_UNDEF(SOUND_TELEPORT);
 TOLUA_UNDEF(SOUND_SHOOT);
 TOLUA_UNDEF(SOUND_QUAFF);
 TOLUA_UNDEF(SOUND_ZAP);
 TOLUA_UNDEF(SOUND_WALK);
 TOLUA_UNDEF(SOUND_TPOTHER);
 TOLUA_UNDEF(SOUND_HITWALL);
 TOLUA_UNDEF(SOUND_EAT);
 TOLUA_UNDEF(SOUND_STORE1);
 TOLUA_UNDEF(SOUND_STORE2);
 TOLUA_UNDEF(SOUND_STORE3);
 TOLUA_UNDEF(SOUND_STORE4);
 TOLUA_UNDEF(SOUND_DIG);
 TOLUA_UNDEF(SOUND_OPENDOOR);
 TOLUA_UNDEF(SOUND_SHUTDOOR);
 TOLUA_UNDEF(SOUND_TPLEVEL);
 TOLUA_UNDEF(SOUND_SCROLL);
 TOLUA_UNDEF(SOUND_BUY);
 TOLUA_UNDEF(SOUND_SELL);
 TOLUA_UNDEF(SOUND_WARN);
 TOLUA_UNDEF(SOUND_ROCKET);
 TOLUA_UNDEF(SOUND_N_KILL);
 TOLUA_UNDEF(SOUND_U_KILL);
 TOLUA_UNDEF(SOUND_QUEST);
 TOLUA_UNDEF(SOUND_HEAL);
 TOLUA_UNDEF(SOUND_X_HEAL);
 TOLUA_UNDEF(SOUND_BITE);
 TOLUA_UNDEF(SOUND_CLAW);
 TOLUA_UNDEF(SOUND_M_SPELL);
 TOLUA_UNDEF(SOUND_SUMMON);
 TOLUA_UNDEF(SOUND_BREATH);
 TOLUA_UNDEF(SOUND_BALL);
 TOLUA_UNDEF(SOUND_M_HEAL);
 TOLUA_UNDEF(SOUND_ATK_SPELL);
 TOLUA_UNDEF(SOUND_EVIL);
 TOLUA_UNDEF(SOUND_TOUCH);
 TOLUA_UNDEF(SOUND_STING);
 TOLUA_UNDEF(SOUND_CRUSH);
 TOLUA_UNDEF(SOUND_SLIME);
 TOLUA_UNDEF(SOUND_WAIL);
 TOLUA_UNDEF(SOUND_WINNER);
 TOLUA_UNDEF(SOUND_FIRE);
 TOLUA_UNDEF(SOUND_ACID);
 TOLUA_UNDEF(SOUND_ELEC);
 TOLUA_UNDEF(SOUND_COLD);
 TOLUA_UNDEF(SOUND_ILLEGAL);
 TOLUA_UNDEF(SOUND_FAIL);
 TOLUA_UNDEF(SOUND_WAKEUP);
 TOLUA_UNDEF(SOUND_INVULN);
 TOLUA_UNDEF(SOUND_FALL);
 TOLUA_UNDEF(SOUND_PAIN);
 TOLUA_UNDEF(SOUND_DESTITEM);
 TOLUA_UNDEF(SOUND_MOAN);
 TOLUA_UNDEF(SOUND_SHOW);
 TOLUA_UNDEF(SOUND_UNUSED);
 TOLUA_UNDEF(SOUND_EXPLODE);
 TOLUA_UNDEF(SOUND_MAX);
 TOLUA_UNDEF(PU_BONUS);
 TOLUA_UNDEF(PU_TORCH);
 TOLUA_UNDEF(PU_HP);
 TOLUA_UNDEF(PU_MANA);
 TOLUA_UNDEF(PU_SPELLS);
 TOLUA_UNDEF(PU_VIEW);
 TOLUA_UNDEF(PU_MON_LITE);
 TOLUA_UNDEF(PU_MONSTERS);
 TOLUA_UNDEF(PU_DISTANCE);
 TOLUA_UNDEF(PU_FLOW);
 TOLUA_UNDEF(PR_MISC);
 TOLUA_UNDEF(PR_TITLE);
 TOLUA_UNDEF(PR_LEV);
 TOLUA_UNDEF(PR_EXP);
 TOLUA_UNDEF(PR_STATS);
 TOLUA_UNDEF(PR_ARMOR);
 TOLUA_UNDEF(PR_HP);
 TOLUA_UNDEF(PR_MANA);
 TOLUA_UNDEF(PR_GOLD);
 TOLUA_UNDEF(PR_DEPTH);
 TOLUA_UNDEF(PR_EQUIPPY);
 TOLUA_UNDEF(PR_HEALTH);
 TOLUA_UNDEF(PR_CUT);
 TOLUA_UNDEF(PR_STUN);
 TOLUA_UNDEF(PR_HUNGER);
 TOLUA_UNDEF(PR_STATUS);
 TOLUA_UNDEF(PR_BLIND);
 TOLUA_UNDEF(PR_CONFUSED);
 TOLUA_UNDEF(PR_AFRAID);
 TOLUA_UNDEF(PR_POISONED);
 TOLUA_UNDEF(PR_STATE);
 TOLUA_UNDEF(PR_SPEED);
 TOLUA_UNDEF(PR_STUDY);
 TOLUA_UNDEF(PR_EXTRA);
 TOLUA_UNDEF(PR_BASIC);
 TOLUA_UNDEF(PR_MAP);
 TOLUA_UNDEF(PR_WIPE);
 TOLUA_UNDEF(PW_INVEN);
 TOLUA_UNDEF(PW_EQUIP);
 TOLUA_UNDEF(PW_SPELL);
 TOLUA_UNDEF(PW_PLAYER);
 TOLUA_UNDEF(PW_SCRIPT_VARS);
 TOLUA_UNDEF(PW_SCRIPT_SOURCE);
 TOLUA_UNDEF(PW_MESSAGE);
 TOLUA_UNDEF(PW_OVERHEAD);
 TOLUA_UNDEF(PW_MONSTER);
 TOLUA_UNDEF(PW_OBJECT);
 TOLUA_UNDEF(PW_DUNGEON);
 TOLUA_UNDEF(PW_SNAPSHOT);
 TOLUA_UNDEF(PW_VISIBLE);
 TOLUA_UNDEF(PW_BORG_1);
 TOLUA_UNDEF(PW_BORG_2);
 TOLUA_UNDEF(update_stuff);
 TOLUA_UNDEF(redraw_stuff);
 TOLUA_UNDEF(window_stuff);
 TOLUA_UNDEF(handle_stuff);
 TOLUA_UNDEF(message_flush);
 TOLUA_UNDEF(msgf);
 TOLUA_UNDEF(get_check);
 TOLUA_UNDEF(sound);
}
