/**
 * \file list-ignore-types.h
 * \brief types of object used for ignoring by quality or ego
 */

/* index					description */
ITYPE(NONE,					"")
ITYPE(SHARP,				"Sharp Melee Weapons")
ITYPE(BLUNT,				"Blunt Melee Weapons")
ITYPE(GREAT,				"Great Weapons")
ITYPE(6MM,					"6mm guns")
ITYPE(9MM,					"9mm guns")
ITYPE(12MM,					"12mm guns")
ITYPE(AMMO_6,				"6mm ammo")
ITYPE(AMMO_9,				"9mm ammo")
ITYPE(AMMO_12,				"12mm ammo")
ITYPE(ROBE,					"Robes")
ITYPE(BODY_ARMOR,			"Body Armor")
ITYPE(BASIC_DRAGON_ARMOR,	"Basic Dragon Scale Mail")
ITYPE(MULTI_DRAGON_ARMOR,	"Multi-Hued Dragon Scale Mail")
ITYPE(HIGH_DRAGON_ARMOR,	"High Dragon Scale Mail")
ITYPE(BALANCE_DRAGON_ARMOR,	"Balance Dragon Scale Mail")
ITYPE(POWER_DRAGON_ARMOR,	"Power Dragon Scale Mail")
ITYPE(CLOAK,				"Cloaks")
ITYPE(ELVEN_CLOAK,			"Elven Cloaks")
ITYPE(BELT,					"Belts")
ITYPE(SHIELD,				"Shields")
ITYPE(HEADGEAR,				"Headgear")
ITYPE(HANDGEAR,				"Handgear")
ITYPE(FEET,					"Footgear")
ITYPE(DIGGER,				"Diggers")
ITYPE(RING,					"Rings")
ITYPE(AMULET,				"Amulets")
ITYPE(LIGHT, 				"Lights")
ITYPE(BLOCK,				"Blocks")
ITYPE(PRINTER,				"Printers")
