/**
 * \file list-tvals.h
 * \brief List of object base types
 */
/* string		name 			min randarts */
TV(NULL,		"none",			0)
TV(CHEST,		"chest",		0)
TV(AMMO_6,		"6mm ammo",		0)
TV(AMMO_9,		"9mm ammo",		0)
TV(AMMO_12,		"12mm ammo",	0)
TV(GUN,			"gun",			4)
TV(DIGGING,		"digger",		0)
TV(HAFTED,		"hafted",		5)
TV(POLEARM,		"polearm",		5)
TV(SWORD,		"sword",		5)
TV(BOOTS,		"boots",		4)
TV(GLOVES,		"gloves",		4)
TV(HELM,		"helm",			3)
TV(CROWN,		"crown",		1)
TV(SHIELD,		"shield",		4)
TV(CLOAK,		"cloak",		4)
TV(BELT,		"belt",			1)
TV(SOFT_ARMOR,	"soft armor",	2)
TV(HARD_ARMOR,	"hard armor",	2)
TV(DRAG_ARMOR,	"dragon armor",	1)
TV(LIGHT,		"light",		3)
TV(DEVICE,		"device",		0)
TV(WAND,		"wand",			0)
TV(GADGET,		"gadget",		0)
TV(CARD,		"card",			0)
TV(PILL,		"pill",			0)
TV(BATTERY,		"battery",		0)
TV(FOOD,		"food",			0)
TV(MUSHROOM,	"mushroom",		0)
TV(GOLD,		"cash",			0)
TV(BLOCK,		"block",		0)
TV(PRINTER,		"printer",		0)
TV(LEGS,		"legs",			0)
TV(ARMS,		"arms",			0)

