#define LOADSAVE_C
/* File: loadsave.c */

/* Purpose: interact with savefiles (auxiliary code) */

#include "angband.h"
#include "loadsave.h"

/*
 * Don't use hard-coded values for the version, so that the game can create
 * a save file as if it was an older version if desired.
 */
/*
 * Savefile version
 */
byte sf_major;			/* Savefile's "version_major" */
byte sf_minor;			/* Savefile's "version_minor" */
byte sf_patch;			/* Savefile's "version_patch" */
byte sf_extra;			/* Savefile's "version_extra" */

u16b sf_flags;			/* Savefile's "version flags" */

/*
 * Savefile information
 */
u32b sf_xtra;			/* Operating system info */
u32b sf_when;			/* Time when savefile created */
u16b sf_lives;			/* Number of past "lives" with this file */
u16b sf_saves;			/* Number of "saves" during this life */

/*
 * The table of version flags which alter the object table.
 * This is currently a flag, but may need to change to an index as the
 * save file version grows.
 */
static u32b object_version[] =
{
#ifdef SF_K_INFO_1
	SF_K_INFO_1,
#else
	0,
#endif
	0
};

/*
 * The table of object indices for the above indices in the same order.
 */
static s16b object_table[][2] =
{
	{OBJ_MAX_DISTRO,	525},
	{OBJ_NOTHING,	0},
	{OBJ_FOOD_BLINDNESS,	1},
	{OBJ_FOOD_PARANOIA,	2},
	{OBJ_FOOD_CONFUSION,	3},
	{OBJ_FOOD_HALLUCINATION,	4},
	{OBJ_FOOD_CURE_POISON,	5},
	{OBJ_FOOD_CURE_BLINDNESS,	6},
	{OBJ_FOOD_CURE_PARANOIA,	7},
	{OBJ_FOOD_CURE_CONFUSION,	8},
	{OBJ_FOOD_DEC_STR,	9},
	{OBJ_FOOD_UNHEALTH,	10},
	{OBJ_FOOD_RES_CON,	11},
	{OBJ_FOOD_RESTORING,	12},
	{OBJ_FOOD_DEC_INT,	13},
	{OBJ_FOOD_DEC_WIS,	14},
	{OBJ_FOOD_POISON,	15},
	{OBJ_FOOD_SICKNESS,	16},
	{OBJ_FOOD_PARALYSIS,	17},
	{OBJ_FOOD_RES_STR,	18},
	{OBJ_FOOD_DISEASE,	19},
	{OBJ_FOOD_CURE_SERIOUS,	20},
	{OBJ_RATION_OF_FOOD,	21},
	{OBJ_HARD_BISCUIT,	22},
	{OBJ_STRIP_OF_VENISON,	23},
	{OBJ_SLIME_MOLD,	24},
	{OBJ_PIECE_OF_ELVISH_WAYBREAD,	25},
	{OBJ_PINT_OF_FINE_ALE,	26},
	{OBJ_BOTTLE_OF_FINE_WINE,	27},
	{OBJ_UNKNOWN,	28},
	{OBJ_BROKEN_DAGGER,	30},
	{OBJ_BASTARD_SWORD,	31},
	{OBJ_SCIMITAR,	32},
	{OBJ_TULWAR,	33},
	{OBJ_BROAD_SWORD,	34},
	{OBJ_SHORT_SWORD,	35},
	{OBJ_BLADE_OF_CHAOS,	36},
	{OBJ_TWO_HANDED_SWORD,	37},
	{OBJ_MAIN_GAUCHE,	38},
	{OBJ_CUTLASS,	39},
	{OBJ_EXECUTIONERS_SWORD,	40},
	{OBJ_KATANA,	41},
	{OBJ_LONG_SWORD,	42},
	{OBJ_DAGGER,	43},
	{OBJ_RAPIER,	44},
	{OBJ_SABRE,	45},
	{OBJ_SMALL_SWORD,	46},
	{OBJ_BROKEN_SWORD,	47},
	{OBJ_BALL_AND_CHAIN,	48},
	{OBJ_WHIP,	49},
	{OBJ_FLAIL,	50},
	{OBJ_TWO_HANDED_FLAIL,	51},
	{OBJ_MORNING_STAR,	52},
	{OBJ_MACE,	53},
	{OBJ_QUARTERSTAFF,	54},
	{OBJ_WAR_HAMMER,	55},
	{OBJ_LEAD_FILLED_MACE,	56},
	{OBJ_MACE_OF_DISRUPTION,	57},
	{OBJ_LUCERNE_HAMMER,	58},
	{OBJ_BEAKED_AXE,	59},
	{OBJ_GLAIVE,	60},
	{OBJ_HALBERD,	61},
	{OBJ_AWL_PIKE,	62},
	{OBJ_PIKE,	63},
	{OBJ_SPEAR,	64},
	{OBJ_TRIDENT,	65},
	{OBJ_LANCE,	66},
	{OBJ_GREAT_AXE,	67},
	{OBJ_BATTLE_AXE,	68},
	{OBJ_LOCHABER_AXE,	69},
	{OBJ_BROAD_AXE,	70},
	{OBJ_SCYTHE,	71},
	{OBJ_SCYTHE_OF_SLICING,	72},
	{OBJ_SHORT_BOW,	73},
	{OBJ_LONG_BOW,	74},
	{OBJ_LIGHT_CROSSBOW,	75},
	{OBJ_HEAVY_CROSSBOW,	76},
	{OBJ_SLING,	77},
	{OBJ_ARROW,	78},
	{OBJ_SEEKER_ARROW,	79},
	{OBJ_BOLT,	80},
	{OBJ_SEEKER_BOLT,	81},
	{OBJ_ROUNDED_PEBBLE,	82},
	{OBJ_IRON_SHOT,	83},
	{OBJ_SHOVEL,	84},
	{OBJ_GNOMISH_SHOVEL,	85},
	{OBJ_DWARVEN_SHOVEL,	86},
	{OBJ_PICK,	87},
	{OBJ_ORCISH_PICK,	88},
	{OBJ_DWARVEN_PICK,	89},
	{OBJ_ELVEN_CLOAK,	90},
	{OBJ_SOFT_LEATHER_BOOTS,	91},
	{OBJ_HARD_LEATHER_BOOTS,	92},
	{OBJ_METAL_SHOD_BOOTS,	93},
	{OBJ_HARD_LEATHER_CAP,	94},
	{OBJ_METAL_CAP,	95},
	{OBJ_IRON_HELM,	96},
	{OBJ_STEEL_HELM,	97},
	{OBJ_IRON_CROWN,	98},
	{OBJ_GOLDEN_CROWN,	99},
	{OBJ_JEWEL_ENCRUSTED_CROWN,	100},
	{OBJ_ROBE,	101},
	{OBJ_FILTHY_RAG,	102},
	{OBJ_SOFT_LEATHER_ARMOUR,	103},
	{OBJ_SOFT_STUDDED_LEATHER,	104},
	{OBJ_HARD_LEATHER_ARMOUR,	105},
	{OBJ_HARD_STUDDED_LEATHER,	106},
	{OBJ_LEATHER_SCALE_MAIL,	107},
	{OBJ_METAL_SCALE_MAIL,	108},
	{OBJ_CHAIN_MAIL,	109},
	{OBJ_RUSTY_CHAIN_MAIL,	110},
	{OBJ_AUGMENTED_CHAIN_MAIL,	111},
	{OBJ_BAR_CHAIN_MAIL,	112},
	{OBJ_METAL_BRIGANDINE_ARMOUR,	113},
	{OBJ_PARTIAL_PLATE_ARMOUR,	114},
	{OBJ_METAL_LAMELLAR_ARMOUR,	115},
	{OBJ_FULL_PLATE_ARMOUR,	116},
	{OBJ_RIBBED_PLATE_ARMOUR,	117},
	{OBJ_ADAMANTITE_PLATE_MAIL,	118},
	{OBJ_MITHRIL_PLATE_MAIL,	119},
	{OBJ_MITHRIL_CHAIN_MAIL,	120},
	{OBJ_DOUBLE_CHAIN_MAIL,	121},
	{OBJ_SHIELD_OF_DEFLECTION,	122},
	{OBJ_CLOAK,	123},
	{OBJ_SHADOW_CLOAK,	124},
	{OBJ_LEATHER_GLOVES,	125},
	{OBJ_GAUNTLETS,	126},
	{OBJ_CESTI,	127},
	{OBJ_SMALL_LEATHER_SHIELD,	128},
	{OBJ_LARGE_LEATHER_SHIELD,	129},
	{OBJ_SMALL_METAL_SHIELD,	130},
	{OBJ_LARGE_METAL_SHIELD,	131},
	{OBJ_RING_INC_STR,	132},
	{OBJ_RING_INC_DEX,	133},
	{OBJ_RING_INC_CON,	134},
	{OBJ_RING_INC_INT,	135},
	{OBJ_RING_SPEED,	136},
	{OBJ_RING_SEARCHING,	137},
	{OBJ_RING_TELEPORTATION,	138},
	{OBJ_RING_SLOW_DIGESTION,	139},
	{OBJ_RING_RES_FIRE,	140},
	{OBJ_RING_RES_COLD,	141},
	{OBJ_RING_LEVITATION,	142},
	{OBJ_RING_RES_POISON,	143},
	{OBJ_RING_FREE_ACTION,	144},
	{OBJ_RING_DEC_STR,	145},
	{OBJ_RING_FIRE,	146},
	{OBJ_RING_ACID,	147},
	{OBJ_RING_ICE,	148},
	{OBJ_RING_WOE,	149},
	{OBJ_RING_DEC_INT,	150},
	{OBJ_RING_DAMAGE,	151},
	{OBJ_RING_ACCURACY,	152},
	{OBJ_RING_PROTECTION,	153},
	{OBJ_RING_AGGRAVATE_MONSTER,	154},
	{OBJ_RING_SEE_INVIS,	155},
	{OBJ_RING_SUSTAIN_STR,	156},
	{OBJ_RING_SUSTAIN_INT,	157},
	{OBJ_RING_SUSTAIN_WIS,	158},
	{OBJ_RING_SUSTAIN_CON,	159},
	{OBJ_RING_SUSTAIN_DEX,	160},
	{OBJ_RING_SUSTAIN_CHR,	161},
	{OBJ_RING_SLAYING,	162},
	{OBJ_AMULET_BRILLIANCE,	163},
	{OBJ_AMULET_INC_CHR,	164},
	{OBJ_AMULET_SEARCHING,	165},
	{OBJ_AMULET_TELEPORTATION,	166},
	{OBJ_AMULET_SLOW_DIGESTION,	167},
	{OBJ_AMULET_RES_ACID,	168},
	{OBJ_AMULET_ADORNMENT,	169},
	{OBJ_AMULET_THE_MAGI,	171},
	{OBJ_AMULET_DOOM,	172},
	{OBJ_SCROLL_ENCHANT_WEAPON_TO_HIT,	173},
	{OBJ_SCROLL_ENCHANT_WEAPON_TO_DAM,	174},
	{OBJ_SCROLL_ENCHANT_ARMOUR,	175},
	{OBJ_SCROLL_IDENTIFY,	176},
	{OBJ_SCROLL_STAR_IDENTIFY,	177},
	{OBJ_SCROLL_RUMOUR,	178},
	{OBJ_SCROLL_CHAOS,	179},
	{OBJ_SCROLL_REMOVE_CURSE,	180},
	{OBJ_SCROLL_LIGHT,	181},
	{OBJ_SCROLL_FIRE,	182},
	{OBJ_SCROLL_ICE,	183},
	{OBJ_SCROLL_SUMMON_MONSTER,	184},
	{OBJ_SCROLL_PHASE_DOOR,	185},
	{OBJ_SCROLL_TELEPORTATION,	186},
	{OBJ_SCROLL_TELEPORT_LEVEL,	187},
	{OBJ_SCROLL_MONSTER_CONFUSION,	188},
	{OBJ_SCROLL_MAGIC_MAPPING,	189},
	{OBJ_SCROLL_RUNE_OF_PROTECTION,	190},
	{OBJ_SCROLL_STAR_REMOVE_CURSE,	191},
	{OBJ_SCROLL_TREASURE_DETECTION,	192},
	{OBJ_SCROLL_OBJECT_DETECTION,	193},
	{OBJ_SCROLL_TRAP_DETECTION,	194},
	{OBJ_SCROLL_DOOR_STAIR_LOCATION,	197},
	{OBJ_SCROLL_ACQUIREMENT,	198},
	{OBJ_SCROLL_STAR_ACQUIREMENT,	199},
	{OBJ_SCROLL_MASS_GENOCIDE,	200},
	{OBJ_SCROLL_DETECT_INVIS,	201},
	{OBJ_SCROLL_AGGRAVATE_MONSTER,	202},
	{OBJ_SCROLL_TRAP_CREATION,	203},
	{OBJ_SCROLL_TRAP_DOOR_DESTRUCTION,	204},
	{OBJ_SCROLL_ARTIFACT_CREATION,	205},
	{OBJ_SCROLL_RECHARGING,	206},
	{OBJ_SCROLL_GENOCIDE,	207},
	{OBJ_SCROLL_DARKNESS,	208},
	{OBJ_SCROLL_PROTECTION_FROM_EVIL,	209},
	{OBJ_SCROLL_SATISFY_HUNGER,	210},
	{OBJ_SCROLL_DISPEL_UNDEAD,	211},
	{OBJ_SCROLL_STAR_ENCHANT_WEAPON,	212},
	{OBJ_SCROLL_CURSE_WEAPON,	213},
	{OBJ_SCROLL_STAR_ENCHANT_ARMOUR,	214},
	{OBJ_SCROLL_CURSE_ARMOUR,	215},
	{OBJ_SCROLL_SUMMON_UNDEAD,	216},
	{OBJ_SCROLL_BLESSING,	217},
	{OBJ_SCROLL_HOLY_CHANT,	218},
	{OBJ_SCROLL_HOLY_PRAYER,	219},
	{OBJ_SCROLL_WORD_OF_RECALL,	220},
	{OBJ_SCROLL_STAR_DESTRUCTION,	221},
	{OBJ_POTION_SLIME_MOLD_JUICE,	222},
	{OBJ_POTION_APPLE_JUICE,	223},
	{OBJ_POTION_WATER,	224},
	{OBJ_POTION_INC_STR,	225},
	{OBJ_POTION_DEC_STR,	226},
	{OBJ_POTION_RES_STR,	227},
	{OBJ_POTION_INC_INT,	228},
	{OBJ_POTION_DEC_INT,	229},
	{OBJ_POTION_RES_INT,	230},
	{OBJ_POTION_INC_WIS,	231},
	{OBJ_POTION_DEC_WIS,	232},
	{OBJ_POTION_RES_WIS,	233},
	{OBJ_POTION_INC_CHR,	234},
	{OBJ_POTION_DEC_CHR,	235},
	{OBJ_POTION_RES_CHR,	236},
	{OBJ_POTION_CURING,	237},
	{OBJ_POTION_INVULNERABILITY,	238},
	{OBJ_POTION_NEW_LIFE,	239},
	{OBJ_POTION_CURE_SERIOUS,	240},
	{OBJ_POTION_CURE_CRITICAL,	241},
	{OBJ_POTION_HEALING,	242},
	{OBJ_POTION_INC_CON,	243},
	{OBJ_POTION_EXPERIENCE,	244},
	{OBJ_POTION_SLEEP,	245},
	{OBJ_POTION_BLINDNESS,	246},
	{OBJ_POTION_BOOZE,	247},
	{OBJ_POTION_POISON,	248},
	{OBJ_POTION_SPEED,	249},
	{OBJ_POTION_SLOWNESS,	250},
	{OBJ_POTION_INC_DEX,	251},
	{OBJ_POTION_RES_DEX,	252},
	{OBJ_POTION_RES_CON,	253},
	{OBJ_POTION_LOSE_MEMORIES,	254},
	{OBJ_POTION_SALT_WATER,	255},
	{OBJ_POTION_ENLIGHTENMENT,	256},
	{OBJ_POTION_HEROISM,	257},
	{OBJ_POTION_BERSERK_STR,	258},
	{OBJ_POTION_BOLDNESS,	259},
	{OBJ_POTION_RES_LIFE_LEVELS,	260},
	{OBJ_POTION_RES_HEAT,	261},
	{OBJ_POTION_RES_COLD,	262},
	{OBJ_POTION_DETECT_INVIS,	263},
	{OBJ_POTION_SLOW_POISON,	264},
	{OBJ_POTION_NEUTRALIZE_POISON,	265},
	{OBJ_POTION_RES_MANA,	266},
	{OBJ_POTION_INFRA_VISION,	267},
	{OBJ_POTION_RESISTANCE,	268},
	{OBJ_WAND_LIGHT,	269},
	{OBJ_WAND_TAME_MONSTER,	270},
	{OBJ_WAND_COLD_BOLT,	271},
	{OBJ_WAND_FIRE_BOLT,	272},
	{OBJ_WAND_STONE_TO_MUD,	273},
	{OBJ_WAND_POLYMORPH,	274},
	{OBJ_WAND_HEAL_MONSTER,	275},
	{OBJ_WAND_HASTE_MONSTER,	276},
	{OBJ_WAND_SLOW_MONSTER,	277},
	{OBJ_WAND_CONFUSE_MONSTER,	278},
	{OBJ_WAND_SLEEP_MONSTER,	279},
	{OBJ_WAND_DRAIN_LIFE,	280},
	{OBJ_WAND_TRAP_DOOR_DESTRUCTION,	281},
	{OBJ_WAND_MAGIC_MISSILE,	282},
	{OBJ_WAND_CLONE_MONSTER,	283},
	{OBJ_WAND_SCARE_MONSTER,	284},
	{OBJ_WAND_TELEPORT_OTHER,	285},
	{OBJ_WAND_DISARMING,	286},
	{OBJ_WAND_ELEC_BALL,	287},
	{OBJ_WAND_COLD_BALL,	288},
	{OBJ_WAND_FIRE_BALL,	289},
	{OBJ_WAND_STINKING_CLOUD,	290},
	{OBJ_WAND_ACID_BALL,	291},
	{OBJ_WAND_WONDER,	292},
	{OBJ_WAND_ACID_BOLT,	294},
	{OBJ_WAND_DRAGON_FIRE,	295},
	{OBJ_WAND_DRAGON_COLD,	296},
	{OBJ_WAND_DRAGON_BREATH,	297},
	{OBJ_WAND_ANNIHILATION,	298},
	{OBJ_WAND_SHARD_BALL,	299},
	{OBJ_STAFF_TRAP_LOCATION,	300},
	{OBJ_STAFF_TREASURE_LOCATION,	301},
	{OBJ_STAFF_OBJECT_LOCATION,	302},
	{OBJ_STAFF_TELEPORTATION,	303},
	{OBJ_STAFF_EARTHQUAKES,	304},
	{OBJ_STAFF_SUMMONING,	305},
	{OBJ_STAFF_LIGHT,	306},
	{OBJ_STAFF_STAR_DESTRUCTION,	307},
	{OBJ_STAFF_STARLIGHT,	308},
	{OBJ_STAFF_HASTE_MONSTERS,	309},
	{OBJ_STAFF_SLOW_MONSTERS,	310},
	{OBJ_STAFF_SLEEP_MONSTERS,	311},
	{OBJ_STAFF_CURE_LIGHT,	312},
	{OBJ_STAFF_DETECT_INVIS,	313},
	{OBJ_STAFF_SPEED,	314},
	{OBJ_STAFF_SLOWNESS,	315},
	{OBJ_STAFF_DOOR_STAIR_LOCATION,	316},
	{OBJ_STAFF_REMOVE_CURSE,	317},
	{OBJ_STAFF_DETECT_EVIL,	318},
	{OBJ_STAFF_CURING,	319},
	{OBJ_STAFF_DISPEL_EVIL,	320},
	{OBJ_STAFF_PROBING,	321},
	{OBJ_STAFF_DARKNESS,	322},
	{OBJ_STAFF_GENOCIDE,	323},
	{OBJ_STAFF_POWER,	324},
	{OBJ_STAFF_THE_MAGI,	325},
	{OBJ_STAFF_PERCEPTION,	326},
	{OBJ_STAFF_HOLINESS,	327},
	{OBJ_STAFF_ENLIGHTENMENT,	328},
	{OBJ_STAFF_HEALING,	329},
	{OBJ_SORCERY_BEGINNERS_HANDBOOK,	334},
	{OBJ_SORCERY_MASTER_SORCERERS_HANDBOOK,	335},
	{OBJ_SORCERY_RLYEH_TEXT,	336},
	{OBJ_SORCERY_UNAUSPRECHLICHEN_KULTEN,	337},
	{OBJ_SMALL_WOODEN_CHEST,	338},
	{OBJ_LARGE_WOODEN_CHEST,	339},
	{OBJ_SMALL_IRON_CHEST,	340},
	{OBJ_LARGE_IRON_CHEST,	341},
	{OBJ_SMALL_STEEL_CHEST,	342},
	{OBJ_LARGE_STEEL_CHEST,	343},
	{OBJ_RUINED_CHEST,	344},
	{OBJ_IRON_SPIKE,	345},
	{OBJ_WOODEN_TORCH,	346},
	{OBJ_BRASS_LANTERN,	347},
	{OBJ_FLASK_OF_OIL,	348},
	{OBJ_EMPTY_BOTTLE,	349},
	{OBJ_ROD_HAVOC,	350},
	{OBJ_ROD_DOOR_STAIR_LOCATION,	351},
	{OBJ_ROD_TRAP_LOCATION,	352},
	{OBJ_ROD_PROBING,	353},
	{OBJ_ROD_RECALL,	354},
	{OBJ_ROD_ILLUMINATION,	355},
	{OBJ_ROD_LIGHT,	356},
	{OBJ_ROD_ELEC_BOLT,	357},
	{OBJ_ROD_COLD_BOLT,	358},
	{OBJ_ROD_FIRE_BOLT,	359},
	{OBJ_ROD_POLYMORPH,	360},
	{OBJ_ROD_SLOW_MONSTER,	361},
	{OBJ_ROD_SLEEP_MONSTER,	362},
	{OBJ_ROD_DRAIN_LIFE,	363},
	{OBJ_ROD_TELEPORT_OTHER,	364},
	{OBJ_ROD_DISARMING,	365},
	{OBJ_ROD_ELEC_BALL,	366},
	{OBJ_ROD_COLD_BALL,	367},
	{OBJ_ROD_FIRE_BALL,	368},
	{OBJ_ROD_ACID_BALL,	369},
	{OBJ_ROD_ACID_BOLT,	370},
	{OBJ_ROD_ENLIGHTENMENT,	371},
	{OBJ_ROD_PERCEPTION,	372},
	{OBJ_ROD_CURING,	373},
	{OBJ_ROD_HEALING,	374},
	{OBJ_ROD_DETECTION,	375},
	{OBJ_ROD_RESTORATION,	376},
	{OBJ_ROD_SPEED,	377},
	{OBJ_LUMP_OF_SULPHUR,	378},
	{OBJ_HEMLOCK_TWIG,	379},
	{OBJ_SILVER_UNICORN_HORN,	380},
	{OBJ_CRYSTAL,	381},
	{OBJ_FLY_AGARIC_TOADSTOOL,	382},
	{OBJ_CLOVE_OF_GARLIC,	383},
	{OBJ_GEODE,	384},
	{OBJ_THAUMATURGY_SIGN_OF_CHAOS,	385},
	{OBJ_THAUMATURGY_CHAOS_MASTERY,	386},
	{OBJ_THAUMATURGY_THE_KING_IN_YELLOW,	387},
	{OBJ_THAUMATURGY_REVELATIONS_OF_GLAAKI,	388},
	{OBJ_SHARD_OF_POTTERY,	389},
	{OBJ_BROKEN_STICK,	390},
	{OBJ_BROKEN_SKULL,	391},
	{OBJ_BROKEN_BONE,	392},
	{OBJ_CANINE_SKELETON,	393},
	{OBJ_RODENT_SKELETON,	394},
	{OBJ_HUMAN_SKELETON,	395},
	{OBJ_DWARF_SKELETON,	396},
	{OBJ_ELF_SKELETON,	397},
	{OBJ_GNOME_SKELETON,	398},
	{OBJ_DSM_BLACK,	400},
	{OBJ_DSM_BLUE,	401},
	{OBJ_DSM_WHITE,	402},
	{OBJ_DSM_RED,	403},
	{OBJ_DSM_GREEN,	404},
	{OBJ_DSM_MULTI_HUED,	405},
	{OBJ_DSM_PSEUDO,	406},
	{OBJ_DSM_LAW,	407},
	{OBJ_DSM_BRONZE,	408},
	{OBJ_DSM_GOLD,	409},
	{OBJ_DSM_CHAOS,	410},
	{OBJ_DSM_BALANCE,	411},
	{OBJ_DSM_POWER,	412},
	{OBJ_DRAGON_HELM,	413},
	{OBJ_DRAGON_SHIELD,	414},
	{OBJ_POTION_IOCAINE,	415},
	{OBJ_POTION_RUINATION,	416},
	{OBJ_POTION_DETONATIONS,	417},
	{OBJ_POTION_AUGMENTATION,	418},
	{OBJ_POTION_STAR_HEALING,	419},
	{OBJ_POTION_LIFE,	420},
	{OBJ_POTION_SELF_KNOWLEDGE,	421},
	{OBJ_POTION_STAR_ENLIGHTENMENT,	422},
	{OBJ_RING_RES_FEAR,	425},
	{OBJ_RING_RES_LIGHT_AND_DARKNESS,	426},
	{OBJ_RING_RES_NETHER,	427},
	{OBJ_RING_RES_NEXUS,	428},
	{OBJ_RING_RES_SOUND,	429},
	{OBJ_RING_RES_CONFUSION,	430},
	{OBJ_RING_RES_SHARD,	431},
	{OBJ_RING_RES_DISENCHANTMENT,	432},
	{OBJ_RING_RES_CHAOS,	433},
	{OBJ_RING_RES_BLINDNESS,	434},
	{OBJ_RING_LORDLY_PROTECTION,	435},
	{OBJ_RING_EXTRA_ATTACKS,	436},
	{OBJ_POTION_CURE_LIGHT,	437},
	{OBJ_POTION_DEC_DEX,	438},
	{OBJ_POTION_DEC_CON,	439},
	{OBJ_COPPER,	480},
	{OBJ_COPPER_2,	481},
	{OBJ_COPPER_3,	482},
	{OBJ_SILVER,	483},
	{OBJ_SILVER_2,	484},
	{OBJ_SILVER_3,	485},
	{OBJ_GARNETS,	486},
	{OBJ_GARNETS_2,	487},
	{OBJ_GOLD,	488},
	{OBJ_GOLD_2,	489},
	{OBJ_GOLD_3,	490},
	{OBJ_OPALS,	491},
	{OBJ_SAPPHIRES,	492},
	{OBJ_RUBIES,	493},
	{OBJ_DIAMONDS,	494},
	{OBJ_EMERALDS,	495},
	{OBJ_MITHRIL,	496},
	{OBJ_ADAMANTITE,	497},
	{OBJ_MIGHTY_HAMMER_OF_WORLDS,	498},
	{OBJ_LEAD_CROWN_OF_THE_UNIVERSE,	499},
	{OBJ_STAR_ESSENCE_OF_POLARIS,	500},
	{OBJ_STAR_ESSENCE_OF_XOTH,	501},
	{OBJ_GEMSTONE_TRAPEZODEDRON,	502},
	{OBJ_AMULET_LOBON,	503},
	{OBJ_AMULET_ABD_ALHAZRED,	504},
	{OBJ_NECKLACE_OF_THE_DWARVES,	505},
	{OBJ_RING_MAGIC,	506},
	{OBJ_RING_BAST,	507},
	{OBJ_RING_ELEMENTAL_POWER_FIRE,	508},
	{OBJ_RING_ELEMENTAL_POWER_ICE,	509},
	{OBJ_RING_ELEMENTAL_POWER_STORM,	510},
	{OBJ_RING_NYARLATHOTEP,	511},
	{OBJ_CONJURATION_MINOR_CONJURINGS,	512},
	{OBJ_CONJURATION_CONJURING_MASTERY,	513},
	{OBJ_CONJURATION_BOOK_OF_EIBON,	514},
	{OBJ_CONJURATION_LIBER_IVONIS,	515},
	{OBJ_NECROMANCY_BLACK_PRAYERS,	516},
	{OBJ_NECROMANCY_BLACK_MASS,	517},
	{OBJ_NECROMANCY_NECRONOMICON,	518},
	{OBJ_NECROMANCY_KITAB_AL_AZIF,	519},
	{OBJ_AMULET_REFLECTION,	520},
	{OBJ_AMULET_ANTI_MAGIC,	521},
	{OBJ_AMULET_ANTI_TELEPORTATION,	522},
	{OBJ_AMULET_RESISTANCE,	523},
	{OBJ_RUNESWORD_STORMBRINGER,	524},
	{OBJ_NO_TEA,	525},
};

static u32b monster_version[] =
{
#ifdef SF_R_INFO_1
	SF_R_INFO_1,
#else
	0,
#endif
	0
};
static s16b monster_table[][2] =
{
	{MON_PLAYER,	0},
	{MON_NOBODY_THE_UNNAMED_GHOST______________________________________,	576},
#ifdef SF_R_INFO_1
	{MON_POISON, -1},
	{MON_LIGHT, -1},
	{MON_TRAP, -1},
	{MON_CHAOS_PATRON, -1},
	{MON_CASTING_GENOCIDE, -1},
	{MON_CASTING_MASS_GENOCIDE, -1},
	{MON_CALLING_THE_VOID, -1},
	{MON_CASTING_HELLFIRE, -1},
	{MON_EARTHQUAKE, -1},
	{MON_CORRUPT_PATTERN, -1},
	{MON_PATTERN, -1},
	{MON_SOLID_ROCK, -1},
	{MON_BLEEDING, -1},
	{MON_STARVATION, -1},
	{MON_DANGEROUS_EQUIPMENT, -1},
	{MON_DANGEROUS_MUTATION, -1},
	{MON_POISONOUS_FOOD, -1},
	{MON_HARMFUL_POTION, -1},
	{MON_HARMFUL_SCROLL, -1},
	{MON_CONCENTRATING_TOO_HARD, -1},
	{MON_FATAL_POLYMORPH, -1},
	{MON_SUICIDE, -1},
	{MON_G_THE_SKELETON_RACE, -1},
	{MON_G_THE_ZOMBIFIED_RACE, -1},
	{MON_G_THE_MUMMIFIED_RACE, -1},
	{MON_G_THE_POLTERGEIST, -1},
	{MON_G_THE_SPIRIT, -1},
	{MON_G_THE_GHOST, -1},
	{MON_G_THE_VAMPIRE, -1},
	{MON_G_THE_WRAITH, -1},
	{MON_G_THE_VAMPIRE_LORD, -1},
	{MON_G_THE_GHOST_2, -1},
	{MON_G_THE_GHOST_3, -1},
	{MON_G_THE_LICH, -1},
	{MON_G_THE_GHOST_4, -1},
#endif
	{MON_FILTHY_STREET_URCHIN,	1},
	{MON_SCRAWNY_CAT,	2},
	{MON_SCRUFFY_LITTLE_DOG,	3},
	{MON_FARMER_MAGGOT,	4},
	{MON_SMALL_CHILD,	5},
	{MON_HOBO,	6},
	{MON_RAVING_LUNATIC,	7},
	{MON_PITIFUL_LOOKING_BEGGAR,	8},
	{MON_MANGY_LOOKING_LEPER,	9},
	{MON_AGENT_OF_BLACK_MARKET,	10},
	{MON_SINGING_HAPPY_DRUNK,	11},
	{MON_AIMLESS_LOOKING_MERCHANT,	12},
	{MON_MEAN_LOOKING_MERCENARY,	13},
	{MON_BATTLE_SCARRED_VETERAN,	14},
	{MON_FOOLHARDY_ADOLESCENT,	15},
	{MON_GREY_MOLD,	16},
	{MON_BLINKING_DOT,	17},
	{MON_NEWT,	18},
	{MON_GIANT_WHITE_CENTIPEDE,	19},
	{MON_TOWNSMAN_OF_IB,	20},
	{MON_MAGICIAN_OF_IB,	21},
	{MON_GIANT_WHITE_MOUSE,	22},
	{MON_LARGE_BROWN_SNAKE,	23},
	{MON_SMALL_KOBOLD,	24},
	{MON_KOBOLD,	25},
	{MON_WHITE_WORM_MASS,	26},
	{MON_FLOATING_EYE,	27},
	{MON_ROCK_LIZARD,	28},
	{MON_GRID_BUG,	29},
	{MON_JACKAL,	30},
	{MON_SOLDIER_ANT,	31},
	{MON_FRUIT_BAT,	32},
	{MON_REDWEED,	33},
	{MON_SHRIEKER_MUSHROOM_PATCH,	34},
	{MON_THIEF_OF_IB,	35},
	{MON_METALLIC_GREEN_CENTIPEDE,	36},
	{MON_NOVICE_WARRIOR,	37},
	{MON_NOVICE_ROGUE,	38},
	{MON_NOVICE_SHAMAN,	39},
	{MON_NOVICE_WIZARD,	40},
	{MON_YELLOW_MUSHROOM_PATCH,	41},
	{MON_WHITE_JELLY,	42},
	{MON_GIANT_BLACK_ANT,	43},
	{MON_SALAMANDER,	44},
	{MON_WHITE_HARPY,	45},
	{MON_BLUE_YEEK,	46},
	{MON_GRIP_FARMER_MAGGOTS_DOG,	47},
	{MON_FANG_FARMER_MAGGOTS_DOG,	48},
	{MON_KING_RAT,	49},
	{MON_GREEN_WORM_MASS,	50},
	{MON_LARGE_YELLOW_SNAKE,	51},
	{MON_CAVE_SPIDER,	52},
	{MON_WILD_CAT,	53},
	{MON_SMEAGOL,	54},
	{MON_GREEN_OOZE,	55},
	{MON_POLTERGEIST,	56},
	{MON_METALLIC_BLUE_CENTIPEDE,	57},
	{MON_GIANT_WHITE_LOUSE,	58},
	{MON_BLACK_NAGA,	59},
	{MON_SPOTTED_MUSHROOM_PATCH,	60},
	{MON_SILVER_JELLY,	61},
	{MON_SCRUFFY_LOOKING_HOBBIT,	62},
	{MON_GIANT_WHITE_ANT,	63},
	{MON_YELLOW_MOLD,	64},
	{MON_METALLIC_RED_CENTIPEDE,	65},
	{MON_YELLOW_WORM_MASS,	66},
	{MON_CLEAR_WORM_MASS,	67},
	{MON_RADIATION_EYE,	68},
	{MON_CAVE_LIZARD,	69},
	{MON_NOVICE_RANGER,	70},
	{MON_BLUE_JELLY,	71},
	{MON_CREEPING_COPPER_COINS,	72},
	{MON_GIANT_WHITE_RAT,	73},
	{MON_BLUE_WORM_MASS,	74},
	{MON_LARGE_GREY_SNAKE,	75},
	{MON_WILD_MAN,	76},
	{MON_NOVICE_WIZARD_2,	77},
	{MON_GREEN_NAGA,	78},
	{MON_BLUE_OOZE,	79},
	{MON_GREEN_GLUTTON_GHOST,	80},
	{MON_GREEN_JELLY,	81},
	{MON_LARGE_KOBOLD,	82},
	{MON_SOLDIER_OF_IB,	83},
	{MON_DISENCHANTER_EYE,	84},
	{MON_RED_WORM_MASS,	85},
	{MON_COPPERHEAD_SNAKE,	86},
	{MON_DEATH_SWORD,	87},
	{MON_PURPLE_MUSHROOM_PATCH,	88},
	{MON_NOVICE_SHAMAN_2,	89},
	{MON_NOVICE_WARRIOR_2,	90},
	{MON_NIBELUNG,	91},
	{MON_THE_DISEMBODIED_HAND,	92},
	{MON_BROWN_MOLD,	93},
	{MON_GIANT_BROWN_BAT,	94},
	{MON_NOVICE_ARCHER,	95},
	{MON_CREEPING_SILVER_COINS,	96},
	{MON_SNAGA,	97},
	{MON_RATTLESNAKE,	98},
	{MON_CRYPT_CREEP,	99},
	{MON_ROTTING_CORPSE,	100},
	{MON_CAVE_ORC,	101},
	{MON_WOOD_SPIDER,	102},
	{MON_MANES,	103},
	{MON_BLOODSHOT_EYE,	104},
	{MON_RED_NAGA,	105},
	{MON_RED_JELLY,	106},
	{MON_ALCHEMIST_OF_IB,	107},
	{MON_LOST_SOUL,	108},
	{MON_NIGHT_LIZARD,	109},
	{MON_VORT_THE_KOBOLD_QUEEN,	110},
	{MON_WORMTONGUE_AGENT_OF_SARUMAN,	111},
	{MON_ROBIN_HOOD_THE_OUTLAW,	112},
	{MON_LAGDUF_THE_SNAGA,	113},
	{MON_BROWN_YEEK,	114},
	{MON_NOVICE_RANGER_2,	115},
	{MON_GIANT_SALAMANDER,	116},
	{MON_GAPING_MAW,	117},
	{MON_GREEN_MOLD,	118},
	{MON_NOVICE_PALADIN,	119},
	{MON_LEMURE,	120},
	{MON_HILL_ORC,	121},
	{MON_BANDIT,	122},
	{MON_HUNTING_HAWK,	123},
	{MON_PHANTOM_WARRIOR,	124},
	{MON_GREMLIN,	125},
	{MON_YETI,	126},
	{MON_CURSED_ONE_OF_IB,	127},
	{MON_GIANT_GREY_RAT,	128},
	{MON_BLACK_HARPY,	129},
	{MON_ORC_SHAMAN,	130},
	{MON_BABY_BLUE_DRAGON,	131},
	{MON_BABY_WHITE_DRAGON,	132},
	{MON_BABY_GREEN_DRAGON,	133},
	{MON_BABY_BLACK_DRAGON,	134},
	{MON_BABY_RED_DRAGON,	135},
	{MON_GIANT_RED_ANT,	136},
	{MON_BRODDA_THE_EASTERLING,	137},
	{MON_KING_COBRA,	138},
	{MON_WAR_BEAR,	139},
	{MON_KILLER_BEE,	140},
	{MON_GIANT_SPIDER,	141},
	{MON_DARK_ELVEN_WIZARD,	142},
	{MON_ORFAX_SON_OF_BOLDOR,	143},
	{MON_DARK_ELVEN_WARRIOR,	144},
	{MON_ARCHER_MUSHROOM,	145},
	{MON_GRISHNAKH_THE_HILL_ORC,	146},
	{MON_HAIRY_MOLD,	147},
	{MON_DISENCHANTER_MOLD,	148},
	{MON_PSEUDO_DRAGON,	149},
	{MON_TENGU,	150},
	{MON_CREEPING_GOLD_COINS,	151},
	{MON_WOLF,	152},
	{MON_GIANT_FRUIT_FLY,	153},
	{MON_PANTHER,	154},
	{MON_BRIGAND,	155},
	{MON_FTHSSSSSS_CHAMPION_OF_CATS,	156},
	{MON_SHADOW_CREATURE,	157},
	{MON_UNDEAD_MASS,	158},
	{MON_CHAOS_SHAPECHANGER,	159},
	{MON_BABY_MULTI_HUED_DRAGON,	160},
	{MON_HIPPOGRIFF,	161},
	{MON_BLACK_MAMBA,	162},
	{MON_WHITE_WOLF,	163},
	{MON_GRAPE_JELLY,	164},
	{MON_NETHER_WORM_MASS,	165},
	{MON_ABYSS_WORM_MASS,	166},
	{MON_GOLFIMBUL_THE_HILL_ORC_CHIEF,	167},
	{MON_HELLCAT,	168},
	{MON_MOON_BEAST,	169},
	{MON_MASTER_YEEK,	170},
	{MON_CULTIST,	171},
	{MON_DARK_ELVEN_DEMONOLOGIST,	172},
	{MON_AIR_SPIRIT,	173},
	{MON_SKELETON_HUMAN,	174},
	{MON_ZOMBIFIED_HUMAN,	175},
	{MON_TIGER,	176},
	{MON_MOANING_SPIRIT,	177},
	{MON_FRUMIOUS_BANDERSNATCH,	178},
	{MON_SPOTTED_JELLY,	179},
	{MON_DRIDER,	180},
	{MON_HELLBAT,	181},
	{MON_KILLER_BROWN_BEETLE,	182},
	{MON_BOLDOR_KING_OF_THE_YEEKS,	183},
	{MON_OGRE,	184},
	{MON_CREEPING_MITHRIL_COINS,	185},
	{MON_ILLUSIONIST,	186},
	{MON_SHAMAN,	187},
	{MON_BLACK_ORC,	188},
	{MON_OCHRE_JELLY,	189},
	{MON_GIANT_COCKROACH,	190},
	{MON_GIANT_WHITE_DRAGON_FLY,	191},
	{MON_WITCH_OF_IB,	192},
	{MON_GIBBERING_MOUTHER,	193},
	{MON_MASTIFF,	194},
	{MON_HILL_GIANT,	195},
	{MON_FLESH_GOLEM,	196},
	{MON_WARG,	197},
	{MON_FIRE_VAMPIRE,	198},
	{MON_GIANT_FLEA,	199},
	{MON_BLACK_OGRE,	200},
	{MON_MAGIC_MUSHROOM_PATCH,	201},
	{MON_GUARDIAN_NAGA,	202},
	{MON_LIGHT_HOUND,	203},
	{MON_SHADOW_HOUND,	204},
	{MON_FLYING_SKULL,	205},
	{MON_MI_GO,	206},
	{MON_GIANT_TARANTULA,	207},
	{MON_GIANT_CLEAR_CENTIPEDE,	208},
	{MON_MIRKWOOD_SPIDER,	209},
	{MON_FROST_GIANT,	210},
	{MON_GRIFFON,	211},
	{MON_HOMONCULOUS,	212},
	{MON_GNOME_WIZARD,	213},
	{MON_CLEAR_HOUND,	214},
	{MON_UMBER_HULK,	215},
	{MON_ORC_CAPTAIN,	216},
	{MON_GELATINOUS_CUBE,	217},
	{MON_GIANT_GREEN_DRAGON_FLY,	218},
	{MON_FIRE_GIANT,	219},
	{MON_THE_EMISSARY,	220},
	{MON_QUASIT,	221},
	{MON_IMP,	222},
	{MON_FOREST_TROLL,	223},
	{MON_2_HEADED_HYDRA,	224},
	{MON_WATER_SPIRIT,	225},
	{MON_GIANT_RED_SCORPION,	226},
	{MON_EARTH_SPIRIT,	227},
	{MON_FIRE_SPIRIT,	228},
	{MON_FIRE_HOUND,	229},
	{MON_COLD_HOUND,	230},
	{MON_ENERGY_HOUND,	231},
	{MON_POTION_MIMIC,	232},
	{MON_BLINK_DOG,	233},
	{MON_URUK,	234},
	{MON_SHAGRAT_THE_ORC_CAPTAIN,	235},
	{MON_GORBAG_THE_ORC_CAPTAIN,	236},
	{MON_SHAMBLING_MOUND,	237},
	{MON_STONE_GIANT,	238},
	{MON_GIANT_BLACK_DRAGON_FLY,	239},
	{MON_STONE_GOLEM,	240},
	{MON_RED_MOLD,	241},
	{MON_GIANT_GOLD_DRAGON_FLY,	242},
	{MON_BOLG_SON_OF_AZOG,	243},
	{MON_PHASE_SPIDER,	244},
	{MON_WYVERN,	245},
	{MON_LIVINGSTONE,	246},
	{MON_EARTH_HOUND,	247},
	{MON_AIR_HOUND,	248},
	{MON_SABRE_TOOTH_TIGER,	249},
	{MON_WATER_HOUND,	250},
	{MON_CHIMERA,	251},
	{MON_QUYLTHULG,	252},
	{MON_SASQUATCH,	253},
	{MON_THE_QUEEN_OF_IB,	254},
	{MON_DARK_ELVEN_LORD,	255},
	{MON_CLOUD_GIANT,	256},
	{MON_UGLUK_THE_URUK,	257},
	{MON_BLUE_DRAGON_BAT,	258},
	{MON_FIRE_VORTEX,	259},
	{MON_WATER_VORTEX,	260},
	{MON_COLD_VORTEX,	261},
	{MON_ENERGY_VORTEX,	262},
	{MON_MUMMIFIED_ORC,	263},
	{MON_KILLER_STAG_BEETLE,	264},
	{MON_IRON_GOLEM,	265},
	{MON_AUTO_ROLLER,	266},
	{MON_GIANT_YELLOW_SCORPION,	267},
	{MON_BLACK_OOZE,	268},
	{MON_HARDENED_WARRIOR,	269},
	{MON_AZOG_KING_OF_THE_URUK_HAI,	270},
	{MON_DARK_ELVEN_WARLOCK,	271},
	{MON_MASTER_ROGUE,	272},
	{MON_RED_DRAGON_BAT,	273},
	{MON_GIANT_BRONZE_DRAGON_FLY,	274},
	{MON_KOUKO,	275},
	{MON_MIME_THE_NIBELUNG,	276},
	{MON_HAGEN_SON_OF_ALBERICH,	277},
	{MON_PHANTOM_BEAST,	278},
	{MON_4_HEADED_HYDRA,	279},
	{MON_TYRANNOSAUR,	280},
	{MON_MUMMIFIED_HUMAN,	281},
	{MON_VAMPIRE_BAT,	282},
	{MON_SANGAHYANDO_OF_UMBAR,	283},
	{MON_IT,	284},
	{MON_BANSHEE,	285},
	{MON_SILENT_WATCHER,	286},
	{MON_PUKELMAN,	287},
	{MON_DARK_ELVEN_SHAMAN,	288},
	{MON_STONE_TROLL,	289},
	{MON_TROLL_THAUMATURGIST,	290},
	{MON_WEREWORM,	291},
	{MON_KILLER_CRIMSON_BEETLE,	292},
	{MON_GIANT_GREY_ANT,	293},
	{MON_KHUFU_THE_MUMMIFIED_KING,	294},
	{MON_DISPLACER_BEAST,	295},
	{MON_CAVE_OGRE,	296},
	{MON_WHITE_WRAITH,	297},
	{MON_DEEP_ONE,	298},
	{MON_GHOUL,	299},
	{MON_ALBERICH_THE_NIBELUNG_KING,	300},
	{MON_HELLBLADE,	301},
	{MON_KILLER_RED_BEETLE,	302},
	{MON_CREEPING_ADAMANTITE_COINS,	303},
	{MON_ALGROTH,	304},
	{MON_HEADLESS,	305},
	{MON_VIBRATION_HOUND,	306},
	{MON_NEXUS_HOUND,	307},
	{MON_OGRE_WIZARD,	308},
	{MON_GRENDEL,	309},
	{MON_VAMPIRE,	310},
	{MON_GORGIMERA,	311},
	{MON_SHANTAK,	312},
	{MON_COLBRAN,	313},
	{MON_SPIRIT_NAGA,	314},
	{MON_STAIRWAY_TO_HELL,	315},
	{MON_GRENDELS_MOTHER,	316},
	{MON_BLACK_KNIGHT,	317},
	{MON_LESSER_WALL_MONSTER,	318},
	{MON_WIZARD,	319},
	{MON_MIND_FLAYER,	320},
	{MON_THE_ULTIMATE_DUNGEON_CLEANER,	321},
	{MON_FATHER_DAGON,	322},
	{MON_BASILISK,	323},
	{MON_ICE_TROLL,	324},
	{MON_BHOLE,	325},
	{MON_DIMENSIONAL_SHAMBLER,	326},
	{MON_RING_MIMIC,	327},
	{MON_CHAOS_TILE,	328},
	{MON_YOUNG_BLUE_DRAGON,	329},
	{MON_YOUNG_WHITE_DRAGON,	330},
	{MON_YOUNG_GREEN_DRAGON,	331},
	{MON_YOUNG_BRONZE_DRAGON,	332},
	{MON_MITHRIL_GOLEM,	333},
	{MON_SHADOW_DRAKE,	334},
	{MON_MANTICORE,	335},
	{MON_GIANT_ARMY_ANT,	336},
	{MON_KILLER_SLICER_BEETLE,	337},
	{MON_GHOST,	338},
	{MON_DEATH_WATCH_BEETLE,	339},
	{MON_OGRE_SHAMAN,	340},
	{MON_NEXUS_QUYLTHULG,	341},
	{MON_SHELOB_SPIDER_OF_DARKNESS,	342},
	{MON_NINJA,	343},
	{MON_MEMORY_MOSS,	344},
	{MON_STORM_GIANT,	345},
	{MON_SPECTATOR,	346},
	{MON_CAVE_TROLL,	347},
	{MON_ANTI_PALADIN,	348},
	{MON_CHAOS_MASTER,	349},
	{MON_BARROW_WIGHT,	350},
	{MON_GIANT_SKELETON_TROLL,	351},
	{MON_CHAOS_DRAKE,	352},
	{MON_LAW_DRAKE,	353},
	{MON_BALANCE_DRAKE,	354},
	{MON_ETHEREAL_DRAKE,	355},
	{MON_GROO_THE_WANDERER,	356},
	{MON_FASOLT_THE_GIANT,	357},
#ifdef SF_R_INFO_1
	{MON_BOKRUG_THE_WATER_LIZARD,	-1},
#endif
	{MON_CHAOS_GHOST,	358},
	{MON_SPECTRE,	359},
	{MON_WATER_TROLL,	360},
	{MON_FIRE_ELEMENTAL,	361},
	{MON_LENG_SPIDER,	362},
	{MON_WATER_ELEMENTAL,	363},
	{MON_MULTI_HUED_HOUND,	364},
	{MON_NIGHT_STALKER,	365},
	{MON_CARRION_CRAWLER,	366},
	{MON_MASTER_THIEF,	367},
	{MON_FIRE_PHANTOM,	368},
	{MON_LICH,	369},
	{MON_MASTER_VAMPIRE,	370},
	{MON_ORIENTAL_VAMPIRE,	371},
	{MON_GIANT_GREY_SCORPION,	372},
	{MON_EARTH_ELEMENTAL,	373},
	{MON_AIR_ELEMENTAL,	374},
	{MON_DOOM_DRAKE,	375},
	{MON_MALICIOUS_LEPRECHAUN,	376},
	{MON_EOG_GOLEM,	377},
	{MON_OLOG,	378},
	{MON_HALFLING_SLINGER,	379},
	{MON_GRAVITY_HOUND,	380},
	{MON_ACIDIC_CYTOPLASM,	381},
	{MON_INERTIA_HOUND,	382},
	{MON_IMPACT_HOUND,	383},
	{MON_OOZE_ELEMENTAL,	384},
	{MON_YOUNG_BLACK_DRAGON,	385},
	{MON_MATURE_WHITE_DRAGON,	386},
	{MON_XORN,	387},
	{MON_LAW_GHOST,	388},
	{MON_GREY_WRAITH,	389},
	{MON_YOUNG_MULTI_HUED_DRAGON,	390},
	{MON_RAALS_TOME_OF_DESTRUCTION,	391},
	{MON_COLOSSUS,	392},
	{MON_YOUNG_GOLD_DRAGON,	393},
	{MON_MATURE_BLUE_DRAGON,	394},
	{MON_MATURE_GREEN_DRAGON,	395},
	{MON_MATURE_BRONZE_DRAGON,	396},
	{MON_YOUNG_RED_DRAGON,	397},
	{MON_NIGHTBLADE,	398},
	{MON_TRAPPER,	399},
	{MON_BODAK,	400},
	{MON_ELDER_THING,	401},
	{MON_ICE_ELEMENTAL,	402},
	{MON_IPSISSIMUS,	403},
	{MON_THE_INSANE_CRUSADER,	404},
	{MON_CHAOS_SPAWN,	405},
	{MON_TIME_ELEMENTAL,	406},
	{MON_THE_QUEEN_ANT,	407},
	{MON_WILL_O_THE_WISP,	408},
	{MON_MAGMA_ELEMENTAL,	409},
	{MON_BLACK_PUDDING,	410},
	{MON_KILLER_IRIDESCENT_BEETLE,	411},
	{MON_NEXUS_VORTEX,	412},
	{MON_PLASMA_VORTEX,	413},
	{MON_MATURE_RED_DRAGON,	414},
	{MON_MATURE_GOLD_DRAGON,	415},
	{MON_CRYSTAL_DRAKE,	416},
	{MON_MATURE_BLACK_DRAGON,	417},
	{MON_MATURE_MULTI_HUED_DRAGON,	418},
	{MON_DEATH_KNIGHT,	419},
	{MON_MANDOR_MASTER_OF_CHAOS,	420},
	{MON_TIME_VORTEX,	421},
	{MON_SHIMMERING_VORTEX,	422},
	{MON_ANCIENT_BLUE_DRAGON,	423},
	{MON_ANCIENT_BRONZE_DRAGON,	424},
	{MON_BEHOLDER,	425},
	{MON_EMPEROR_WIGHT,	426},
	{MON_FLYING_POLYP,	427},
	{MON_KARAKAL_SPIRIT_OF_FIRE,	428},
	{MON_BLACK_WRAITH,	429},
	{MON_NIGHTGAUNT,	430},
	{MON_BARON_OF_HELL,	431},
	{MON_NETHER_WRAITH,	432},
	{MON_LASHA_MISTRESS_OF_WATER,	433},
	{MON_KAVLAX_THE_MANY_HEADED,	434},
	{MON_ANCIENT_WHITE_DRAGON,	435},
	{MON_ANCIENT_GREEN_DRAGON,	436},
	{MON_CHTHONIAN,	437},
	{MON_NIGHT_MARE,	438},
	{MON_VAMPIRE_LORD,	439},
	{MON_ANCIENT_BLACK_DRAGON,	440},
	{MON_WAR_TROLL,	441},
	{MON_DISENCHANTER_WORM_MASS,	442},
	{MON_ROTTING_QUYLTHULG,	443},
	{MON_LESSER_TITAN,	444},
	{MON_9_HEADED_HYDRA,	445},
	{MON_ENCHANTRESS,	446},
	{MON_CULT_LEADER,	447},
	{MON_SORCERER,	448},
	{MON_XAREN,	449},
	{MON_JUBJUB_BIRD,	450},
	{MON_MINOTAUR,	451},
	{MON_MEDUSA_THE_GORGON,	452},
	{MON_DEATH_DRAKE,	453},
	{MON_ANCIENT_RED_DRAGON,	454},
	{MON_ANCIENT_GOLD_DRAGON,	455},
	{MON_GREAT_CRYSTAL_DRAKE,	456},
	{MON_CLUBBER_DEMON,	457},
	{MON_DEATH_QUASIT,	458},
	{MON_GLARYSSA_SUCCUBUS_QUEEN,	459},
	{MON_DARK_ELVEN_THAUMATURGE,	460},
	{MON_MASTER_LICH,	461},
	{MON_BYAKHEE,	462},
	{MON_SHOGGOTH,	463},
	{MON_SERVITOR_OF_THE_OUTER_GODS,	464},
	{MON_FORMLESS_SPAWN_OF_TSATHOGGUA,	465},
	{MON_HUNTING_HORROR,	466},
	{MON_UNDEAD_BEHOLDER,	467},
	{MON_SHADOW_DEMON,	468},
	{MON_IRON_LICH,	469},
	{MON_VERMICIOUS_KNID,	470},
	{MON_ANCIENT_MULTI_HUED_DRAGON,	471},
	{MON_ETHEREAL_DRAGON,	472},
	{MON_DARK_YOUNG_OF_SHUB_NIGGURATH,	473},
	{MON_GROM_MASTER_OF_EARTH,	474},
	{MON_STRAASHA_QUEEN_OF_AIR,	475},
	{MON_11_HEADED_HYDRA,	476},
	{MON_CULT_HIGH_PRIEST,	477},
	{MON_DREADMASTER,	478},
	{MON_DROLEM,	479},
	{MON_SCATHA_THE_WORM,	480},
	{MON_AVATAR_OF_NYARLATHOTEP,	481},
	{MON_NAZGUL,	482},
	{MON_SMAUG_THE_GOLDEN,	483},
	{MON_THE_STORMBRINGER,	484},
	{MON_ULTRA_ELITE_PALADIN,	485},
	{MON_DRACOLICH,	486},
	{MON_GREATER_TITAN,	487},
	{MON_DRACOLISK,	488},
	{MON_SPECTRAL_TYRANNOSAUR,	489},
	{MON_DEATH_MOLD,	490},
	{MON_FAFNER_THE_DRAGON,	491},
	{MON_GLAURUNG_FATHER_OF_THE_DRAGONS,	492},
	{MON_GREATER_WALL_MONSTER,	493},
	{MON_BALROG,	494},
	{MON_GOAT_OF_MENDES,	495},
	{MON_NIGHTWING,	496},
	{MON_MAULOTAUR,	497},
	{MON_NETHER_HOUND,	498},
	{MON_TIME_HOUND,	499},
	{MON_PLASMA_HOUND,	500},
	{MON_DEMONIC_QUYLTHULG,	501},
	{MON_GREAT_STORM_WYRM,	502},
	{MON_BAPHOMET_THE_MINOTAUR_LORD,	503},
	{MON_GRAND_MASTER_THIEF,	504},
	{MON_THE_COLLECTOR,	505},
	{MON_LORD_OF_CHAOS,	506},
	{MON_KHAMUL_THE_EASTERLING,	507},
	{MON_HOUND_OF_TINDALOS,	508},
	{MON_GREAT_ICE_WYRM,	509},
	{MON_THE_PHOENIX,	510},
	{MON_NIGHTCRAWLER,	511},
	{MON_HAND_DRUJ,	512},
	{MON_EYE_DRUJ,	513},
	{MON_SKULL_DRUJ,	514},
	{MON_CHAOS_VORTEX,	515},
	{MON_AETHER_VORTEX,	516},
	{MON_THE_LERNEAN_HYDRA,	517},
	{MON_THURINGWETHIL,	518},
	{MON_GREAT_HELL_WYRM,	519},
	{MON_HASTUR_THE_UNSPEAKABLE,	520},
	{MON_DRACONIC_QUYLTHULG,	521},
	{MON_NYOGTHA_THE_THING_THAT_SHOULD_NOT_BE,	522},
	{MON_SHUDDE_MELL,	523},
	{MON_FTHAGGHUA_LORD_OF_THE_FIRE_VAMPIRES,	524},
	{MON_TULZSCHA,	525},
	{MON_ANCALAGON_THE_BLACK,	526},
	{MON_NIGHTWALKER,	527},
	{MON_DAOLOTH,	528},
	{MON_SARUMAN_OF_MANY_COLOURS,	529},
	{MON_SHADOWLORD,	530},
	{MON_BAST_GODDESS_OF_CATS,	531},
	{MON_JABBERWOCK,	532},
	{MON_CHAOS_HOUND,	533},
	{MON_GREAT_WYRM_OF_CHAOS,	534},
	{MON_GREAT_WYRM_OF_LAW,	535},
	{MON_GREAT_WYRM_OF_BALANCE,	536},
	{MON_SHAMBLER,	537},
	{MON_GREAT_WYRM_OF_MANY_COLOURS,	538},
	{MON_TSELAKUS_THE_DREADLORD,	539},
	{MON_SKY_DRAKE,	540},
	{MON_THE_NORSA,	541},
	{MON_BONE_GOLEM,	542},
	{MON_MASTER_QUYLTHULG,	543},
	{MON_GREATER_DRACONIC_QUYLTHULG,	544},
	{MON_GREATER_ROTTING_QUYLTHULG,	545},
	{MON_VECNA_THE_EMPEROR_LICH,	546},
	{MON_OMARAX_THE_EYE_TYRANT,	547},
	{MON_ATLACH_NACHA_THE_SPIDER_GOD,	548},
	{MON_AETHER_HOUND,	549},
	{MON_UNMAKER,	550},
	{MON_BLACK_REAVER,	551},
	{MON_KLINGSOR_EVIL_MASTER_OF_MAGIC,	552},
	{MON_GLAAKI,	553},
	{MON_THE_EMPEROR_QUYLTHULG,	554},
	{MON_QLZQQLZUUP_THE_LORD_OF_FLESH,	555},
	{MON_HYPNOS,	556},
	{MON_THE_WITCH_KING_OF_ANGMAR,	557},
	{MON_ITHAQUA_THE_WINDWALKER,	558},
	{MON_SNAKE_OF_YIG,	559},
	{MON_CANTORAS_THE_SKELETAL_LORD,	560},
	{MON_MEPHISTOPHELES_LORD_OF_HELL,	561},
	{MON_YIG_FATHER_OF_SERPENTS,	562},
	{MON_STAR_SPAWN_OF_CTHULHU,	563},
	{MON_KASCHEI_THE_IMMORTAL,	564},
	{MON_YOG_SOTHOTH_THE_ALL_IN_ONE,	565},
	{MON_GREAT_WYRM_OF_POWER,	566},
	{MON_SHUB_NIGGURATH_BLACK_GOAT_OF_THE_WOODS,	567},
	{MON_CARCHAROTH_THE_JAWS_OF_THIRST,	568},
	{MON_ABHOTH_SOURCE_OF_UNCLEANNESS,	569},
	{MON_TSATHOGGUA,	570},
	{MON_GOTHMOG_THE_HIGH_CAPTAIN_OF_BALROGS,	571},
	{MON_GREAT_CTHULHU,	572},
	{MON_SAURON_THE_SORCERER,	573},
	{MON_NYARLATHOTEP,	574},
	{MON_AZATHOTH_THE_DAEMON_SULTAN,	575},
};

/* A list of shop owners, as they aren't used elsewhere. */
#define OWN_YOUR_HOME 0
#define OWN_HALL_OF_RECORDS 1
#define OWN_FALILMAWEN_THE_FRIENDLY 2
#define OWN_VOIRIN_THE_COWARDLY 3
#define OWN_ERASHNAK_THE_MIDGET 4
#define OWN_GRUG_THE_COMELY 5
#define OWN_KON_DAR_THE_UGLY 6
#define OWN_DARG_LOW_THE_GRIM 7
#define OWN_DECADO_THE_HANDSOME 8
#define OWN_ELO_DRAGONSCALE 9
#define OWN_ARNOLD_THE_BEASTLY 10
#define OWN_ARNDAL_BEAST_SLAYER 11
#define OWN_EDOR_THE_SHORT 12
#define OWN_OGLIGN_DRAGON_SLAYER 13
#define OWN_LUDWIG_THE_HUMBLE 14
#define OWN_GUNNAR_THE_PALADIN 15
#define OWN_SIR_PARSIVAL_THE_PURE 16
#define OWN_ASENATH_THE_HOLY 17
#define OWN_MCKINNON 18
#define OWN_MISTRESS_CHASTITY 19
#define OWN_HASHNIK_THE_DRUID 20
#define OWN_FINAK 21
#define OWN_MAUSER_THE_CHEMIST 22
#define OWN_WIZZLE_THE_CHAOTIC 23
#define OWN_KAKALRAKAKAL 24
#define OWN_JAL_ETH_THE_ALCHEMIST 25
#define OWN_SKIDNEY_THE_SORCERER 26
#define OWN_BUGGERBY_THE_GREAT 27
#define OWN_KYRIA_THE_ILLUSIONIST 28
#define OWN_NIKKI_THE_NECROMANCER 29
#define OWN_RANDOLPH_CARTER 30
#define OWN_ODNAR_THE_SAGE 31
#define OWN_GANDAR_THE_NEUTRAL 32
#define OWN_RO_SHA_THE_PATIENT 33
#define OWN_MORDSAN 34
#define OWN_FURFOOT_POBBER 35
#define OWN_ODDO_YEEKSON 36
#define OWN_DRY_BONES 37
#define OWN_MAGD_THE_RUTHLESS 38
#define OWN_DRAKO_FAIRDEAL 39
#define OWN_FEATHERWING 40
#define OWN_XOCHINAGGUA 41
#define OWN_FOROVIR_THE_CHEAP 42
#define OWN_ELLIS_THE_FOOL 43
#define OWN_FILBERT_THE_HUNGRY 44
#define OWN_FTHNARGL_PSATHIGGUA 45
#define OWN_DELICATUS 46
#define OWN_GRUCE_THE_HUGE 47
#define OWN_ANIMUS 48
#define OWN_MALVUS 49
#define OWN_DREW_THE_SKILLED 50
#define OWN_ORRAX_DRAGONSON 51
#define OWN_ANTHRAX_DISEASE_CARRIER 52
#define OWN_ARKHOTH_THE_STOUT 53
#define OWN_KRIKKIK 54
#define OWN_MORIVAL_THE_WILD 55
#define OWN_HOSHAK_THE_DARK 56
#define OWN_ATAL_THE_WISE 57
#define OWN_FANELATH_THE_CAUTIOUS 58
#define OWN_RUNCIE_THE_INSANE 59
#define OWN_GRUMBLEWORTH 60
#define OWN_FLITTER 61
#define OWN_SOLOSTORAN 62
#define OWN_ACHSHE_THE_TENTACLED 63
#define OWN_KAZA_THE_NOBLE 64
#define OWN_FAZZIL_THE_DARK 65
#define OWN_SARAI_THE_SWIFT 66
#define OWN_BODRIL_THE_SEER 67
#define OWN_VELOIN_THE_QUIET 68
#define OWN_VANTHYLAS_THE_LEARNED 69
#define OWN_KLEIBONS 70
#define OWN_PRENDEGAST 71
#define OWN_STRAASHA 72
#define OWN_ALLIA_THE_SERVILE 73
#define OWN_OD_THE_PENNILESS 74
#define OWN_XAX 75
#define OWN_JAKE_SMALL 76
#define OWN_HELGA_THE_LOST 77
#define OWN_ELOISE_LONG_DEAD 78
#define OWN_FUNDI_THE_SLOW 79
#define OWN_GRANTHUS 80
#define OWN_LORAX_THE_SUAVE 81
#define OWN_SELAXIS 82
#define OWN_DEATHCHILL 83
#define OWN_DRIOS_THE_FAINT 84
#define OWN_BATHRIC_THE_COLD 85
#define OWN_SARLYAS_THE_ROTTEN 86
#define OWN_TUETHIC_BARE_BONES 87
#define OWN_BILIOUS 88
#define OWN_FASGUL 89
#define OWN_VHASSA_THE_DEAD 90
#define OWN_KYN_THE_TREACHEROUS 91
#define OWN_BUBONICUS 92
#define OWN_CORPSELIGHT 93
#define OWN_PARRISH_THE_BLOODTHIRSTY 94
#define OWN_VILE 95
#define OWN_PRENTICE_THE_TRUSTED 96
#define OWN_GRIELLA_HUMANSLAYER 97
#define OWN_ANGELFACE 98
#define OWN_FLOTSAM_THE_BLOATED 99
#define OWN_NIEVAL 100
#define OWN_ANASTASIA_THE_LUMINOUS 101
#define OWN_OSSEIN_THE_LITERATE 102
#define OWN_OLVAR_BOOKWORM 103
#define OWN_SHALLOWGRAVE 104
#define OWN_DNDRASN 105
#define OWN_FUBBLE_THE_BORING 106
#define OWN_BARE_BONES_SALLUAH 107
#define OWN_WINSALT_ONCE_LIVING 108
#define OWN_AGNES_DARCY 109
#define OWN_LUMIN_THE_BLUE 110
#define OWN_SHORT_AL 111
#define OWN_SILENT_FALDUS 112
#define OWN_QUIRMBY_THE_STRANGE 113
#define OWN_GLOOM_THE_PHLEGMATIC 114
#define OWN_QUICK_ARM_VOLLAIRE 115
#define OWN_ASENATH 116
#define OWN_LORD_FILBERT 117
#define OWN_BUTCH 118
#define OWN_ELBERETH_THE_BEAUTIFUL 119
#define OWN_SARLETH_THE_SNEAKY 120
#define OWN_NARLOCK 121
#define OWN_VENGELLA_THE_CRUEL 122
#define OWN_WYRANA_THE_MIGHTY 123
#define OWN_YOJO_II 124
#define OWN_RANALAR_THE_SWEET 125
#define OWN_UURDA_THE_INFECTIOUS 126
#define OWN_SPARROW_II 127
#define OWN_WESTMARK_THE_FALLEN 128
#define OWN_GROB_THE_STUPID 129
#define OWN_ELLEFRIS_THE_PALADIN 130
#define OWN_KTRRIKK 131
#define OWN_DROCUS_SPIDERFRIEND 132
#define OWN_FUNGUS_GIANT_SLAYER 133
#define OWN_DELANTHA 134
#define OWN_SOLVISTANI_THE_RANGER 135
#define OWN_XORIL_THE_SLOW 136
#define OWN_AEON_FLUX 137
#define OWN_XARILLUS 138
#define OWN_EGBERT_THE_OLD 139
#define OWN_VALINDRA_THE_PROUD 140
#define OWN_TAEN_THE_ALCHEMIST 141
#define OWN_KELDORN_THE_GRAND 142
#define OWN_PHILANTHROPUS 143
#define OWN_AGNAR_THE_ENCHANTRESS 144
#define OWN_BULIANCE_THE_NECROMANCER 145
#define OWN_CHARITY_THE_NECROMANCER 146
#define OWN_PUGNACIOUS_THE_PUGILIST 147
#define OWN_FOOTSORE_THE_LUCKY 148
#define OWN_SIDRIA_LIGHFINGERED 149
#define OWN_PORCINA_THE_OBESE 150
#define OWN_GLARUNA_BRANDYBREATH 151
#define OWN_FURFACE_YEEK 152
#define OWN_BALD_OGGIN 153
#define OWN_ALDOUS_THE_SLEEPY 154
#define OWN_GRUNDY_THE_TALL 155
#define OWN_GOBBLEGUTS_THUNDERBREATH 156
#define OWN_SILVERSCALE 157
#define OWN_HANEKA_THE_SMALL 158
#define OWN_LOIRIN_THE_MAD 159
#define OWN_WUTO_POISONBREATH 160
#define OWN_ARAAKA_THE_ROTUND 161
#define OWN_HORBAG_THE_UNCLEAN 162
#define OWN_ELELEN_THE_TELEPATH 163
#define OWN_ISEDRELIAS 164
#define OWN_VEGNAR_ONE_EYE 165
#define OWN_NADOC_THE_STRONG 166
#define OWN_ERAMOG_THE_WEAK 167
#define OWN_EOWILITH_THE_FAIR 168
#define OWN_HUIMOG_BALROG_SLAYER 169
#define OWN_IBENIDD_THE_CHASTE 170
#define OWN_ERIDISH 171
#define OWN_VRUDUSH_THE_SHAMAN 172
#define OWN_HAOB_THE_BERSERKER 173
#define OWN_CAYD_THE_SWEET 174
#define OWN_FULIR_THE_DARK 175
#define OWN_DOMLI_THE_HUMBLE 176
#define OWN_YAARJUKKA_DEMONSPAWN 177
#define OWN_VUIRAK_THE_WIZARD 178
#define OWN_MADISH_THE_SMART 179
#define OWN_FALEBRIMBOR 180
#define OWN_FELIL_GAND_THE_SUBTLE 181
#define OWN_RIATHO_THE_JUGGLER 182
#define OWN_JANAAKA_THE_SHIFTY 183
#define OWN_CINA_THE_ROGUE 184
#define OWN_ARUNIKKI_GREATCLAW 185
#define OWN_ASUUNU_THE_LEARNED 186
#define OWN_PRIRAND_THE_DEAD 187
#define OWN_RONAR_THE_IRON 188
#define OWN_GALIL_GAMIR 189
#define OWN_TOGDUSH_THE_QUIET 190
#define OWN_VURJAANA_THE_STUDIOUS 191
#define OWN_YIETRAM_THE_LUMINOUS 192
#define OWN_THRADRIERITH 193
#define OWN_ETHERAA_THE_FURIOUS 194
#define OWN_PAETLAN_THE_ALCOHOLIC 195
#define OWN_DRANG 196
#define OWN_BARBAG_THE_SLY 197
#define OWN_POOGOR_THE_DUMB 198
#define OWN_FELORFILIAND 199
#define OWN_MAROKA_THE_AGED 200
#define OWN_SASIN_THE_BOLD 201
#define OWN_RODISH_THE_CHAOTIC 202
#define OWN_HESIN_SWORDMASTER 203
#define OWN_ELVERERITH_THE_CHEAT 204
#define OWN_ZZATHATH_THE_IMP 205
#define OWN_PEADUS_THE_CRUEL 206
#define OWN_VAMOG_SLAYER 207
#define OWN_HOOSHNAK_THE_VICIOUS 208
#define OWN_BALENN_WAR_DANCER 209
#define OWN_PROOGDISH_THE_YOUTHFULL 210
#define OWN_LUMWISE_THE_MAD 211
#define OWN_MUIRT_THE_VIRTUOUS 212
#define OWN_DARDOBARD_THE_WEAK 213
#define OWN_GELARALDOR_THE_HERBMASTER 214
#define OWN_OLELALDAN_THE_WISE 215
#define OWN_FTHOGLO_THE_DEMONICIST 216
#define OWN_DRIDASH_THE_ALCHEMIST 217
#define OWN_NELIR_THE_STRONG 218
#define OWN_LIGNUS_THE_PUNGENT 219
#define OWN_TILBA 220
#define OWN_MYRILDRIC_THE_WEALTHY 221
#define OWN_THALEGORD_THE_SHAMAN 222
#define OWN_CTHOALOTH_THE_MYSTIC 223
#define OWN_IBELI_THE_ILLUSIONIST 224
#define OWN_HETO_THE_NECROMANCER 225
#define OWN_CHAEAND_THE_POOR 226
#define OWN_AFARDORF_THE_BRIGAND 227
#define OWN_LATHAXL_THE_GREEDY 228
#define OWN_FALAREWYN 229
#define OWN_VOSUR_THE_WRINKLED 230
#define OWN_ARAORD_THE_HANDSOME 231
#define OWN_THERADFRID_THE_LOSER 232
#define OWN_ONE_LEGGED_EROOLO 233
#define OWN_RORBAG_BOOK_EATER 234
#define OWN_KIRIARIKIRK 235
#define OWN_RILIN_THE_QUIET 236
#define OWN_ISUNG_THE_LORD 237
#define OWN_KIRAKAK 238
#define OWN_NAFUR_THE_WOODEN 239
#define OWN_GRARAK_THE_HOSPITABLE 240
#define OWN_LONA_THE_CHARISMATIC 241
#define OWN_HERRANYTH_THE_RUTHLESS 242
#define OWN_GAGRIN_MONEYLENDER 243
#define OWN_THRAMBOR_THE_GRUBBY 244
#define OWN_DERIGRIN_THE_HONEST 245
#define OWN_ABIEMAR_THE_PEASANT 246
#define OWN_HURK_THE_POOR 247
#define OWN_SOALIN_THE_WRETCHED 248
#define OWN_MERULLA_THE_HUMBLE 249
#define OWN_CREDIRIC_THE_BREWER 250
#define OWN_NYDUDUS_THE_SLOW 251
#define OWN_BAURK_THE_BUSY 252
#define OWN_SEVIRAS_THE_MINDCRAFTER 253
#define OWN_MUNK_THE_BARTERER 254
#define OWN_GADRIALDUR_THE_FAIR 255
#define OWN_NINAR_THE_STOOPED 256
#define OWN_ADIRATH_THE_UNMAGICAL 257

#define OWNER_MAX_DISTRO OWN_ADIRATH_THE_UNMAGICAL

/* A list of the old town indices. */
#define TOWN_CELEPHAIS	0
#define TOWN_ULTHAR	1
#define TOWN_DYLATH	2
#define TOWN_KADATH	3
#define TOWN_HLANTH	4
#define TOWN_ILEK	5
#define TOWN_INGANOK	6
#define TOWN_NIR	7

/*
 * The table of version flags which alter the shopkeeper table.
 * This is currently a flag, but may need to change to an index as the
 * save file version grows.
 */
static u32b owner_version[] =
{
#ifdef SF_QUEST_DIRECT
	SF_QUEST_DIRECT,
#else
	0,
#endif
	0
};

/*
 * The table of shopkeeper indices for the above indices in the same order.
 * Versions 0 will already have been converted from a 2d format to a 1d one.
 */
static s16b owner_table[][2] =
{
	{OWN_FALILMAWEN_THE_FRIENDLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+0)+0},
	{OWN_VOIRIN_THE_COWARDLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+0)+1},
	{OWN_ERASHNAK_THE_MIDGET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+0)+2},
	{OWN_GRUG_THE_COMELY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+0)+3},
	{OWN_KON_DAR_THE_UGLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+1)+0},
	{OWN_DARG_LOW_THE_GRIM, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+1)+1},
	{OWN_DECADO_THE_HANDSOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+1)+2},
	{OWN_ELO_DRAGONSCALE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+1)+3},
	{OWN_ARNOLD_THE_BEASTLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+2)+0},
	{OWN_ARNDAL_BEAST_SLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+2)+1},
	{OWN_EDOR_THE_SHORT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+2)+2},
	{OWN_OGLIGN_DRAGON_SLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+2)+3},
	{OWN_LUDWIG_THE_HUMBLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+3)+0},
	{OWN_GUNNAR_THE_PALADIN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+3)+1},
	{OWN_SIR_PARSIVAL_THE_PURE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+3)+2},
	{OWN_ASENATH_THE_HOLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+3)+3},
	{OWN_MCKINNON, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+4)+0},
	{OWN_MISTRESS_CHASTITY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+4)+1},
	{OWN_HASHNIK_THE_DRUID, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+4)+2},
	{OWN_FINAK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+4)+3},
	{OWN_MAUSER_THE_CHEMIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+5)+0},
	{OWN_WIZZLE_THE_CHAOTIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+5)+1},
	{OWN_KAKALRAKAKAL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+5)+2},
	{OWN_JAL_ETH_THE_ALCHEMIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+5)+3},
	{OWN_SKIDNEY_THE_SORCERER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+6)+0},
	{OWN_BUGGERBY_THE_GREAT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+6)+1},
	{OWN_KYRIA_THE_ILLUSIONIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+6)+2},
	{OWN_NIKKI_THE_NECROMANCER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+6)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+7)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+7)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+7)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+7)+3},
	{OWN_RANDOLPH_CARTER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+8)+0},
	{OWN_ODNAR_THE_SAGE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+8)+1},
	{OWN_GANDAR_THE_NEUTRAL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+8)+2},
	{OWN_RO_SHA_THE_PATIENT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+8)+3},
	{OWN_MORDSAN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+9)+0},
	{OWN_FURFOOT_POBBER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+9)+1},
	{OWN_ODDO_YEEKSON, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+9)+2},
	{OWN_DRY_BONES, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+9)+3},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+10)+0},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+10)+1},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+10)+2},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+10)+3},
	{OWN_MAGD_THE_RUTHLESS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+11)+0},
	{OWN_DRAKO_FAIRDEAL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+11)+1},
	{OWN_FEATHERWING, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+11)+2},
	{OWN_XOCHINAGGUA, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_CELEPHAIS+11)+3},
	{OWN_FOROVIR_THE_CHEAP, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+0)+0},
	{OWN_ELLIS_THE_FOOL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+0)+1},
	{OWN_FILBERT_THE_HUNGRY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+0)+2},
	{OWN_FTHNARGL_PSATHIGGUA, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+0)+3},
	{OWN_DELICATUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+1)+0},
	{OWN_GRUCE_THE_HUGE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+1)+1},
	{OWN_ANIMUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+1)+2},
	{OWN_MALVUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+1)+3},
	{OWN_DREW_THE_SKILLED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+2)+0},
	{OWN_ORRAX_DRAGONSON, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+2)+1},
	{OWN_ANTHRAX_DISEASE_CARRIER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+2)+2},
	{OWN_ARKHOTH_THE_STOUT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+2)+3},
	{OWN_KRIKKIK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+3)+0},
	{OWN_MORIVAL_THE_WILD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+3)+1},
	{OWN_HOSHAK_THE_DARK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+3)+2},
	{OWN_ATAL_THE_WISE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+3)+3},
	{OWN_FANELATH_THE_CAUTIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+4)+0},
	{OWN_RUNCIE_THE_INSANE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+4)+1},
	{OWN_GRUMBLEWORTH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+4)+2},
	{OWN_FLITTER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+4)+3},
	{OWN_SOLOSTORAN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+5)+0},
	{OWN_ACHSHE_THE_TENTACLED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+5)+1},
	{OWN_KAZA_THE_NOBLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+5)+2},
	{OWN_FAZZIL_THE_DARK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+5)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+6)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+6)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+6)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+6)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+7)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+7)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+7)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+7)+3},
	{OWN_SARAI_THE_SWIFT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+8)+0},
	{OWN_BODRIL_THE_SEER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+8)+1},
	{OWN_VELOIN_THE_QUIET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+8)+2},
	{OWN_VANTHYLAS_THE_LEARNED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+8)+3},
	{OWN_KLEIBONS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+9)+0},
	{OWN_PRENDEGAST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+9)+1},
	{OWN_STRAASHA, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+9)+2},
	{OWN_ALLIA_THE_SERVILE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+9)+3},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+10)+0},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+10)+1},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+10)+2},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+10)+3},
	{OWN_OD_THE_PENNILESS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+11)+0},
	{OWN_XAX, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+11)+1},
	{OWN_JAKE_SMALL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+11)+2},
	{OWN_HELGA_THE_LOST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ULTHAR+11)+3},
	{OWN_ELOISE_LONG_DEAD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+0)+0},
	{OWN_FUNDI_THE_SLOW, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+0)+1},
	{OWN_GRANTHUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+0)+2},
	{OWN_LORAX_THE_SUAVE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+0)+3},
	{OWN_SELAXIS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+1)+0},
	{OWN_DEATHCHILL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+1)+1},
	{OWN_DRIOS_THE_FAINT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+1)+2},
	{OWN_BATHRIC_THE_COLD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+1)+3},
	{OWN_SARLYAS_THE_ROTTEN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+2)+0},
	{OWN_TUETHIC_BARE_BONES, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+2)+1},
	{OWN_BILIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+2)+2},
	{OWN_FASGUL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+2)+3},
	{OWN_VHASSA_THE_DEAD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+3)+0},
	{OWN_KYN_THE_TREACHEROUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+3)+1},
	{OWN_BUBONICUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+3)+2},
	{OWN_CORPSELIGHT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+3)+3},
	{OWN_PARRISH_THE_BLOODTHIRSTY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+4)+0},
	{OWN_VILE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+4)+1},
	{OWN_PRENTICE_THE_TRUSTED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+4)+2},
	{OWN_GRIELLA_HUMANSLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+4)+3},
	{OWN_ANGELFACE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+5)+0},
	{OWN_FLOTSAM_THE_BLOATED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+5)+1},
	{OWN_NIEVAL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+5)+2},
	{OWN_ANASTASIA_THE_LUMINOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+5)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+6)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+6)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+6)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+6)+3},
	{OWN_OSSEIN_THE_LITERATE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+7)+0},
	{OWN_OLVAR_BOOKWORM, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+7)+1},
	{OWN_SHALLOWGRAVE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+7)+2},
	{OWN_DNDRASN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+7)+3},
	{OWN_FUBBLE_THE_BORING, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+8)+0},
	{OWN_BARE_BONES_SALLUAH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+8)+1},
	{OWN_WINSALT_ONCE_LIVING, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+8)+2},
	{OWN_AGNES_DARCY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+8)+3},
	{OWN_LUMIN_THE_BLUE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+9)+0},
	{OWN_SHORT_AL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+9)+1},
	{OWN_SILENT_FALDUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+9)+2},
	{OWN_QUIRMBY_THE_STRANGE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+9)+3},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+10)+0},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+10)+1},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+10)+2},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+10)+3},
	{OWN_GLOOM_THE_PHLEGMATIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+11)+0},
	{OWN_QUICK_ARM_VOLLAIRE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+11)+1},
	{OWN_ASENATH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+11)+2},
	{OWN_LORD_FILBERT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_DYLATH+11)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+0)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+0)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+0)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+0)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+1)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+1)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+1)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+1)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+2)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+2)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+2)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+2)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+3)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+3)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+3)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+3)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+4)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+4)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+4)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+4)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+5)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+5)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+5)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+5)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+6)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+6)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+6)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+6)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+7)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+7)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+7)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+7)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+8)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+8)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+8)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+8)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+9)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+9)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+9)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+9)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+10)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+10)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+10)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+10)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+11)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+11)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+11)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_KADATH+11)+3},
	{OWN_BUTCH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+0)+0},
	{OWN_ELBERETH_THE_BEAUTIFUL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+0)+1},
	{OWN_SARLETH_THE_SNEAKY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+0)+2},
	{OWN_NARLOCK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+0)+3},
	{OWN_VENGELLA_THE_CRUEL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+1)+0},
	{OWN_WYRANA_THE_MIGHTY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+1)+1},
	{OWN_YOJO_II, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+1)+2},
	{OWN_RANALAR_THE_SWEET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+1)+3},
	{OWN_UURDA_THE_INFECTIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+2)+0},
	{OWN_SPARROW_II, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+2)+1},
	{OWN_WESTMARK_THE_FALLEN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+2)+2},
	{OWN_GROB_THE_STUPID, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+2)+3},
	{OWN_ELLEFRIS_THE_PALADIN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+3)+0},
	{OWN_KTRRIKK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+3)+1},
	{OWN_DROCUS_SPIDERFRIEND, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+3)+2},
	{OWN_FUNGUS_GIANT_SLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+3)+3},
	{OWN_DELANTHA, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+4)+0},
	{OWN_SOLVISTANI_THE_RANGER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+4)+1},
	{OWN_XORIL_THE_SLOW, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+4)+2},
	{OWN_AEON_FLUX, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+4)+3},
	{OWN_XARILLUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+5)+0},
	{OWN_EGBERT_THE_OLD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+5)+1},
	{OWN_VALINDRA_THE_PROUD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+5)+2},
	{OWN_TAEN_THE_ALCHEMIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+5)+3},
	{OWN_KELDORN_THE_GRAND, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+6)+0},
	{OWN_PHILANTHROPUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+6)+1},
	{OWN_AGNAR_THE_ENCHANTRESS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+6)+2},
	{OWN_BULIANCE_THE_NECROMANCER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+6)+3},
	{OWN_CHARITY_THE_NECROMANCER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+7)+0},
	{OWN_PUGNACIOUS_THE_PUGILIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+7)+1},
	{OWN_FOOTSORE_THE_LUCKY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+7)+2},
	{OWN_SIDRIA_LIGHFINGERED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+7)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+8)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+8)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+8)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+8)+3},
	{OWN_PORCINA_THE_OBESE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+9)+0},
	{OWN_GLARUNA_BRANDYBREATH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+9)+1},
	{OWN_FURFACE_YEEK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+9)+2},
	{OWN_BALD_OGGIN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+9)+3},
	{OWN_ALDOUS_THE_SLEEPY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+10)+0},
	{OWN_GRUNDY_THE_TALL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+10)+1},
	{OWN_GOBBLEGUTS_THUNDERBREATH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+10)+2},
	{OWN_SILVERSCALE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+10)+3},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+11)+0},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+11)+1},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+11)+2},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_HLANTH+11)+3},
	{OWN_HANEKA_THE_SMALL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+0)+0},
	{OWN_LOIRIN_THE_MAD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+0)+1},
	{OWN_WUTO_POISONBREATH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+0)+2},
	{OWN_ARAAKA_THE_ROTUND, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+0)+3},
	{OWN_HORBAG_THE_UNCLEAN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+1)+0},
	{OWN_ELELEN_THE_TELEPATH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+1)+1},
	{OWN_ISEDRELIAS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+1)+2},
	{OWN_VEGNAR_ONE_EYE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+1)+3},
	{OWN_NADOC_THE_STRONG, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+2)+0},
	{OWN_ERAMOG_THE_WEAK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+2)+1},
	{OWN_EOWILITH_THE_FAIR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+2)+2},
	{OWN_HUIMOG_BALROG_SLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+2)+3},
	{OWN_IBENIDD_THE_CHASTE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+3)+0},
	{OWN_ERIDISH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+3)+1},
	{OWN_VRUDUSH_THE_SHAMAN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+3)+2},
	{OWN_HAOB_THE_BERSERKER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+3)+3},
	{OWN_CAYD_THE_SWEET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+4)+0},
	{OWN_FULIR_THE_DARK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+4)+1},
	{OWN_DOMLI_THE_HUMBLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+4)+2},
	{OWN_YAARJUKKA_DEMONSPAWN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+4)+3},
	{OWN_VUIRAK_THE_WIZARD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+5)+0},
	{OWN_MADISH_THE_SMART, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+5)+1},
	{OWN_FALEBRIMBOR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+5)+2},
	{OWN_FELIL_GAND_THE_SUBTLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+5)+3},
	{OWN_RIATHO_THE_JUGGLER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+6)+0},
	{OWN_JANAAKA_THE_SHIFTY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+6)+1},
	{OWN_CINA_THE_ROGUE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+6)+2},
	{OWN_ARUNIKKI_GREATCLAW, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+6)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+7)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+7)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+7)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+7)+3},
	{OWN_ASUUNU_THE_LEARNED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+8)+0},
	{OWN_PRIRAND_THE_DEAD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+8)+1},
	{OWN_RONAR_THE_IRON, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+8)+2},
	{OWN_GALIL_GAMIR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+8)+3},
	{OWN_TOGDUSH_THE_QUIET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+9)+0},
	{OWN_VURJAANA_THE_STUDIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+9)+1},
	{OWN_YIETRAM_THE_LUMINOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+9)+2},
	{OWN_THRADRIERITH, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+9)+3},
	{OWN_ETHERAA_THE_FURIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+10)+0},
	{OWN_PAETLAN_THE_ALCOHOLIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+10)+1},
	{OWN_DRANG, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+10)+2},
	{OWN_BARBAG_THE_SLY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+10)+3},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+11)+0},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+11)+1},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+11)+2},
	{OWN_HALL_OF_RECORDS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_ILEK+11)+3},
	{OWN_POOGOR_THE_DUMB, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+0)+0},
	{OWN_FELORFILIAND, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+0)+1},
	{OWN_MAROKA_THE_AGED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+0)+2},
	{OWN_SASIN_THE_BOLD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+0)+3},
	{OWN_RODISH_THE_CHAOTIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+1)+0},
	{OWN_HESIN_SWORDMASTER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+1)+1},
	{OWN_ELVERERITH_THE_CHEAT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+1)+2},
	{OWN_ZZATHATH_THE_IMP, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+1)+3},
	{OWN_PEADUS_THE_CRUEL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+2)+0},
	{OWN_VAMOG_SLAYER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+2)+1},
	{OWN_HOOSHNAK_THE_VICIOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+2)+2},
	{OWN_BALENN_WAR_DANCER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+2)+3},
	{OWN_PROOGDISH_THE_YOUTHFULL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+3)+0},
	{OWN_LUMWISE_THE_MAD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+3)+1},
	{OWN_MUIRT_THE_VIRTUOUS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+3)+2},
	{OWN_DARDOBARD_THE_WEAK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+3)+3},
	{OWN_GELARALDOR_THE_HERBMASTER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+4)+0},
	{OWN_OLELALDAN_THE_WISE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+4)+1},
	{OWN_FTHOGLO_THE_DEMONICIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+4)+2},
	{OWN_DRIDASH_THE_ALCHEMIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+4)+3},
	{OWN_NELIR_THE_STRONG, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+5)+0},
	{OWN_LIGNUS_THE_PUNGENT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+5)+1},
	{OWN_TILBA, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+5)+2},
	{OWN_MYRILDRIC_THE_WEALTHY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+5)+3},
	{OWN_THALEGORD_THE_SHAMAN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+6)+0},
	{OWN_CTHOALOTH_THE_MYSTIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+6)+1},
	{OWN_IBELI_THE_ILLUSIONIST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+6)+2},
	{OWN_HETO_THE_NECROMANCER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+6)+3},
	{OWN_CHAEAND_THE_POOR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+7)+0},
	{OWN_AFARDORF_THE_BRIGAND, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+7)+1},
	{OWN_LATHAXL_THE_GREEDY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+7)+2},
	{OWN_FALAREWYN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+7)+3},
	{OWN_VOSUR_THE_WRINKLED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+8)+0},
	{OWN_ARAORD_THE_HANDSOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+8)+1},
	{OWN_THERADFRID_THE_LOSER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+8)+2},
	{OWN_ONE_LEGGED_EROOLO, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+8)+3},
	{OWN_RORBAG_BOOK_EATER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+9)+0},
	{OWN_KIRIARIKIRK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+9)+1},
	{OWN_RILIN_THE_QUIET, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+9)+2},
	{OWN_ISUNG_THE_LORD, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+9)+3},
	{OWN_KIRAKAK, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+10)+0},
	{OWN_NAFUR_THE_WOODEN, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+10)+1},
	{OWN_GRARAK_THE_HOSPITABLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+10)+2},
	{OWN_LONA_THE_CHARISMATIC, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+10)+3},
	{OWN_HERRANYTH_THE_RUTHLESS, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+11)+0},
	{OWN_GAGRIN_MONEYLENDER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+11)+1},
	{OWN_THRAMBOR_THE_GRUBBY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+11)+2},
	{OWN_DERIGRIN_THE_HONEST, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_INGANOK+11)+3},
	{OWN_ABIEMAR_THE_PEASANT, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+0)+0},
	{OWN_HURK_THE_POOR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+0)+1},
	{OWN_SOALIN_THE_WRETCHED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+0)+2},
	{OWN_MERULLA_THE_HUMBLE, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+0)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+1)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+1)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+1)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+1)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+2)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+2)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+2)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+2)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+3)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+3)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+3)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+3)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+4)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+4)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+4)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+4)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+5)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+5)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+5)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+5)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+6)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+6)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+6)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+6)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+7)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+7)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+7)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+7)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+8)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+8)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+8)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+8)+3},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+9)+0},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+9)+1},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+9)+2},
	{OWN_YOUR_HOME, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+9)+3},
	{OWN_CREDIRIC_THE_BREWER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+10)+0},
	{OWN_NYDUDUS_THE_SLOW, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+10)+1},
	{OWN_BAURK_THE_BUSY, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+10)+2},
	{OWN_SEVIRAS_THE_MINDCRAFTER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+10)+3},
	{OWN_MUNK_THE_BARTERER, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+11)+0},
	{OWN_GADRIALDUR_THE_FAIR, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+11)+1},
	{OWN_NINAR_THE_STOOPED, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+11)+2},
	{OWN_ADIRATH_THE_UNMAGICAL, MAX_OWNERS*(MAX_STORES_PER_TOWN*TOWN_NIR+11)+3},
};

/*
 * Define the flags for the current version globally.
 */
const u16b sf_flags_now = 0x00000000
#ifdef SF_SKILL_BASE
	| SF_SKILL_BASE
#endif
#ifdef SF_16_IDENT
	| SF_16_IDENT
#endif
#ifdef SF_CURSE
	| SF_CURSE
#endif
#ifdef SF_Q_SAVE
	| SF_Q_SAVE
#endif
#ifdef SF_DEATHEVENTTEXT
	| SF_DEATHEVENTTEXT
#endif
#ifdef SF_QUEST_UNKNOWN
	| SF_QUEST_UNKNOWN
#endif
#ifdef SF_3D_WINPRI
	| SF_3D_WINPRI
#endif
#ifdef SF_16_CAVE_FLAG
	| SF_16_CAVE_FLAG
#endif
#ifdef SF_SAVE_MAX_SKILLS
	| SF_SAVE_MAX_SKILLS
#endif
#ifdef SF_K_INFO_1
	| SF_K_INFO_1
#endif
#ifdef SF_QUEST_KNOWN
	| SF_QUEST_KNOWN
#endif
#ifdef SF_R_INFO_1
	| SF_R_INFO_1
#endif
#ifdef SF_QUEST_DIRECT
	| SF_QUEST_DIRECT
#endif
	;

/*
 * Convert an object table from one version to another.
 * It returns what k_idx in version from_v is equivalent to in to_v.
 */
s16b convert_k_idx(s16b idx, u32b from_v, u32b to_v)
{
	/* Assume the oldest version in the absence of relevant flags. */
	uint i, from, to, max = N_ELEMENTS(object_version)-1;
	int max_distro;

	/* Find the newest version flag which is included in each of old and new. */
	for (i = 0, from = to = max; i < max; i++)
	{
		if (from_v & object_version[i]) from = i;
		if (to_v & object_version[i]) to = i;
	}

	/* No change. */
	if (from == to) return idx;

	/* Return the new version of the given object. */
	for (i = 0; i < N_ELEMENTS(object_table); i++)
	{
		if (object_table[i][from] != idx) continue;
		return object_table[i][to];
	}

	/*
	 * Maintain the user area's integrity.
	 * OBJ_MAX_DISTRO must be a term in the above table.
	 */
	max_distro = convert_k_idx(OBJ_MAX_DISTRO, sf_flags_now, from_v);
	if (idx > max_distro)
	{
		return idx - max_distro +
			convert_k_idx(OBJ_MAX_DISTRO, sf_flags_now, to_v);
	}
	/* 
	 * As anything can happen to strange indices in the system area, convert
	 * them to bad objects in order for them to be safely removed later.
	 */
	else
	{
		return -1;
	}
}

/*
 * Convert a monster table from one version to another.
 * It returns what idx in version from_v is equivalent to in to_v.
 */
s16b convert_r_idx(s16b idx, u32b from_v, u32b to_v)
{
	/* Assume the oldest version in the absence of relevant flags. */
	uint i, from, to, max = N_ELEMENTS(monster_version)-1;
	int max_distro;

	/* Find the newest version flag which is included in each of old and new. */
	for (i = 0, from = to = max; i < max; i++)
	{
		if (from_v & monster_version[i]) from = i;
		if (to_v & monster_version[i]) to = i;
	}

	/* No change. */
	if (from == to) return idx;

	/* Return the new version of the given monster. */
	for (i = 0; i < N_ELEMENTS(monster_table); i++)
	{
		if (monster_table[i][from] != idx) continue;
		return monster_table[i][to];
	}

	/*
	 * Maintain the user area's integrity.
	 * OBJ_MAX_DISTRO must be a term in the above table.
	 */
	max_distro = convert_r_idx(MON_MAX_DISTRO, sf_flags_now, from_v);
	if (idx > max_distro)
	{
		return idx - max_distro +
			convert_r_idx(MON_MAX_DISTRO, sf_flags_now, to_v);
	}
	/* 
	 * As anything can happen to strange indices in the system area, convert
	 * them to bad monsters in order for them to be safely removed later.
	 */
	else
	{
		return -1;
	}
}

/*
 * Convert a shop owner table from one version to another.
 * It returns what idx in version from_v is equivalent to in to_v.
 *
 * Note that the version 0 table actually uses values of
 * MAX_OWNERS*(shop number)+owner
 */
s16b convert_owner(s16b idx, u32b from_v, u32b to_v)
{
	/* Assume the oldest version in the absence of relevant flags. */
	uint i, from, to, max = N_ELEMENTS(owner_version)-1;
	int max_distro;

	/* Find the newest version flag which is included in each of old and new. */
	for (i = 0, from = to = max; i < max; i++)
	{
		if (from_v & owner_version[i]) from = i;
		if (to_v & owner_version[i]) to = i;
	}

	/* No change. */
	if (from == to) return idx;

	/* Return the new version of the given monster. */
	for (i = 0; i < N_ELEMENTS(owner_table); i++)
	{
		if (owner_table[i][from] != idx) continue;
		return owner_table[i][to];
	}

	/*
	 * Maintain the user area's integrity.
	 * OBJ_MAX_DISTRO must be a term in the above table.
	 */
	max_distro = convert_r_idx(OWNER_MAX_DISTRO, sf_flags_now, from_v);
	if (idx > max_distro)
	{
		return idx - max_distro +
			convert_r_idx(OWNER_MAX_DISTRO, sf_flags_now, to_v);
	}
	/* 
	 * As anything can happen to strange indices in the system area, convert
	 * them to bad monsters in order for them to be safely removed later.
	 */
	else
	{
		return -1;
	}
}

/*
 * Determine the current version number based on compile-time options.
 */
void current_version(u16b *flags, byte *major, byte *minor, byte *patch)
{
	if (flags) (*flags) = sf_flags_now;
	if (major) (*major) = SFM_SPECIAL;
	if (minor) (*minor) = (*flags)/256;
	if (patch) (*patch) = (*flags)%256;
}

