#
# Borland C++ IDE generated makefile
# Generated 4/12/98 at 9:11:23 PM 
#
.AUTODEPEND


#
# Borland C++ tools
#
IMPLIB  = Implib
BCC32   = Bcc32 +BccW32.cfg 
BCC32I  = Bcc32i +BccW32.cfg 
TLINK32 = TLink32
ILINK32 = Ilink32
TLIB    = TLib
BRC32   = Brc32
TASM32  = Tasm32
#
# IDE macros
#


#
# Options
#
IDE_LinkFLAGS32 =  -LD:\BC5\LIB
IDE_ResFLAGS32 = 
LinkerLocalOptsAtW32_dcbrangbandbrangbanddexe =  -Tpe -aa -V4.0 -c -LD:\BC5\LIB
ResLocalOptsAtW32_dcbrangbandbrangbanddexe = 
BLocalOptsAtW32_dcbrangbandbrangbanddexe = 
CompInheritOptsAt_dcbrangbandbrangbanddexe = -ID:\BC5\INCLUDE -DSTRICT;_OWLPCH
LinkerInheritOptsAt_dcbrangbandbrangbanddexe = -x
LinkerOptsAt_dcbrangbandbrangbanddexe = $(LinkerLocalOptsAtW32_dcbrangbandbrangbanddexe)
ResOptsAt_dcbrangbandbrangbanddexe = $(ResLocalOptsAtW32_dcbrangbandbrangbanddexe)
BOptsAt_dcbrangbandbrangbanddexe = $(BLocalOptsAtW32_dcbrangbandbrangbanddexe)

#
# Dependency List
#
Dep_rangband = \
   d:\rangband\rangband.exe

rangband : BccW32.cfg $(Dep_rangband)
  echo MakeNode

Dep_dcbrangbandbrangbanddexe = \
   random.obj\
   angband.res\
   tables.obj\
   z-util.obj\
   z-term.obj\
   z-rand.obj\
   z-form.obj\
   xtra2.obj\
   xtra1.obj\
   wizard2.obj\
   wizard1.obj\
   variable.obj\
   util.obj\
   z-virt.obj\
   birth.obj\
   spells2.obj\
   spells1.obj\
   save.obj\
   readdib.obj\
   object2.obj\
   object1.obj\
   monster2.obj\
   monster1.obj\
   melee2.obj\
   melee1.obj\
   main-xxx.obj\
   main-xaw.obj\
   main-x11.obj\
   main-win.obj\
   main-vme.obj\
   main-sla.obj\
   main-mac.obj\
   main-ibm.obj\
   main-gcu.obj\
   main-emx.obj\
   main-cap.obj\
   main-ami.obj\
   main-acn.obj\
   main.obj\
   load.obj\
   init2.obj\
   init1.obj\
   generate.obj\
   files.obj\
   dungeon.obj\
   cmd6.obj\
   cmd5.obj\
   cmd4.obj\
   cmd3.obj\
   cmd2.obj\
   cmd1.obj\
   cave.obj\
   store.obj

d:\rangband\rangband.exe : $(Dep_dcbrangbandbrangbanddexe)
  $(ILINK32) @&&|
 /v $(IDE_LinkFLAGS32) $(LinkerOptsAt_dcbrangbandbrangbanddexe) $(LinkerInheritOptsAt_dcbrangbandbrangbanddexe) +
D:\BC5\LIB\c0w32.obj+
random.obj+
tables.obj+
z-util.obj+
z-term.obj+
z-rand.obj+
z-form.obj+
xtra2.obj+
xtra1.obj+
wizard2.obj+
wizard1.obj+
variable.obj+
util.obj+
z-virt.obj+
birth.obj+
spells2.obj+
spells1.obj+
save.obj+
readdib.obj+
object2.obj+
object1.obj+
monster2.obj+
monster1.obj+
melee2.obj+
melee1.obj+
main-xxx.obj+
main-xaw.obj+
main-x11.obj+
main-win.obj+
main-vme.obj+
main-sla.obj+
main-mac.obj+
main-ibm.obj+
main-gcu.obj+
main-emx.obj+
main-cap.obj+
main-ami.obj+
main-acn.obj+
main.obj+
load.obj+
init2.obj+
init1.obj+
generate.obj+
files.obj+
dungeon.obj+
cmd6.obj+
cmd5.obj+
cmd4.obj+
cmd3.obj+
cmd2.obj+
cmd1.obj+
cave.obj+
store.obj
$<,$*
D:\BC5\LIB\owlwf.lib+
D:\BC5\LIB\bidsf.lib+
D:\BC5\LIB\import32.lib+
D:\BC5\LIB\cw32.lib

angband.res

|
random.obj :  random.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ random.c
|

angband.res :  angband.rc
  $(BRC32) -R @&&|
 $(IDE_ResFLAGS32) $(ROptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe)  -FO$@ angband.rc
|
tables.obj :  tables.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ tables.c
|

z-util.obj :  z-util.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ z-util.c
|

z-term.obj :  z-term.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ z-term.c
|

z-rand.obj :  z-rand.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ z-rand.c
|

z-form.obj :  z-form.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ z-form.c
|

xtra2.obj :  xtra2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ xtra2.c
|

xtra1.obj :  xtra1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ xtra1.c
|

wizard2.obj :  wizard2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ wizard2.c
|

wizard1.obj :  wizard1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ wizard1.c
|

variable.obj :  variable.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ variable.c
|

util.obj :  util.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ util.c
|

z-virt.obj :  z-virt.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ z-virt.c
|

birth.obj :  birth.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ birth.c
|

spells2.obj :  spells2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ spells2.c
|

spells1.obj :  spells1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ spells1.c
|

save.obj :  save.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ save.c
|

readdib.obj :  readdib.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ readdib.c
|

object2.obj :  object2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ object2.c
|

object1.obj :  object1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ object1.c
|

monster2.obj :  monster2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ monster2.c
|

monster1.obj :  monster1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ monster1.c
|

melee2.obj :  melee2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ melee2.c
|

melee1.obj :  melee1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ melee1.c
|

main-xxx.obj :  main-xxx.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-xxx.c
|

main-xaw.obj :  main-xaw.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-xaw.c
|

main-x11.obj :  main-x11.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-x11.c
|

main-win.obj :  main-win.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-win.c
|

main-vme.obj :  main-vme.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-vme.c
|

main-sla.obj :  main-sla.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-sla.c
|

main-mac.obj :  main-mac.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-mac.c
|

main-ibm.obj :  main-ibm.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-ibm.c
|

main-gcu.obj :  main-gcu.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-gcu.c
|

main-emx.obj :  main-emx.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-emx.c
|

main-cap.obj :  main-cap.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-cap.c
|

main-ami.obj :  main-ami.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-ami.c
|

main-acn.obj :  main-acn.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main-acn.c
|

main.obj :  main.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ main.c
|

load.obj :  load.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ load.c
|

init2.obj :  init2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ init2.c
|

init1.obj :  init1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ init1.c
|

generate.obj :  generate.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ generate.c
|

files.obj :  files.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ files.c
|

dungeon.obj :  dungeon.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ dungeon.c
|

cmd6.obj :  cmd6.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd6.c
|

cmd5.obj :  cmd5.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd5.c
|

cmd4.obj :  cmd4.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd4.c
|

cmd3.obj :  cmd3.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd3.c
|

cmd2.obj :  cmd2.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd2.c
|

cmd1.obj :  cmd1.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cmd1.c
|

cave.obj :  cave.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ cave.c
|

store.obj :  store.c
  $(BCC32) -P- -c @&&|
 $(CompOptsAt_dcbrangbandbrangbanddexe) $(CompInheritOptsAt_dcbrangbandbrangbanddexe) -o$@ store.c
|

# Compiler configuration file
BccW32.cfg : 
   Copy &&|
-w
-R
-v
-WM-
-vi
-H
-H=rangband.csm
-W
-H"owl\pch.h"
-O1
-g255
-j255
-w-dup
-w-aus
-f
-ff
-y-
-N-
-vi
-He
-v-
-R-
-k-
-wdpu
-w-pro
| $@


