# File: Makefile.ibm

# Purpose: Makefile support for "main-ibm.c" and Gnu C

# Note: Rename to "Makefile" before using
# Added extra targets: mrmarcel@eos.ncsu.edu (Mike Marcelais)
# Changed by rr9@inf.tu-dresden.de (Robert Ruehlmann)

OBJS = \
  z-util.o z-virt.o z-form.o z-rand.o z-term.o \
  variable.o tables.o util.o cave.o \
  object1.o object2.o monster1.o monster2.o \
  xtra1.o xtra2.o spells1.o spells2.o melee1.o melee2.o \
  load1.o load2.o save.o files.o \
  cmd1.o cmd2.o cmd3.o cmd4.o cmd5.o cmd6.o \
  store.o birth.o wizard1.o wizard2.o \
  generate.o dungeon.o init1.o init2.o

MAIN_OBJS = \
  main-ibm.o main.o


# Compiler

CC = gcc

# Compiler flags

CFLAGS = -Wall -O2 -s -DUSE_IBM -DHAS_USLEEP -DUSE_IBM_SVGA

# Libraries

LIBS = -lpc
GLIBS= -lalleg

# Name of Program

PROGRAM = angband.exe


all: angband.exe
	@echo All done.  Use 'make install' to copy them up one directory.

install: angband.exe
	copy angband.exe ..

# Generate binary file

angband.exe: $(MAIN_OBJS) libangb.a
	$(CC) $(CFLAGS) -o $@ $(MAIN_OBJS) libangb.a $(LIBS) $(GLIBS)

#
# Build the Angband function library
#

libangb.a: $(OBJS)
	ar rcv $@ $(OBJS)
	ranlib $@

# Compile source files

.c.o:
	$(CC) $(CFLAGS) -c $*.c


# Clean up

clean:
	del *.o
	del angband.exe
	del *.bin
	del libangb.a
