/*
 * Power descriptions (unthemed)
 * Themed descriptions will replace generic if applicable and available
 */
cptr pwr_desc[] =
{
        NULL ,
	"Absorb Mana From Air" ,
	"Alter Reality" ,
	"Far-Reaching Attack" ,
	"Powerful Attack" ,
	"Whirlwind Attack" ,
	"Uproot the Trees" ,
	"Basilisk Gaze" ,
	"Spear of Light" ,
	"Berserk Strength" ,
	"Blink" ,
	"Brain Smashing" ,
	"Breathe Acid" ,
	"Breathe Acid Bolt/Beam" ,
	"Breathe Chaos" ,
	"Breathe Chaos Bolt/Beam" ,
	"Breathe Cold" ,
	"Breathe Cold Bolt/Beam" ,
	"Breathe Confusion" ,
	"Breathe Freezing" ,
	"Breathe Darkness" ,
	"Breathe Darkness Bolt/Beam" ,
	"Breathe Disenchant" ,
	"Breathe Disenchant Bolt/Beam" ,
	"Breathe Lightning" ,
	"Breathe Lightning Beam" ,
	"Cloud of Fear" ,
	"Breathe Fire" ,
	"Breathe Fire Bolt/Beam" ,
	"Breathe Force" ,
	"Breathe Force Bolt/Beam" ,
	"Breathe Gravity" ,
	"Breathe Gravity Bolt/Beam" ,
	"Breathe Ice" ,
	"Breathe Inertia" ,
	"Breathe Inertia Bolt/Beam" ,
	"Breathe Light" ,
	"Breathe Light Bolt/Beam" ,
	"Breathe Raw Mana" ,
	"Breathe Mana Bolt/Beam" ,
	"Breathe Nether" ,
	"Breathe Nether Bolt/Beam" ,
	"Breathe Nexus" ,
	"Breathe Nexus Bolt/Beam" ,
	"Breathe Plasma" ,
	"Breathe Plasma Bolt/Beam" ,
	"Breathe Poison" ,
	"Breathe Poison Bolt/Beam" ,
	"Breathe Shards" ,
	"Breathe Bolt/Beam of Shards" ,
	"Roar Sound" ,
	"Roar Sound Bolt/Beam" ,
	"Breathe Time" ,
	"Breathe Time Bolt/Beam" ,
	"Breathe Winds" ,
	"Call Light" ,
	"Acid Bolt" ,
	"Frost Ball" ,
	"Frost Bolt" ,
	"Darkness Ball" ,
	"Darkness Storm" ,
	"Disenchantment Bolt" ,
	"Spark" ,
	"Ball Lightning" ,
	"Lightning" ,
	"Fire Ball" ,
	"Fire Bolt" ,
	"Fiery Lightning" ,
	"Ice Storm" ,
	"Ice Bolt" ,
	"Light Orb" ,
	"Magic Missile" ,
	"Mana Bolt " ,
	"Mana Bolt" ,
	"Mana Storm" ,
	"Death Orb" ,
	"Nether Bolt" ,
	"Nexus Storm" ,
	"Space Disruption" ,
	"Plasma Bolt" ,
	"Plasma Storm" ,
	"Stinking Cloud" ,
	"Whirlpool" ,
	"Waterfall" ,
	"Cyclone" ,
	"Wind Blast" ,
	"Confuse" ,
	"Cure Critital Wounds" ,
	"Cure Light Wounds" ,
	"Cure Serious Wounds" ,
	"Priest's Sacrifice" ,
	"Acolyte's Sacrifice" ,
	"Prophet's Sacrifice" ,
	"Believer's Sacrifice" ,
	"Detect All" ,
	"Detect Chaos" ,
	"Detect Evil" ,
	"Detect Law" ,
	"Detect Monsters" ,
	"Smell Treasure" ,
	"Dimensional Door" ,
	"Dispel Monsters" ,
	"Force Obey" ,
	"Enchant Weapon" ,
	"Examine Object" ,
	"Haste" ,
	"Heal" ,
	"Heal with Bones" ,
	"Heal Pet" ,
	"Merge Wall to Self" ,
	"Heroism" ,
	"Holy Smoke" ,
	"Identify" ,
	"Healing Light" ,
	"Crush the Dungeon" ,
	"Kindle the Fires" ,
	"Grow the Grass" ,
	"Freeze the Air" ,
	"Melt the Stone" ,
	"Raise the Trees" ,
	"Build the Walls" ,
	"Fill the Lake" ,
	"Oppose Cold" ,
	"Oppose Electricity" ,
	"Oppose Fire" ,
	"Sleep" ,
	"Project Chaos" ,
	"Call the Ice of Helcaraxe" ,
	"Project Disenchantment" ,
	"Spray Shards" ,
	"Mighty Roar" ,
	"Remembrance" ,
	"Resistance" ,
	"Restoration" ,
	"Scare" ,
	"Scare All" ,
	"Electric Discharge" ,
	"Shift Planes" ,
	"Shriek" ,
	"Slow" ,
	"Spawn" ,
	"Spit Acid" ,
	"Spit Poison" ,
	"*Healing*" ,
	"Steal" ,
	"Summon Maiar" ,
	"Summon Demon Commander" ,
	"Summon Dark Elf" ,
	"Summon Demon" ,
	"Summon Demon Summoner" ,
	"Summon Dragon" ,
	"Summon Ancient Dragon" ,
	"Summon Mature Dragons" ,
	"Summon Dragon Summoner" ,
	"Summon Elemental" ,
	"Summon Golem" ,
	"Summon Greater Demons" ,
	"Summon Ancient Dragons" ,
	"Summon Greater Undeads" ,
	"Summon Hydras" ,
	"Summon Lawful Creatures" ,
	"Summon Lich" ,
	"Melt the Wall to Magma" ,
	"Summon Ogres" ,
	"Summon Orcs" ,
	"Summon Spiders" ,
	"Summon Trolls" ,
	"Summon Ultimate Pets" ,
	"Summon Undead" ,
	"Summon Undead Dragons" ,
	"Summon Undead Summoner" ,
	"Summon Vortex" ,
	"Summon Demon Troops" ,
	"Summon Wight/Wraith" ,
	"Summon Yeeks" ,
	"Teleport" ,
	"Teleport Away" ,
	"Weave Webs" ,
	"Spit Webs" ,
	"Wonder" ,
	"Word of Destruction" ,
	"Word of Recall" 
};

