/*
 * Legal restrictions for "summon_specific()"
 */
#define SUMMON_MONSTER		0
#define SUMMON_ANT					11
#define SUMMON_SPIDER		12
#define SUMMON_HOUND			13
#define SUMMON_HYDRA			14
#define SUMMON_ANGEL			15
#define SUMMON_DEMON			16
#define SUMMON_UNDEAD		17
#define SUMMON_DRAGON		18
#define SUMMON_HI_UNDEAD		21
#define SUMMON_HI_DRAGON		22
#define SUMMON_AMBER			31
#define SUMMON_UNIQUE		32
#define SUMMON_BIZARRE1		33
#define SUMMON_BIZARRE2		34
#define SUMMON_BIZARRE3		35
#define SUMMON_BIZARRE4		36
#define SUMMON_BIZARRE5		37
#define SUMMON_BIZARRE6		38
#define SUMMON_CYBER			39
#define SUMMON_KIN			40
#define SUMMON_DAWN			41
#define SUMMON_ANIMAL		42
#define SUMMON_ANIMAL_RANGER	43
#define SUMMON_HI_UNDEAD_NO_UNIQUES			44
#define SUMMON_HI_DRAGON_NO_UNIQUES			45
#define SUMMON_NO_UNIQUES					46
#define SUMMON_PHANTOM		47
#define SUMMON_ELEMENTAL		48
#define SUMMON_SKULL			49
#define SUMMON_DOOM			50
#define SUMMON_HI_DOOM		51

