/* File: xtra3.c */

/*
 * Copyright (c) 2007 Kenneth Boyd.  This file is subject to the Boost license.

	http://www.boost.org/more/license_info.html
	Boost Software License - Version 1.0 - August 17th, 2003

	Permission is hereby granted, free of charge, to any person or organization
	obtaining a copy of the software and accompanying documentation covered by
	this license (the "Software") to use, reproduce, display, distribute,
	execute, and transmit the Software, and to prepare derivative works of the
	Software, and to permit third-parties to whom the Software is furnished to
	do so, all subject to the following:

	The copyright notices in the Software and this entire statement, including
	the above license grant, this restriction and the following disclaimer,
	must be included in all copies of the Software, in whole or in part, and
	all derivative works of the Software, unless such copies or derivative
	works are solely in the form of machine-executable object code generated by
	a source language processor.

	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
	IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
	FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
	SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
	FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
	ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
	DEALINGS IN THE SOFTWARE.
 */

#include "angband.h"

/*
 * Test to see if the character acts on a moronic command.
 * return true if the character does act on a moronic command.
 */
bool player_type::allow_moron() const	/* Strictly Boost-licensed */
{
	s16b INT = stat_use[A_INT];
	s16b WIS = stat_use[A_WIS];
	s16b STAT_PRODUCT = INT*WIS;
	s16b STAT_MAX = (INT<WIS) ? WIS : INT;

	/* animal intellect or wisdom...always */
	if (5>INT || 5>WIS) return TRUE;
	/* clinically moron or fool: linear check against better stat */
	else if (9>INT || 9>WIS) return 4>rand_int(STAT_MAX);

	/* reasonable INT and WIS: check against product */
	return 16>rand_int(STAT_PRODUCT);
}

