/*
 * File: list-player-flags.h
 * Purpose: Player race and class flags
 *
 * Fields:
 * symbol - the flag name
 * additional details in player_property.txt
 */

/* symbol */
PF(NONE)
PF(FAST_SHOT)
PF(BLESS_WEAPON)
PF(ZERO_FAIL)
PF(BEAM)
PF(CHOOSE_SPELLS)
PF(KNOW_MUSHROOM)
PF(KNOW_ZAPPER)
PF(SEE_ORE)
PF(NO_MANA)
PF(CHARM)
PF(UNLIGHT)
PF(STEAL)
PF(SHIELD_BASH)
PF(COMBAT_REGEN)
PF(ELEMENTAL_SPELLS)
PF(UNDEAD_POWERS)
PF(STEALTH_MODE)
PF(STEALING_IMPROV)
PF(MONSTER_SPELLS)
PF(MARTIAL_ARTS)
PF(FAST_THROW)
PF(BACK_STAB)
PF(ORC)
PF(TROLL)
PF(ANIMAL)
PF(GIANT)
PF(THUNDERLORD)
PF(DRAGON)
PF(HYDRA)
PF(SUMMON_SPELLS)
PF(SHAPECHANGE)
