/*
 * File: list-player-flags.h
 * Purpose: Player race and class flags
 */

/* symbol            descr */
PF(NONE,             "")
PF(EXTRA_SHOT,       "receive extra shots with tension bows at levels 20 and 40")
PF(BRAVERY_30,       "become immune to fear at level 30")
PF(BLESS_WEAPON,     "may only wield blessed or hafted weapons")
PF(CUMBER_GLOVE,     "have difficulty using magic with covered hands")
PF(ZERO_FAIL,        "may obtain a perfect success rate with magic")
PF(BEAM,             "frequently turn bolt spells into beams")
PF(CHOOSE_SPELLS,    "may choose their own spells to study")
PF(PSEUDO_ID_IMPROV, "get better at pseudo id with experience")
PF(ELEMENTAL_SPELLS, "get access to elemental spells")
PF(UNDEAD_POWERS,    "get access to undead powers")
PF(STEALTH_MODE,     "turn Searching Mode into Stealth Mode")
PF(STEALING_IMPROV,  "get better chance at stealing")
PF(SPEED_BONUS,      "get extra speed")
PF(MONSTER_SPELLS,   "get access to monster spells")
PF(MARTIAL_ARTS,     "may use fighting abilities when fighting barehanded")
PF(EXTRA_SHOTS,      "get more extra shots")
PF(EXTRA_MANA,       "get extra mana")
PF(BACK_STAB,        "deal extra damage to sleeping and fleeing creatures")
PF(ANTIMAGIC,        "are surrounded by an antimagic field")
PF(KNOW_MUSHROOM,    "easily recognize mushrooms")
PF(KNOW_ZAPPER,      "easily recognize magic devices")
PF(SEE_ORE,          "can sense ore in the walls")
PF(ORC,              "belong to the Orc race")
PF(TROLL,            "belong to the Troll race")
PF(ANIMAL,           "belong to the Animal race")
PF(GIANT,            "belong to the Giant race")
PF(THUNDERLORD,      "belong to the Thunderlord race")
PF(DRAGON,           "belong to the Dragon race")
PF(SUMMON_SPELLS,    "get access to summon spells")
