/*
 * File: list-object-flags.h
 * Purpose: Object flags for all objects
 *
 * Each sustain flag (SUST_*) has a matching stat in src/list-stats.h,
 * which should be at the same index in that file as the sustain in this file (plus one for OF_NONE).
 *
 * Flag properties are defined in lib/gamedata/object_property.txt
 */

OF(NONE)
OF(SUST_STR)
OF(SUST_INT)
OF(SUST_WIS)
OF(SUST_DEX)
OF(SUST_CON)
OF(PROT_FEAR)
OF(PROT_BLIND)
OF(PROT_CONF)
OF(PROT_STUN)
OF(SLOW_DIGEST)
OF(FEATHER)
OF(REGEN)
OF(SEE_INVIS)
OF(FREE_ACT)
OF(HOLD_LIFE)
OF(IMPACT)
OF(BLESSED)
OF(BURNS_OUT)
OF(TAKES_FUEL)
OF(NO_FUEL)
OF(IMPAIR_HP)
OF(IMPAIR_MANA)
OF(AFRAID)
OF(NO_TELEPORT)
OF(AGGRAVATE)
OF(DRAIN_EXP)
OF(STICKY)
OF(FRAGILE)
OF(LIGHT_1)
OF(LIGHT_2)
OF(LIGHT_3)
OF(DIG_1)
OF(DIG_2)
OF(DIG_3)
OF(EXPLODE)
OF(KNOWLEDGE)
OF(AMMO_MAGIC)
OF(NO_ACTIVATION)
OF(ESP_ANIMAL)
OF(ESP_EVIL)
OF(ESP_UNDEAD)
OF(ESP_DEMON)
OF(ESP_ORC)
OF(ESP_TROLL)
OF(ESP_GIANT)
OF(ESP_DRAGON)
OF(ESP_ALL)
OF(ESP_RADIUS)
