/*
 * File: list-mon-spells.h
 * Purpose: List of monster spell flags
 *
 * Fields:
 * name - spell name
 * type - spell type
 * desc - textual description
 * cap - damage cap
 * div - damage divisor (monster hp / this)
 * gf - projection type for project() functions
 * msgt - flag for message colouring
 * save - does this spell allow a saving throw?
 * hit - to-hit chance (100 = always, 0 = never)
 * verb - description of attack
 * base_dam - raw damage (random_value struct)
 * rlev_dam - monster-level-dependent damage (random_value)
 * blind_verb - description of unseen attacks
 * what - special message
 */

/* name  type  desc  cap  div  gf  msgt  save  hit  verb  base_dam  rlev_dam  blind_verb  what */
RSF(NONE, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(SHRIEK, RST_ANNOY, "shriek", 0, 0, 0, MSG_SHRIEK, FALSE, 100, "makes a high-pitched", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "shrieks", NULL)
RSF(ARROW_X, RST_BOLT|RST_MISSILE, "seeker arrow", 0, 0, GF_ARROW_X, 0, FALSE, 50, "fires a", RV(0, 9, 6, 0), RV(0, 0, 0, 0), "fires an arrow", "annihilated")
RSF(ARROW_1, RST_BOLT|RST_MISSILE, "shot", 0, 0, GF_ARROW_1, 0, FALSE, 40, "fires a", RV(0, 1, 6, 0), RV(0, 0, 0, 0), "fires a shot", "annihilated")
RSF(ARROW_2, RST_BOLT|RST_MISSILE, "arrow", 0, 0, GF_ARROW_2, 0, FALSE, 40, "fires an", RV(0, 3, 6, 0), RV(0, 0, 0, 0), "fires an arrow", "annihilated")
RSF(ARROW_3, RST_BOLT|RST_MISSILE, "bolt", 0, 0, GF_ARROW_3, 0, FALSE, 50, "fires a", RV(0, 5, 6, 0), RV(0, 0, 0, 0), "fires a bolt", "annihilated")
RSF(ARROW_4, RST_BOLT|RST_MISSILE, "missile", 0, 0, GF_ARROW_4, 0, FALSE, 50, "fires a", RV(0, 7, 6, 0), RV(0, 0, 0, 0), "fires a missile", "annihilated")
RSF(BR_ACID, RST_BREATH, "acid", 1600, 3, GF_ACID, MSG_BR_ACID, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "hisses", "vaporized")
RSF(BR_ELEC, RST_BREATH, "lightning", 1600, 3, GF_ELEC, MSG_BR_ELEC, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "crackles", "vaporized")
RSF(BR_FIRE, RST_BREATH, "fire", 1600, 3, GF_FIRE, MSG_BR_FIRE, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "roars", "vaporized")
RSF(BR_COLD, RST_BREATH, "frost", 1600, 3, GF_COLD, MSG_BR_FROST, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "wooshes", "vaporized")
RSF(BR_POIS, RST_BREATH, "poison", 800, 3, GF_POIS, MSG_BR_GAS, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "retches", "vaporized")
RSF(BR_NETH, RST_BREATH, "nether", 550, 6, GF_NETHER, MSG_BR_NETHER, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "groans", "vaporized")
RSF(BR_LIGHT, RST_BREATH, "light", 400, 6, GF_LIGHT, MSG_BR_LIGHT, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_DARK, RST_BREATH, "darkness", 400, 6, GF_DARK, MSG_BR_DARK, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_SOUN, RST_BREATH, "sound", 500, 6, GF_SOUND, MSG_BR_SOUND, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_CHAO, RST_BREATH, "chaos", 500, 6, GF_CHAOS, MSG_BR_CHAOS, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_DISE, RST_BREATH, "disenchantment", 500, 6, GF_DISEN, MSG_BR_DISEN, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_NEXU, RST_BREATH, "nexus", 400, 6, GF_NEXUS, MSG_BR_NEXUS, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_TIME, RST_BREATH, "time", 150, 3, GF_TIME, MSG_BR_TIME, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_INER, RST_BREATH, "inertia", 200, 6, GF_INERT, MSG_BR_INERTIA, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_GRAV, RST_BREATH, "gravity", 200, 3, GF_GRAVITY, MSG_BR_GRAVITY, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_SHAR, RST_BREATH, "shards", 500, 6, GF_SHARD, MSG_BR_SHARDS, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_PLAS, RST_BREATH, "hellfire", 150, 6, GF_PLASMA, MSG_BR_PLASMA, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_WALL, RST_BREATH, "force", 200, 6, GF_FORCE, MSG_BR_FORCE, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_MANA, RST_BREATH, "raw magic", 250, 3, GF_MANA, 0, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "breathes", "vaporized")
RSF(BR_WATE, RST_BREATH, "water", 300, 3, GF_WATER, MSG_BR_WATE, FALSE, 100, "breathes", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "gurgles", "vaporized")
RSF(BOULDER, RST_BOLT|RST_MISSILE, "boulder", 0, 0, GF_BOULDER, 0, FALSE, 60, "hurls a", RV(0, 1, 12, 0), RV(0, 14, 12, 1), "hurls a boulder", "annihilated")
RSF(BA_ACID, RST_BALL, "acid", 0, 0, GF_ACID, 0, FALSE, 100, "casts a ball of", RV(15, 0, 0, 0), RV(0, 1, 300, 0), "mumbles", "vaporized")
RSF(BA_ELEC, RST_BALL, "lightning", 0, 0, GF_ELEC, 0, FALSE, 100, "casts a ball of", RV(8, 0, 0, 0), RV(0, 1, 150, 0), "mumbles", "vaporized")
RSF(BA_FIRE, RST_BALL, "fire", 0, 0, GF_FIRE, 0, FALSE, 100, "casts a ball of", RV(10, 0, 0, 0), RV(0, 1, 350, 0), "mumbles", "vaporized")
RSF(BA_COLD, RST_BALL, "frost", 0, 0, GF_COLD, 0, FALSE, 100, "casts a ball of", RV(10, 0, 0, 0), RV(0, 1, 150, 0), "mumbles", "vaporized")
RSF(BA_POIS, RST_BALL, "poison", 0, 0, GF_POIS, 0, FALSE, 100, "creates a cloud of", RV(0, 12, 2, 0), RV(0, 0, 0, 0), "mumbles", "vaporized")
RSF(BA_NETH, RST_BALL, "nether", 0, 0, GF_NETHER, 0, FALSE, 100, "casts a ball of", RV(50, 10, 10, 0), RV(100, 0, 0, 0), "mumbles", "vaporized")
RSF(BA_WATE, RST_BALL, "water", 0, 0, GF_WATER, 0, FALSE, 100, "creates a whirlpool of", RV(50, 0, 0, 0), RV(0, 1, 250, 0), "gurgles", "vaporized")
RSF(BA_MANA, RST_BALL, "raw magic", 0, 0, GF_MANA, 0, FALSE, 100, "invokes a storm of", RV(0, 10, 10, 0), RV(500, 0, 0, 0), "screams loudly", "vaporized")
RSF(BA_DARK, RST_BALL, "darkness", 0, 0, GF_DARK, 0, FALSE, 100, "invokes a storm of", RV(0, 10, 10, 0), RV(500, 0, 0, 0), "mumbles loudly", "vaporized")
RSF(DRAIN_MANA, RST_ANNOY, "mana away", 0, 0, 0, 0, FALSE, 100, "drains your", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "moans", NULL)
RSF(MIND_BLAST, RST_ATTACK|RST_ANNOY|RST_SPECIAL, "psionic energy", 0, 0, GF_BLAST, 0, RSV_SKILL|RSV_UNDEAD, 100, "gazes at you with", RV(0, 8, 8, 0), RV(0, 0, 0, 0), "focuses on your mind", "turned into an unthinking vegetable")
RSF(BRAIN_SMASH, RST_ATTACK|RST_ANNOY|RST_SPECIAL, "psionic energy", 0, 0, GF_SMASH, 0, RSV_SKILL|RSV_UNDEAD, 100, "smashes you with", RV(0, 12, 15, 0), RV(0, 0, 0, 0), "focuses on your mind", "turned into an unthinking vegetable")
RSF(CAUSE_1, RST_ATTACK|RST_SPECIAL, "curses", 0, 0, GF_CURSE, 0, RSV_SKILL|RSV_UNDEAD, 100, "points at you and", RV(0, 3, 8, 0), RV(0, 0, 0, 0), "mumbles", "annihilated")
RSF(CAUSE_2, RST_ATTACK|RST_SPECIAL, "curses horribly", 0, 0, GF_CURSE, 0, RSV_SKILL|RSV_UNDEAD, 100, "points at you and", RV(0, 8, 8, 0), RV(0, 0, 0, 0), "mumbles", "annihilated")
RSF(CAUSE_3, RST_ATTACK|RST_SPECIAL, "incants terribly", 0, 0, GF_CURSE, 0, RSV_SKILL|RSV_UNDEAD, 100, "points at you and", RV(0, 10, 15, 0), RV(0, 0, 0, 0), "mumbles loudly", "annihilated")
RSF(CAUSE_4, RST_ATTACK|RST_SPECIAL, "screams the word 'DIE!'", 0, 0, GF_CURSE2, 0, RSV_SKILL|RSV_UNDEAD, 100, "points at you and", RV(0, 15, 15, 0), RV(0, 0, 0, 0), "screams the word 'DIE!'", "annihilated")
RSF(BO_ACID, RST_BOLT, "acid", 0, 0, GF_ACID, 0, FALSE, 100, "casts a bolt of", RV(0, 7, 8, 0), RV(33, 0, 0, 0), "mumbles", "annihilated")
RSF(BO_ELEC, RST_BOLT, "lightning", 0, 0, GF_ELEC, 0, FALSE, 100, "casts a bolt of", RV(0, 4, 8, 0), RV(33, 0, 0, 0), "mumbles", "annihilated")
RSF(BO_FIRE, RST_BOLT, "fire", 0, 0, GF_FIRE, 0, FALSE, 100, "casts a bolt of", RV(0, 9, 8, 0), RV(33, 0, 0, 0), "mumbles", "annihilated")
RSF(BO_COLD, RST_BOLT, "frost", 0, 0, GF_COLD, 0, FALSE, 100, "casts a bolt of", RV(0, 6, 8, 0), RV(33, 0, 0, 0), "mumbles", "annihilated")
RSF(BO_NETH, RST_BOLT, "nether", 0, 0, GF_NETHER, 0, FALSE, 100, "casts a bolt of", RV(30, 5, 5, 0), RV(150, 0, 0, 0), "mumbles", "annihilated")
RSF(BO_WATE, RST_BOLT, "water", 0, 0, GF_WATER, 0, FALSE, 100, "fires a jet of", RV(0, 10, 10, 0), RV(100, 0, 0, 0), "gurgles", "annihilated")
RSF(BO_MANA, RST_BOLT, "raw magic", 0, 0, GF_MANA, 0, FALSE, 100, "casts a bolt of", RV(50, 0, 0, 0), RV(0, 1, 350, 0), "screams", "annihilated")
RSF(BO_PLAS, RST_BOLT, "hellfire", 0, 0, GF_PLASMA, 0, FALSE, 100, "casts a bolt of", RV(10, 8, 7, 0), RV(100, 0, 0, 0), "screams", "annihilated")
RSF(BO_ICEE, RST_BOLT, "ice", 0, 0, GF_ICE, 0, FALSE, 100, "shoots a spear of", RV(0, 6, 6, 0), RV(100, 0, 0, 0), "mumbles", "annihilated")
RSF(MISSILE, RST_BOLT, "magic missile", 0, 0, GF_MISSILE, 0, FALSE, 100, "fires a", RV(0, 2, 6, 0), RV(33, 0, 0, 0), "mumbles", "annihilated")
RSF(SCARE, RST_ANNOY|RST_SPECIAL, "scary horrors", 0, 0, GF_TURN_ALL, MSG_CAST_FEAR, RSV_SKILL|RSV_UNDEAD, 100, "conjures up", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "makes scary noises", "annihilated")
RSF(BLIND, RST_ANNOY|RST_SPECIAL, "blinding flash", 0, 0, GF_BLIND, 0, RSV_SKILL|RSV_UNDEAD, 100, "sets off a", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", "annihilated")
RSF(CONF, RST_ANNOY|RST_SPECIAL, "weird things", 0, 0, GF_OLD_CONF, 0, RSV_SKILL|RSV_UNDEAD, 100, "conjures up", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "messes with your mind", "annihilated")
RSF(SLOW, RST_ANNOY|RST_HASTE|RST_SPECIAL, "move slowly", 0, 0, GF_OLD_SLOW, 0, RSV_SKILL|RSV_UNDEAD, 100, "tries to make you", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", "annihilated")
RSF(HOLD, RST_ANNOY|RST_HASTE|RST_SPECIAL, "stop moving", 0, 0, GF_OLD_SLEEP, 0, RSV_SKILL|RSV_UNDEAD, 100, "tries to make you", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", "annihilated")
RSF(HASTE, RST_HASTE, "moving faster", 0, 0, 0, 0, FALSE, 100, "starts", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(HEAL, RST_HEAL, "closing wounds", 0, 0, 0, 0, FALSE, 100, "magically starts", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(BLINK, RST_TACTIC|RST_ESCAPE, "phase door", 0, 0, 0, 0, FALSE, 100, "casts a", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(TPORT, RST_ESCAPE, "teleport away", 0, 0, 0, 0, FALSE, 100, "tries to", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "makes a soft 'pop'", NULL)
RSF(TELE_TO, RST_ANNOY, "come hither", 0, 0, 0, MSG_TELEPORT, FALSE, 100, "commands you to", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "commands you to come hither", NULL)
RSF(TELE_AWAY, RST_ESCAPE|RST_SPECIAL, "go away", 0, 0, GF_AWAY_ALL, MSG_TELEPORT, FALSE, 100, "commands you to", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "commands you to go away", "annihilated")
RSF(TELE_LEVEL, RST_ESCAPE|RST_SPECIAL, "go far away", 0, 0, GF_TELE_LEVEL, MSG_TPLEVEL, RSV_SKILL, 100, "commands you to", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "commands you to go far away", "annihilated")
RSF(DARKNESS, RST_ANNOY, "darkness", 0, 0, GF_DARK_WEAK, 0, FALSE, 100, "surrounds you in", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(TRAPS, RST_ANNOY, "traps", 0, 0, 0, MSG_CREATE_TRAP, FALSE, 100, "cackles evilly about", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "cackles evilly", NULL)
RSF(FORGET, RST_ATTACK|RST_ANNOY|RST_SPECIAL, "forget things", 0, 0, GF_FORGET, 0, RSV_SKILL|RSV_UNDEAD, 100, "tries to make you", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "messes with your mind", "annihilated")
RSF(ANIM_DEAD, RST_ANNOY|RST_SUMMON, "the dead", 0, 0, GF_RAISE, 0, FALSE, 100, "raises", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", "killed")
RSF(S_KIN, RST_SUMMON, "its kin", 0, 0, 0, MSG_SUM_MONSTER, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_HI_DEMON, RST_SUMMON, "major demons", 0, 0, 0, MSG_SUM_HI_DEMON, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_MONSTER, RST_SUMMON, "a companion", 0, 0, 0, MSG_SUM_MONSTER, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_MONSTERS, RST_SUMMON, "some friends", 0, 0, 0, MSG_SUM_MONSTER, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_ANIMAL, RST_SUMMON, "animals", 0, 0, 0, MSG_SUM_ANIMAL, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_SPIDER, RST_SUMMON, "spiders", 0, 0, 0, MSG_SUM_SPIDER, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_HOUND, RST_SUMMON, "hounds", 0, 0, 0, MSG_SUM_HOUND, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_HYDRA, RST_SUMMON, "hydrae", 0, 0, 0, MSG_SUM_HYDRA, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_AINU, RST_SUMMON, "an ainu", 0, 0, 0, MSG_SUM_AINU, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_DEMON, RST_SUMMON, "a demon", 0, 0, 0, MSG_SUM_DEMON, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_UNDEAD, RST_SUMMON, "the undead", 0, 0, 0, MSG_SUM_UNDEAD, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_DRAGON, RST_SUMMON, "a dragon", 0, 0, 0, MSG_SUM_DRAGON, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_HI_UNDEAD, RST_SUMMON, "fiends of darkness", 0, 0, 0, MSG_SUM_HI_UNDEAD, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_HI_DRAGON, RST_SUMMON, "ancient dragons", 0, 0, 0, MSG_SUM_HI_DRAGON, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_WRAITH, RST_SUMMON, "ringwraiths", 0, 0, 0, MSG_SUM_WRAITH, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)
RSF(S_UNIQUE, RST_SUMMON, "his servants", 0, 0, 0, MSG_SUM_UNIQUE, FALSE, 100, "summons", RV(0, 0, 0, 0), RV(0, 0, 0, 0), "mumbles", NULL)

/* PWMAngband (PvP) */
RSF(MAGE_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(PRIEST_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(SORC_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(SHAD_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(HUNT_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(PSI_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(DEATH_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(GHOST_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(MIMIC_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(ELEM_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(SUMMON_PROJECT, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(STUN, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(POLY, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
RSF(PSI, 0, NULL, 0, 0, 0, 0, FALSE, 0, NULL, RV(0, 0, 0, 0), RV(0, 0, 0, 0), NULL, NULL)
