/*
 * File: list-tvals.h
 * Purpose: List of object base types
 */

/* string  name */
TV(NULL, "none")
TV(SKELETON, "skeleton")
TV(BOTTLE, "bottle")
TV(STONE, "stone")
TV(CORPSE, "corpse")
TV(DEED, "deed")
TV(CHEST, "chest")
TV(HORN, "horn")
TV(ROCK, "rock")
TV(SHOT, "shot")
TV(ARROW, "arrow")
TV(BOLT, "bolt")
TV(BOW, "bow")
TV(DIGGING, "digger")
TV(HAFTED, "hafted")
TV(POLEARM, "polearm")
TV(SWORD, "sword")
TV(MSTAFF, "mage staff")
TV(BOOTS, "boots")
TV(GLOVES, "gloves")
TV(HELM, "helm")
TV(CROWN, "crown")
TV(SHIELD, "shield")
TV(CLOAK, "cloak")
TV(SOFT_ARMOR, "soft armour")
TV(HARD_ARMOR, "hard armour")
TV(DRAG_ARMOR, "dragon armour")
TV(LIGHT, "light")
TV(AMULET, "amulet")
TV(RING, "ring")
TV(STAFF, "staff")
TV(WAND, "wand")
TV(ROD, "rod")
TV(SCROLL, "scroll")
TV(POTION, "potion")
TV(FLASK, "flask")
TV(FOOD, "food")
TV(MUSHROOM, "mushroom")
TV(CROP, "crop")
TV(MAGIC_BOOK, "magic book")
TV(PRAYER_BOOK, "prayer book")
TV(NATURE_BOOK, "nature book")
TV(SHADOW_BOOK, "shadow book")
TV(PSI_BOOK, "psi book")
TV(ELEM_BOOK, "elemental book")
TV(GHOST_REALM, "ghost realm")
TV(MIMIC_REALM, "mimic realm")
TV(COOKIE, "fortune cookie")
TV(GOLD, "gold")