set loc en

#
# Kingly window
#

# Window title
::msgcat::mcset $loc Winner!

# Window
::msgcat::mcset $loc "Veni, Vidi, Vici!\n"
::msgcat::mcset $loc "I came, I saw, I conquered!\n"
::msgcat::mcset $loc "All Hail the Mighty King!"
::msgcat::mcset $loc "All Hail the Mighty Queen!"

# Buttons
::msgcat::mcset $loc Continue

#
# Tomb window
#

# Window title
::msgcat::mcset $loc Tomb

# Window
::msgcat::mcset $loc RIP
::msgcat::mcset $loc "by %s"
::msgcat::mcset $loc the
::msgcat::mcset $loc "Level: %s"
::msgcat::mcset $loc "Exp: %s"
::msgcat::mcset $loc "AU: %s"
::msgcat::mcset $loc "Killed on Level %s"

# Buttons
::msgcat::mcset $loc Messages
::msgcat::mcset $loc File
::msgcat::mcset $loc Continue

#
# Character Record Options window
#

# Window title
::msgcat::mcset $loc "Character Record"

# Window
::msgcat::mcset $loc *prompt \
	"Choose the information you wish to be kept for your character.\
	The information can be viewed in the High Scores Window."
::msgcat::mcset $loc Options
::msgcat::mcset $loc "Character dump"
::msgcat::mcset $loc "Message log"
::msgcat::mcset $loc "Photo"
::msgcat::mcset $loc "Photo (Img extension missing)"

