set loc ja

#
# Kingly window
#

# Window title
::msgcat::mcset $loc Winner! 勝利者！

# Window
::msgcat::mcset $loc "Veni, Vidi, Vici!\n"
::msgcat::mcset $loc "I came, I saw, I conquered!\n" "来た、見た、勝った！\n"
::msgcat::mcset $loc "All Hail the Mighty King!" 偉大なるキング万歳！
::msgcat::mcset $loc "All Hail the Mighty Queen!" 偉大なるクイーン万歳！

# Buttons
::msgcat::mcset $loc Continue 続行

#
# Tomb window
#

# Window title
::msgcat::mcset $loc Tomb 墓碑銘

# Window
::msgcat::mcset $loc RIP 安らかに眠れ
::msgcat::mcset $loc "by %s" "%sに殺される"
::msgcat::mcset $loc the " "
::msgcat::mcset $loc "Level: %s" "レベル: %s"
::msgcat::mcset $loc "Exp: %s" "経験値: %s"
::msgcat::mcset $loc "AU: %s" "所持金: %s"
::msgcat::mcset $loc "Killed on Level %s" "地下%s階で"

# Buttons
::msgcat::mcset $loc Messages メッセージ
::msgcat::mcset $loc File ファイル
::msgcat::mcset $loc Continue 続行

#
# Character Record Options window
#

# Window title
::msgcat::mcset $loc "Character Record" キャラクター記録

# Window
::msgcat::mcset $loc *prompt \
"保存したい情報を選択してください。後でハイスコアウィンドウから見る事ができます。"
::msgcat::mcset $loc Options オプション
::msgcat::mcset $loc "Character dump" キャラクタ情報保存
::msgcat::mcset $loc "Message log" メッセージ履歴
::msgcat::mcset $loc "Photo" 記念写真
::msgcat::mcset $loc "Photo (Img extension missing)" 記念写真(拡張子なし)

