MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = Classes.txt \
Demigods.txt \
Demons.txt \
Draconians.txt \
DragonRealms.txt \
Dragons.txt \
MonsterRaces.txt \
Personalities.txt \
Races.txt \
Warlocks.txt \
Weaponmasters.txt \
attack.txt \
attack_contents.txt \
birth.txt \
birth_contents.txt \
bldg.txt \
command.txt \
command_contents.txt \
commdesc.txt \
commdesc_contents.txt \
context_message_recall.txt \
context_monster_list.txt \
context_more_prompt.txt \
context_object_list.txt \
context_targetting.txt \
defend.txt \
defend_contents.txt \
dungeon.txt \
dungeon_contents.txt \
editor.txt \
editor_contents.txt \
faq.txt \
gambling.txt \
general.txt \
general_contents.txt \
helpinfo.txt \
magic.txt \
magic_contents.txt \
monster.txt \
monster_contents.txt \
objects.txt \
objects_contents.txt \
option.txt \
option_contents.txt \
pref.txt \
pref_contents.txt \
raceclass_contents.txt \
rings.txt \
start.txt \
tang.txt \
tang_contents.txt \
town.txt \
town_contents.txt \
version.txt

PACKAGE = help

