
/* $Id: strings.h,v 1.5 2003/04/06 15:21:34 cipher Exp $ */

#ifndef IH_SDL_STRINGS_H
#define IH_SDL_STRINGS_H

/*
 * Copyright (c) 2003 Paul A. Schifferer
 *
 * This software may be copied and distributed for educational, research,
 * and not for profit purposes provided that this copyright and statement
 * are included in all such copies.  Other copyrights may also apply.
 */

#define IH_TEXT_TITLE_PROGRAM "Iron Hells"
#define IH_TEXT_TITLE_COPYRIGHT "Copyright (c) 2003 Paul A. Schifferer"
#define IH_TEXT_TITLE_VERSION "v1.0a4"

#define IH_TEXT_SELCHAR_CHARACTERS "Characters"
#define IH_TEXT_SELCHAR_LOAD "Load character"
#define IH_TEXT_SELCHAR_NEW "Create new character"
#define IH_TEXT_SELCHAR_OPTIONS "Options"
#define IH_TEXT_SELCHAR_VIDEO "Display Options"
#define IH_TEXT_SELCHAR_QUIT "Quit"

#define IH_TEXT_VIDEO_SETDISPLAY "Set Display Options"
#define IH_TEXT_VIDEO_RESOLUTION "Resolution"
#define IH_TEXT_VIDEO_DEPTH "Depth"
#define IH_TEXT_VIDEO_HWACCEL_FMT "Hardware Acceleration: %s"
#define IH_TEXT_VIDEO_HWACCEL_ON "On"
#define IH_TEXT_VIDEO_HWACCEL_OFF "Off"
#define IH_TEXT_VIDEO_FULLSCREEN_FMT "Screen Mode: %s"
#define IH_TEXT_VIDEO_FULLSCREEN_ON "Fullscreen"
#define IH_TEXT_VIDEO_FULLSCREEN_OFF "Windowed"
#define IH_TEXT_VIDEO_MODE_FMT "Mode: %dx%dx%d"
#define IH_TEXT_VIDEO_ACCEPT "Accept"
#define IH_TEXT_VIDEO_CANCEL "Cancel"

#define IH_TEXT_NEWCHAR_CHOOSEGENDER "Choose Gender"
#define IH_TEXT_NEWCHAR_GENDER "Gender"
#define IH_TEXT_NEWCHAR_CHOOSERACE "Choose Race"
#define IH_TEXT_NEWCHAR_RACE "Race"
#define IH_TEXT_NEWCHAR_CHOOSECLASS "Choose Class"
#define IH_TEXT_NEWCHAR_CLASS "Class"
#define IH_TEXT_NEWCHAR_MODIFYOPTIONS "Modify Options"
#define IH_TEXT_NEWCHAR_YES "Yes"
#define IH_TEXT_NEWCHAR_NO "No"
#define IH_TEXT_NEWCHAR_ROLLSTATS "Generate Ability Scores"
#define IH_TEXT_NEWCHAR_STR "Strength"
#define IH_TEXT_NEWCHAR_INT "Intelligence"
#define IH_TEXT_NEWCHAR_WIS "Wisdom"
#define IH_TEXT_NEWCHAR_DEX "Dexterity"
#define IH_TEXT_NEWCHAR_CON "Constitution"
#define IH_TEXT_NEWCHAR_CHA "Charisma"
#define IH_TEXT_NEWCHAR_GETNAME "Name Character"
#define IH_TEXT_NEWCHAR_DONE "Done"
#define IH_TEXT_NEWCHAR_FINALIZE "Finalize Character"
#define IH_TEXT_NEWCHAR_REROLL "Roll Again"
#define IH_TEXT_NEWCHAR_LOADPREV "Load Previous"
#define IH_TEXT_NEWCHAR_GETNAME "Name Character"
#define IH_TEXT_NEWCHAR_FINALIZE "Finalize Character"
#define IH_TEXT_NEWCHAR_DONE "Done"
#define IH_TEXT_NEWCHAR_BACK "Back"
#define IH_TEXT_NEWCHAR_STARTOVER "Start Over"
#define IH_TEXT_NEWCHAR_RANDOM "Random"
#define IH_TEXT_NEWCHAR_NEXT "Next"
#define IH_TEXT_NEWCHAR_PLAY "Play"

#define IH_TEXT_CHARINFO_NAME "Name"
#define IH_TEXT_CHARINFO_GENDER "Gender"
#define IH_TEXT_CHARINFO_RACE "Race"
#define IH_TEXT_CHARINFO_CLASS "Class"
#define IH_TEXT_CHARINFO_TITLE "Title"
#define IH_TEXT_CHARINFO_HP "HP"
#define IH_TEXT_CHARINFO_SP "SP"
#define IH_TEXT_CHARINFO_LEVEL "Level"
#define IH_TEXT_CHARINFO_CUREXP "Cur. Exp."
#define IH_TEXT_CHARINFO_MAXEXP "Max. Exp."
#define IH_TEXT_CHARINFO_ADVEXP "Adv. Exp."
#define IH_TEXT_CHARINFO_GOLD "Gold"
#define IH_TEXT_CHARINFO_BURDEN "Burden"
#define IH_TEXT_CHARINFO_AGE "Age"
#define IH_TEXT_CHARINFO_HEIGHT "Height"
#define IH_TEXT_CHARINFO_WEIGHT "Weight"
#define IH_TEXT_CHARINFO_STATUS "Status"
#define IH_TEXT_CHARINFO_MAXIMIZE "Maximize"
#define IH_TEXT_CHARINFO_PRESERVE "Preserve"
#define IH_TEXT_CHARINFO_ARMOR "Armor"
#define IH_TEXT_CHARINFO_FIGHT "Fight"
#define IH_TEXT_CHARINFO_MELEE "Melee"
#define IH_TEXT_CHARINFO_SHOOT "Shoot"
#define IH_TEXT_CHARINFO_BLOWS "Blows"
#define IH_TEXT_CHARINFO_SHOTS "Shots"
#define IH_TEXT_CHARINFO_INFRA "Infra"
#define IH_TEXT_CHARINFO_SAVINGTHROW "Saving Throw"
#define IH_TEXT_CHARINFO_STEALTH "Stealth"
#define IH_TEXT_CHARINFO_FIGHTING "Fighting"
#define IH_TEXT_CHARINFO_SHOOTING "Shooting"
#define IH_TEXT_CHARINFO_DISARMING "Disarming"
#define IH_TEXT_CHARINFO_MAGICDEVICE "Magic Device"
#define IH_TEXT_CHARINFO_PERCEPTION "Perception"
#define IH_TEXT_CHARINFO_SEARCHING "Searching"
#define IH_TEXT_CHARINFO_SELF "Self"
#define IH_TEXT_CHARINFO_RB "RB"
#define IH_TEXT_CHARINFO_CB "CB"
#define IH_TEXT_CHARINFO_EB "EB"
#define IH_TEXT_CHARINFO_BEST "Best"
#define IH_TEXT_CHARINFO_STR "STR"
#define IH_TEXT_CHARINFO_INT "INT"
#define IH_TEXT_CHARINFO_WIS "WIS"
#define IH_TEXT_CHARINFO_DEX "DEX"
#define IH_TEXT_CHARINFO_CON "CON"
#define IH_TEXT_CHARINFO_CHA "CHA"
#define IH_TEXT_CHARINFO_Str "Str"
#define IH_TEXT_CHARINFO_Int "Int"
#define IH_TEXT_CHARINFO_Wis "Wis"
#define IH_TEXT_CHARINFO_Dex "Dex"
#define IH_TEXT_CHARINFO_Con "Con"
#define IH_TEXT_CHARINFO_Cha "Cha"

#define IH_TEXT_OVERLAY_BOOK_COLUMN_NAME "Name"
#define IH_TEXT_OVERLAY_BOOK_COLUMN_LEVEL "Lev"
#define IH_TEXT_OVERLAY_BOOK_COLUMN_MANA "Mana"
#define IH_TEXT_OVERLAY_BOOK_COLUMN_FAIL "Fail"
#define IH_TEXT_OVERLAY_BOOK_COLUMN_INFO "Info"
#define IH_TEXT_OVERLAY_BOOK_ILLEGIBLE "(illegible)"
#define IH_TEXT_OVERLAY_BOOK_COMMENT_FORGOTTEN "forgotten"
#define IH_TEXT_OVERLAY_BOOK_COMMENT_UNKNOWN "unknown"
#define IH_TEXT_OVERLAY_BOOK_COMMENT_DIFFICULT "difficult"
#define IH_TEXT_OVERLAY_BOOK_COMMENT_UNTRIED "untried"

#endif /* IH_SDL_STRINGS_H */
