subdir = ./lib/bone/

## makefile.zb

srcfiles += lib/bone/makefile.zb

INSTALL += \
		if [ -n "$(GAMEGROUP)" ]; then \
			chown -R $(GAMEGROUP) "$(DESTDIR)/lib/bone"; \
			chmod -R 070 "$(DESTDIR)/lib/bone"; \
		fi;
