set loc en

# Window title
::msgcat::mcset $loc title "Alternate Editor"

# Menus
::msgcat::mcset $loc Alternate
::msgcat::mcset $loc "New Alternate"

::msgcat::mcset $loc Reason
::msgcat::mcset $loc reason-none None
::msgcat::mcset $loc reason-feature Feature
::msgcat::mcset $loc reason-ident Ident
::msgcat::mcset $loc reason-number Number

# Statusbar
::msgcat::mcset $loc browser-type "Icon type \"%s\"."
