MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = colors.prf font-x11.prf graf.prf pref-ami.prf pref-x11.prf \
font-ami.prf font-xxx.prf graf-win.prf pref-emx.prf proxy.prf \
font-dos.prf graf-ami.prf graf-x11.prf pref-gcu.prf spell-xx.prf \
font-ibm.prf graf-dos.prf graf-xaw.prf pref-key.prf user.prf graf-sdl.prf \
font-mac.prf graf-gcu.prf graf-xxx.prf pref-mac.prf user-lim.prf \
user-win.prf font-mon.prf graf-ibm.prf pickpref.prf pref-opt.prf \
xtra-gcu.prf font.prf graf-mac.prf picktype.prf pref.prf xtra-new.prf \
font-sdl.prf font-win.prf graf-new.prf pref-acn.prf pref-win.prf xtra-xxx.prf
PACKAGE = pref

