MKPATH=../../mk/
include $(MKPATH)buildsys.mk

CONFIG = classes.prf flvr-dvg.prf flvr-new.prf flvr-xxx.prf \
font.prf font-mac.prf font-sdl.prf font-win.prf font-x11.prf \
font-xxx.prf graf.prf graf-dvg.prf graf-gcu.prf font-gcu.prf \
font-gtk.prf graf-mac.prf graf-new.prf graf-sdl.prf graf-win.prf \
graf-x11.prf graf-xxx.prf message.prf pref.prf pref-gcu.prf \
pref-mac.prf pref-sdl.prf pref-win.prf pref-x11.prf \
races.prf shades.prf user.prf user-mac.prf xtra-dvg.prf \
xtra-new.prf xtra-xxx.prf

PACKAGE = pref

