set loc ja

::msgcat::mcset $loc title Icons
::msgcat::mcset $loc M_ICONS Icons

::msgcat::mcset $loc ascii-frame-font Font
::msgcat::mcset $loc ascii-frame-color Color
::msgcat::mcset $loc ascii-frame-size Size
::msgcat::mcset $loc button-change Change...
::msgcat::mcset $loc ascii-label-color "You can choose background colors for icons."
::msgcat::mcset $loc ascii-button-square "Make icon width equal to icon height"
::msgcat::mcset $loc ascii-button-update Update

::msgcat::mcset $loc tab-config Configuration
::msgcat::mcset $loc tab-ascii Ascii
