MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

# compile fonts for .gtk and x11
include Makefile.am
LIBDATA = 5x8x.bdf 5x8x.fon 6x10x.bdf 6x10x.fon 8x8x.bdf 8x8x.fon  \
       8x8xb.bdf 8x8xb.fon 8x12x.bdf 8x12x.fon 8x12xb.bdf 8x12xb.fon \
       8x16x.bdf 8x16x.fon 10x14x.bdf 10x14x.fon 10x14xb.bdf 10x14xb.fon \
       10x14x.fon 10x14xb.bdf 10x14xb.fon 12x18x.bdf 12x18x.fon 12x24.fon \
       16x16x.bdf 16x16x.fon 16x24x.bdf 16x24x.fon
PACKAGE = xtra/font