MKPATH=../../../mk/
include $(MKPATH)buildsys.mk

DATA = 10X20.FON 6X13B.FON 8X13B.FON xm10x17.fnt xm4x6.fnt xm8x13.fnt \
12X24.FON 6X13.FON 8X13.FON xm12x20b.fnt xm5x8.fnt xm8x16b.fnt \
5X8.FON 6X9.FON 9X15B.FON xm12x20.fnt xm6x12b.fnt xm8x16.fnt \
6X10.FON 7X13B.FON 9X15.FON xm16x25b.fnt xm6x12.fnt \
6X12.FON 7X13.FON xm10x17b.fnt xm16x25.fnt xm8x13b.fnt
PACKAGE = xtra/font
