MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = \
	chainswd.txt \
	credits.txt \
	dead.txt \
	death.txt \
	elvish.txt \
	error.txt \
	mondeath.txt \
	monfear.txt \
	monfrien.txt \
	monspeak.txt \
	news10.txt \
	news11.txt \
	news12.txt \
	news13.txt \
	news14.txt \
	news15.txt \
	news16.txt \
	news17.txt \
	news18.txt \
	news19.txt \
	news1.txt \
	news2.txt \
	news3.txt \
	news4.txt \
	news5.txt \
	news6.txt \
	news7.txt \
	news8.txt \
	news9.txt \
	news.txt \
	rumors.txt \
	seppuku.txt \
	silly.txt \
	sname.txt \
	timefun.txt \
	timenorm.txt

PACKAGE = file

