MKPATH=../../mk/
include $(MKPATH)buildsys.mk

DATA = a_cursed.txt \
a_high.txt \
a_low.txt \
a_med.txt \
aa_med.txt \
ab_med.txt \
ac_med.txt \
ag_med.txt \
ah_med.txt \
amulet_cursed.txt \
amulet_high.txt \
amulet_low.txt \
amulet_med.txt \
as_med.txt \
book-0_jp.txt \
chainswd.txt \
credits.txt \
dead.txt \
death.txt \
elvish.txt \
error.txt \
lite_cursed.txt \
lite_high.txt \
lite_low.txt \
lite_med.txt \
mondeath.txt \
monfear.txt \
monfrien.txt \
monspeak.txt \
namebase.txt \
news.txt \
news1.txt \
news10.txt \
news11.txt \
news12.txt \
news13.txt \
news14.txt \
news15.txt \
news16.txt \
news17.txt \
news18.txt \
news19.txt \
news2.txt \
news3.txt \
news4.txt \
news5.txt \
news6.txt \
news7.txt \
news8.txt \
news9.txt \
ranged.txt \
ring_cursed.txt \
ring_high.txt \
ring_low.txt \
ring_med.txt \
rumors.txt \
seppuku.txt \
silly.txt \
sname.txt \
timefun.txt \
timenorm.txt \
w_cursed.txt \
w_hafted.txt \
w_high.txt \
w_low.txt \
w_med.txt \
w_pole.txt \
w_sword.txt \
w_types.txt

PACKAGE = file

